// A1 — 300 ta so'z (week 1)
// [word, translation, phonetic, example_sentence]
export const A1_RAW: [string, string, string, string][] = [
  // ── Numbers (one–twenty) ──
  ['one', 'bir', '/wʌn/', 'I have one brother.'],
  ['two', 'ikki', '/tuː/', 'She has two cats.'],
  ['three', 'uch', '/θriː/', 'There are three books.'],
  ['four', 'tort', '/fɔː/', 'My car has four doors.'],
  ['five', 'besh', '/faɪv/', 'I see five birds.'],
  ['six', 'olti', '/sɪks/', 'The box has six apples.'],
  ['seven', 'yetti', '/ˈsevən/', 'A week has seven days.'],
  ['eight', 'sakkiz', '/eɪt/', 'He is eight years old.'],
  ['nine', 'toqqiz', '/naɪn/', 'There are nine students.'],
  ['ten', 'oʻn', '/ten/', 'I have ten fingers.'],
  ['eleven', 'oʻn bir', '/ɪˈlevən/', 'The bus comes at eleven.'],
  ['twelve', 'oʻn ikki', '/twelv/', 'A year has twelve months.'],
  ['thirteen', 'oʻn uch', '/ˌθɜːˈtiːn/', 'She is thirteen now.'],
  ['fourteen', 'oʻn tort', '/ˌfɔːˈtiːn/', 'He read fourteen pages.'],
  ['fifteen', 'oʻn besh', '/ˌfɪfˈtiːn/', 'We waited fifteen minutes.'],
  ['sixteen', 'oʻn olti', '/ˌsɪksˈtiːn/', 'My sister is sixteen.'],
  ['seventeen', 'oʻn yetti', '/ˌsevənˈtiːn/', 'There are seventeen chairs.'],
  ['eighteen', 'oʻn sakkiz', '/ˌeɪˈtiːn/', 'You can vote at eighteen.'],
  ['nineteen', 'oʻn toqqiz', '/ˌnaɪnˈtiːn/', 'He scored nineteen points.'],
  ['twenty', 'yigirma', '/ˈtwenti/', 'I have twenty dollars.'],
  // ── Colors ──
  ['red', 'qizil', '/red/', 'The apple is red.'],
  ['blue', 'koʻk', '/bluː/', 'The sky is blue.'],
  ['green', 'yashil', '/ɡriːn/', 'Grass is green.'],
  ['yellow', 'sariq', '/ˈjeləʊ/', 'The sun is yellow.'],
  ['black', 'qora', '/blæk/', 'My shoes are black.'],
  ['white', 'oq', '/waɪt/', 'Snow is white.'],
  ['orange', 'toʻq sariq', '/ˈɒrɪndʒ/', 'I like the orange ball.'],
  ['brown', 'jigarrang', '/braʊn/', 'The dog is brown.'],
  ['pink', 'pushti', '/pɪŋk/', 'She wears a pink dress.'],
  ['purple', 'binafsha', '/ˈpɜːpəl/', 'The flower is purple.'],
  ['grey', 'kulrang', '/ɡreɪ/', 'The cat is grey.'],
  ['gold', 'oltin rang', '/ɡəʊld/', 'The ring is gold.'],
  // ── Family members ──
  ['mother', 'ona', '/ˈmʌðər/', 'My mother is a teacher.'],
  ['father', 'ota', '/ˈfɑːðər/', 'His father works in a bank.'],
  ['brother', 'aka/uka', '/ˈbrʌðər/', 'I have one brother.'],
  ['sister', 'opa/singil', '/ˈsɪstər/', 'Her sister is a doctor.'],
  ['son', 'oʻgʻil', '/sʌn/', 'They have one son.'],
  ['daughter', 'qiz', '/ˈdɔːtər/', 'Their daughter is five.'],
  ['parent', 'ota-ona', '/ˈpeərənt/', 'My parents live here.'],
  ['child', 'bola', '/tʃaɪld/', 'The child is sleeping.'],
  ['baby', 'chaqaloq', '/ˈbeɪbi/', 'The baby is crying.'],
  ['grandmother', 'buvi', '/ˈɡrænmʌðər/', 'My grandmother bakes bread.'],
  ['grandfather', 'bobo', '/ˈɡrænfɑːðər/', 'His grandfather is old.'],
  ['uncle', 'amaki/togʻa', '/ˈʌŋkəl/', 'My uncle lives abroad.'],
  ['aunt', 'amma/xola', '/ɑːnt/', 'Her aunt is kind.'],
  ['husband', 'er', '/ˈhʌzbənd/', 'Her husband is tall.'],
  ['wife', 'xotin', '/waɪf/', 'His wife is a nurse.'],
  // ── Body parts ──
  ['head', 'bosh', '/hed/', 'My head hurts.'],
  ['hair', 'soch', '/heər/', 'She has long hair.'],
  ['eye', 'koʻz', '/aɪ/', 'He has blue eyes.'],
  ['ear', 'quloq', '/ɪər/', 'My ear hurts.'],
  ['nose', 'burun', '/nəʊz/', 'The dog has a wet nose.'],
  ['mouth', 'ogʻiz', '/maʊθ/', 'Open your mouth, please.'],
  ['tooth', 'tish', '/tuːθ/', 'Brush your tooth well.'],
  ['tongue', 'til', '/tʌŋ/', 'The doctor checked my tongue.'],
  ['face', 'yuz', '/feɪs/', 'Wash your face.'],
  ['neck', 'boʻyin', '/nek/', 'My neck is stiff.'],
  ['shoulder', 'yelka', '/ˈʃəʊldər/', 'He carries a bag on his shoulder.'],
  ['arm', 'qoʻl (yelkadan)', '/ɑːm/', 'She broke her arm.'],
  ['hand', 'qoʻl (panja)', '/hænd/', 'Wash your hands.'],
  ['finger', 'barmoq', '/ˈfɪŋɡər/', 'I cut my finger.'],
  ['leg', 'oyoq', '/leɡ/', 'My leg hurts.'],
  ['knee', 'tizza', '/niː/', 'He fell on his knee.'],
  ['foot', 'oyoq panjasi', '/fʊt/', 'My foot is cold.'],
  ['back', 'orqa', '/bæk/', 'My back hurts.'],
  ['stomach', 'qorin', '/ˈstʌmək/', 'My stomach hurts.'],
  ['heart', 'yurak', '/hɑːt/', 'Her heart beats fast.'],
  // ── Home objects ──
  ['house', 'uy', '/haʊs/', 'They live in a big house.'],
  ['door', 'eshik', '/dɔː/', 'Please close the door.'],
  ['window', 'deraza', '/ˈwɪndəʊ/', 'Open the window.'],
  ['table', 'stol', '/ˈteɪbəl/', 'The food is on the table.'],
  ['chair', 'stul', '/tʃeər/', 'Sit on the chair.'],
  ['bed', 'karavot', '/bed/', 'I sleep in my bed.'],
  ['sofa', 'divan', '/ˈsəʊfə/', 'The cat sleeps on the sofa.'],
  ['lamp', 'chiroq', '/læmp/', 'Turn on the lamp.'],
  ['clock', 'soat', '/klɒk/', 'The clock is on the wall.'],
  ['key', 'kalit', '/kiː/', 'I lost my key.'],
  ['wall', 'devor', '/wɔːl/', 'The wall is white.'],
  ['floor', 'pol', '/flɔː/', 'The floor is clean.'],
  ['roof', 'tom', '/ruːf/', 'The roof is red.'],
  ['kitchen', 'oshxona', '/ˈkɪtʃɪn/', 'She cooks in the kitchen.'],
  ['bathroom', 'hammom', '/ˈbɑːθruːm/', 'The bathroom is upstairs.'],
  ['bedroom', 'yotoqxona', '/ˈbedruːm/', 'My bedroom is small.'],
  ['mirror', 'koʻzgu', '/ˈmɪrər/', 'She looks in the mirror.'],
  ['cup', 'piyola', '/kʌp/', 'I drink from this cup.'],
  ['plate', 'tarelka', '/pleɪt/', 'Put the food on a plate.'],
  ['spoon', 'qoshiq', '/spuːn/', 'Eat soup with a spoon.'],
  ['fork', 'vilka', '/fɔːk/', 'Use a fork, please.'],
  ['knife', 'pichoq', '/naɪf/', 'The knife is sharp.'],
  ['bottle', 'shisha', '/ˈbɒtəl/', 'The bottle is empty.'],
  ['box', 'quti', '/bɒks/', 'The box is heavy.'],
  ['bag', 'sumka', '/bæɡ/', 'My bag is full.'],
  // ── School items ──
  ['school', 'maktab', '/skuːl/', 'I go to school.'],
  ['book', 'kitob', '/bʊk/', 'This book is interesting.'],
  ['pen', 'ruchka', '/pen/', 'Write with a pen.'],
  ['pencil', 'qalam', '/ˈpensəl/', 'My pencil is broken.'],
  ['paper', 'qogʻoz', '/ˈpeɪpər/', 'I need some paper.'],
  ['notebook', 'daftar', '/ˈnəʊtbʊk/', 'Open your notebook.'],
  ['desk', 'parta', '/desk/', 'The student sits at a desk.'],
  ['board', 'doska', '/bɔːd/', 'Look at the board.'],
  ['teacher', 'oʻqituvchi', '/ˈtiːtʃər/', 'Our teacher is kind.'],
  ['student', 'oʻquvchi', '/ˈstjuːdənt/', 'She is a good student.'],
  ['lesson', 'dars', '/ˈlesən/', 'The lesson starts now.'],
  ['class', 'sinf', '/klɑːs/', 'Our class is big.'],
  ['homework', 'uy vazifasi', '/ˈhəʊmwɜːk/', 'Do your homework.'],
  ['exam', 'imtihon', '/ɪɡˈzæm/', 'The exam is hard.'],
  ['question', 'savol', '/ˈkwestʃən/', 'Ask me a question.'],
  ['answer', 'javob', '/ˈɑːnsər/', 'Give me the answer.'],
  ['word', 'soʻz', '/wɜːd/', 'Learn a new word.'],
  ['letter', 'harf/xat', '/ˈletər/', 'Write the letter A.'],
  ['number', 'raqam', '/ˈnʌmbər/', 'What is your number?'],
  ['ruler', 'chizgʻich', '/ˈruːlər/', 'Use a ruler to draw lines.'],
  // ── Food & drinks ──
  ['food', 'ovqat', '/fuːd/', 'The food is hot.'],
  ['water', 'suv', '/ˈwɔːtər/', 'I drink water every day.'],
  ['milk', 'sut', '/mɪlk/', 'The baby drinks milk.'],
  ['tea', 'choy', '/tiː/', 'I like green tea.'],
  ['coffee', 'qahva', '/ˈkɒfi/', 'He drinks coffee in the morning.'],
  ['juice', 'sharbat', '/dʒuːs/', 'I want orange juice.'],
  ['bread', 'non', '/bred/', 'We eat bread every day.'],
  ['rice', 'guruch', '/raɪs/', 'They eat rice with meat.'],
  ['meat', 'goʻsht', '/miːt/', 'The meat is delicious.'],
  ['fish', 'baliq', '/fɪʃ/', 'We eat fish on Friday.'],
  ['chicken', 'tovuq', '/ˈtʃɪkɪn/', 'I cooked chicken for dinner.'],
  ['egg', 'tuxum', '/eɡ/', 'I eat an egg for breakfast.'],
  ['cheese', 'pishloq', '/tʃiːz/', 'She likes cheese.'],
  ['butter', 'sariyogʻ', '/ˈbʌtər/', 'Put butter on the bread.'],
  ['sugar', 'shakar', '/ˈʃʊɡər/', 'No sugar in my tea, please.'],
  ['salt', 'tuz', '/sɔːlt/', 'Add some salt to the soup.'],
  ['soup', 'shoʻrva', '/suːp/', 'The soup is hot.'],
  ['salad', 'salat', '/ˈsæləd/', 'I made a fresh salad.'],
  ['fruit', 'meva', '/fruːt/', 'Eat more fruit.'],
  ['apple', 'olma', '/ˈæpəl/', 'I eat an apple a day.'],
  ['banana', 'banan', '/bəˈnɑːnə/', 'The banana is yellow.'],
  ['orange (fruit)', 'apelsin', '/ˈɒrɪndʒ/', 'This orange is sweet.'],
  ['grape', 'uzum', '/ɡreɪp/', 'The grapes are sweet.'],
  ['melon', 'qovun', '/ˈmelən/', 'The melon is very sweet.'],
  ['tomato', 'pomidor', '/təˈmɑːtəʊ/', 'I need one tomato.'],
  ['potato', 'kartoshka', '/pəˈteɪtəʊ/', 'We boiled the potatoes.'],
  ['onion', 'piyoz', '/ˈʌnjən/', 'Cut the onion small.'],
  ['carrot', 'sabzi', '/ˈkærət/', 'Rabbits eat carrots.'],
  ['vegetable', 'sabzavot', '/ˈvedʒtəbəl/', 'Eat your vegetables.'],
  ['cake', 'tort', '/keɪk/', 'The cake is sweet.'],
  ['candy', 'konfet', '/ˈkændi/', 'Children love candy.'],
  ['ice cream', 'muzqaymoq', '/aɪs kriːm/', 'I want ice cream.'],
  ['breakfast', 'nonushta', '/ˈbrekfəst/', 'I eat breakfast at seven.'],
  ['lunch', 'tushlik', '/lʌntʃ/', 'We have lunch at one.'],
  ['dinner', 'kechki ovqat', '/ˈdɪnər/', 'Dinner is ready.'],
  // ── Animals ──
  ['dog', 'it', '/dɒɡ/', 'The dog is friendly.'],
  ['cat', 'mushuk', '/kæt/', 'The cat is sleeping.'],
  ['bird', 'qush', '/bɜːd/', 'The bird is singing.'],
  ['cow', 'sigir', '/kaʊ/', 'The cow gives milk.'],
  ['horse', 'ot', '/hɔːs/', 'He rides a horse.'],
  ['sheep', 'qoʻy', '/ʃiːp/', 'The sheep eat grass.'],
  ['goat', 'echki', '/ɡəʊt/', 'The goat is white.'],
  ['chicken (animal)', 'tovuq (hayvon)', '/ˈtʃɪkɪn/', 'The chicken lays eggs.'],
  ['duck', 'oʻrdak', '/dʌk/', 'The duck swims in the lake.'],
  ['rabbit', 'quyon', '/ˈræbɪt/', 'The rabbit is fast.'],
  ['mouse', 'sichqon', '/maʊs/', 'The cat caught a mouse.'],
  ['lion', 'sher', '/ˈlaɪən/', 'The lion is the king.'],
  ['tiger', 'yoʻlbars', '/ˈtaɪɡər/', 'The tiger is dangerous.'],
  ['bear', 'ayiq', '/beər/', 'The bear is big.'],
  ['elephant', 'fil', '/ˈelɪfənt/', 'The elephant is huge.'],
  ['monkey', 'maymun', '/ˈmʌŋki/', 'The monkey climbs trees.'],
  ['fox', 'tulki', '/fɒks/', 'The fox is clever.'],
  ['wolf', 'boʻri', '/wʊlf/', 'The wolf hunts at night.'],
  ['snake', 'ilon', '/sneɪk/', 'The snake is long.'],
  ['frog', 'baqa', '/frɒɡ/', 'The frog jumps high.'],
  ['fish (animal)', 'baliq (hayvon)', '/fɪʃ/', 'The fish swims fast.'],
  ['insect', 'hasharot', '/ˈɪnsekt/', 'An insect flew into the room.'],
  ['bee', 'asalari', '/biː/', 'The bee makes honey.'],
  ['butterfly', 'kapalak', '/ˈbʌtəflaɪ/', 'The butterfly is beautiful.'],
  ['spider', 'oʻrgimchak', '/ˈspaɪdər/', 'The spider made a web.'],
  // ── Basic verbs ──
  ['go', 'bormoq', '/ɡəʊ/', 'I go to school every day.'],
  ['eat', 'yemoq', '/iːt/', 'We eat dinner at seven.'],
  ['drink', 'ichmoq', '/drɪŋk/', 'I drink water.'],
  ['sleep', 'uxlamoq', '/sliːp/', 'Babies sleep a lot.'],
  ['run', 'yugurmoq', '/rʌn/', 'He runs every morning.'],
  ['walk', 'yurmoq', '/wɔːk/', 'I walk to work.'],
  ['sit', 'oʻtirmoq', '/sɪt/', 'Please sit down.'],
  ['stand', 'turmoq', '/stænd/', 'Please stand up.'],
  ['read', 'oʻqimoq', '/riːd/', 'I read a book at night.'],
  ['write', 'yozmoq', '/raɪt/', 'Write your name here.'],
  ['play', 'oʻynamoq', '/pleɪ/', 'The children play outside.'],
  ['work', 'ishlamoq', '/wɜːk/', 'I work in an office.'],
  ['help', 'yordam bermoq', '/help/', 'Can you help me?'],
  ['like', 'yoqtirmoq', '/laɪk/', 'I like coffee.'],
  ['want', 'xohlamoq', '/wɒnt/', 'I want some water.'],
  ['need', 'kerak boʻlmoq', '/niːd/', 'I need your help.'],
  ['have', 'ega boʻlmoq', '/hæv/', 'I have a car.'],
  ['see', 'koʻrmoq', '/siː/', 'I can see the moon.'],
  ['hear', 'eshitmoq', '/hɪər/', 'I can hear music.'],
  ['know', 'bilmoq', '/nəʊ/', 'I know the answer.'],
  ['come', 'kelmoq', '/kʌm/', 'Come here, please.'],
  ['get', 'olmoq', '/ɡet/', 'I get up at six.'],
  ['give', 'bermoq', '/ɡɪv/', 'Give me the book.'],
  ['make', 'qilmoq/yasamoq', '/meɪk/', 'I make tea every morning.'],
  ['say', 'aytmoq', '/seɪ/', 'Say it again, please.'],
  ['take', 'olmoq', '/teɪk/', 'Take an umbrella.'],
  ['tell', 'aytib bermoq', '/tel/', 'Tell me the truth.'],
  ['use', 'foydalanmoq', '/juːz/', 'Use a pen, please.'],
  ['find', 'topmoq', '/faɪnd/', 'I cannot find my keys.'],
  ['feel', 'his qilmoq', '/fiːl/', 'I feel happy today.'],
  ['think', 'oʻylamoq', '/θɪŋk/', 'I think you are right.'],
  ['look', 'qaramoq', '/lʊk/', 'Look at the picture.'],
  ['turn', 'burilmoq', '/tɜːn/', 'Turn left here.'],
  ['show', 'koʻrsatmoq', '/ʃəʊ/', 'Show me your photo.'],
  ['open', 'ochmoq', '/ˈəʊpən/', 'Open the window.'],
  ['close', 'yopmoq', '/kləʊz/', 'Close the door.'],
  ['start', 'boshlamoq', '/stɑːt/', 'The film starts at eight.'],
  ['stop', 'toʻxtamoq', '/stɒp/', 'Stop the car here.'],
  ['ask', 'soʻramoq', '/ɑːsk/', 'Ask the teacher.'],
  ['answer (verb)', 'javob bermoq', '/ˈɑːnsər/', 'Please answer me.'],
  ['buy', 'sotib olmoq', '/baɪ/', 'I want to buy bread.'],
  ['sell', 'sotmoq', '/sel/', 'They sell fruit here.'],
  ['cook', 'pishirmoq', '/kʊk/', 'She cooks dinner every day.'],
  ['drive', 'haydamoq', '/draɪv/', 'He drives a bus.'],
  ['speak', 'gapirmoq', '/spiːk/', 'I speak English a little.'],
  ['listen', 'tinglamoq', '/ˈlɪsən/', 'Listen to the teacher.'],
  ['learn', 'oʻrganmoq', '/lɜːn/', 'I want to learn English.'],
  ['live', 'yashamoq', '/lɪv/', 'They live in the city.'],
  ['love', 'sevmoq', '/lʌv/', 'I love my family.'],
  ['call', 'qoʻngʻiroq qilmoq', '/kɔːl/', 'Call me tonight.'],
  // ── Basic adjectives ──
  ['big', 'katta', '/bɪɡ/', 'This is a big house.'],
  ['small', 'kichik', '/smɔːl/', 'I have a small bag.'],
  ['hot', 'issiq', '/hɒt/', 'The tea is hot.'],
  ['cold', 'sovuq', '/kəʊld/', 'The water is cold.'],
  ['good', 'yaxshi', '/ɡʊd/', 'This is a good book.'],
  ['bad', 'yomon', '/bæd/', 'The weather is bad.'],
  ['new', 'yangi', '/njuː/', 'I bought a new phone.'],
  ['old', 'eski/keksa', '/əʊld/', 'This is an old car.'],
  ['happy', 'baxtli', '/ˈhæpi/', 'She is very happy.'],
  ['sad', 'gʻamgin', '/sæd/', 'He looks sad today.'],
  ['fast', 'tez', '/fɑːst/', 'The car is very fast.'],
  ['slow', 'sekin', '/sləʊ/', 'The train is slow.'],
  ['long', 'uzun', '/lɒŋ/', 'She has long hair.'],
  ['short', 'qisqa/past', '/ʃɔːt/', 'It was a short film.'],
  ['high', 'baland', '/haɪ/', 'The mountain is high.'],
  ['low', 'past', '/ləʊ/', 'The price is low.'],
  ['clean', 'toza', '/kliːn/', 'The room is clean.'],
  ['dirty', 'kir', '/ˈdɜːti/', 'My hands are dirty.'],
  ['easy', 'oson', '/ˈiːzi/', 'The test was easy.'],
  ['hard', 'qiyin/qattiq', '/hɑːd/', 'This work is hard.'],
  ['full', 'toʻla', '/fʊl/', 'The bottle is full.'],
  ['empty', 'boʻsh', '/ˈempti/', 'The box is empty.'],
  ['right', 'toʻgʻri/oʻng', '/raɪt/', 'Your answer is right.'],
  ['wrong', 'notoʻgʻri', '/rɒŋ/', 'This answer is wrong.'],
  ['beautiful', 'chiroyli', '/ˈbjuːtɪfəl/', 'She is beautiful.'],
  ['ugly', 'xunuk', '/ˈʌɡli/', 'The building is ugly.'],
  ['rich', 'boy', '/rɪtʃ/', 'He is a rich man.'],
  ['poor', 'kambagʻal', '/pɔː/', 'They were very poor.'],
  ['young', 'yosh', '/jʌŋ/', 'She is young.'],
  ['sick', 'kasal', '/sɪk/', 'I feel sick today.'],
  ['free', 'bepul/boʻsh', '/friː/', 'The water is free.'],
  ['busy', 'band', '/ˈbɪzi/', 'I am busy now.'],
  // ── Pronouns ──
  ['I', 'men', '/aɪ/', 'I am a student.'],
  ['you', 'sen/siz', '/juː/', 'You are my friend.'],
  ['he', 'u (erkak)', '/hiː/', 'He is a teacher.'],
  ['she', 'u (ayol)', '/ʃiː/', 'She is my sister.'],
  ['it', 'u (narsa)', '/ɪt/', 'It is a cat.'],
  ['we', 'biz', '/wiː/', 'We are friends.'],
  ['they', 'ular', '/ðeɪ/', 'They live here.'],
  ['me', 'menga', '/miː/', 'Give it to me.'],
  ['him', 'unga (erkak)', '/hɪm/', 'I saw him yesterday.'],
  ['her', 'unga (ayol)', '/hɜː/', 'I gave her a book.'],
  ['us', 'bizga', '/ʌs/', 'They helped us.'],
  ['them', 'ularga', '/ðem/', 'I called them.'],
  ['my', 'mening', '/maɪ/', 'This is my book.'],
  ['your', 'sening/sizning', '/jɔː/', 'Is this your pen?'],
  ['their', 'ularning', '/ðeər/', 'Their house is big.'],
  // ── Question words ──
  ['what', 'nima', '/wɒt/', 'What is your name?'],
  ['where', 'qayer', '/weər/', 'Where do you live?'],
  ['when', 'qachon', '/wen/', 'When is the lesson?'],
  ['who', 'kim', '/huː/', 'Who is that man?'],
  ['why', 'nega', '/waɪ/', 'Why are you late?'],
  ['how', 'qanday', '/haʊ/', 'How are you?'],
  // ── Greetings & basic phrases ──
  ['hello', 'salom', '/həˈləʊ/', 'Hello, how are you?'],
  ['hi', 'salom (norasmiy)', '/haɪ/', 'Hi, nice to see you.'],
  ['goodbye', 'xayr', '/ɡʊdˈbaɪ/', 'Goodbye, see you soon.'],
  ['please', 'iltimos', '/pliːz/', 'Please help me.'],
  ['thanks', 'rahmat', '/θæŋks/', 'Thanks for your help.'],
  ['sorry', 'kechirasiz', '/ˈsɒri/', 'Sorry, I am late.'],
  ['yes', 'ha', '/jes/', 'Yes, I agree.'],
  ['no', 'yoʻq', '/nəʊ/', 'No, I do not want it.'],
  ['okay', 'mayli', '/ˌəʊˈkeɪ/', 'Okay, let us go.'],
  ['welcome', 'xush kelibsiz', '/ˈwelkəm/', 'Welcome to my home.'],
  ['name', 'ism', '/neɪm/', 'My name is Ali.'],
  ['friend', 'doʻst', '/frend/', 'He is my best friend.'],
  ['day', 'kun', '/deɪ/', 'Have a nice day.'],
  ['today', 'bugun', '/təˈdeɪ/', 'Today is Monday.'],
  ['tomorrow', 'ertaga', '/təˈmɒrəʊ/', 'I will see you tomorrow.'],
  ['yesterday', 'kecha', '/ˈjestədeɪ/', 'I was busy yesterday.'],
  ['morning', 'ertalab', '/ˈmɔːnɪŋ/', 'Good morning!'],
  ['night', 'tun', '/naɪt/', 'Good night!'],
  ['time', 'vaqt', '/taɪm/', 'What time is it?'],
  ['week', 'hafta', '/wiːk/', 'See you next week.'],
  ['month', 'oy', '/mʌnθ/', 'This month is May.'],
  ['year', 'yil', '/jɪər/', 'Happy New Year!'],
  ['here', 'bu yerda', '/hɪər/', 'Come here, please.'],
  ['there', 'u yerda', '/ðeər/', 'Put it there.'],
  ['now', 'hozir', '/naʊ/', 'I am busy now.'],
]
