// A2 — 800 ta so'z (week 2,3,4)
// [word, translation, phonetic, example_sentence]
export const A2_RAW: [string, string, string, string][] = [
  // ── Daily routines ──
  ['wake up', 'uygʻonmoq', '/weɪk ʌp/', 'I wake up at six every day.'],
  ['get up', 'oʻrindan turmoq', '/ɡet ʌp/', 'She gets up early.'],
  ['brush', 'tozalamoq', '/brʌʃ/', 'I brush my teeth twice a day.'],
  ['wash', 'yuvmoq', '/wɒʃ/', 'Wash your face in the morning.'],
  ['shower', 'dush', '/ˈʃaʊər/', 'I take a shower every morning.'],
  ['dress', 'kiyinmoq', '/dres/', 'He dresses quickly.'],
  ['shave', 'soqol olmoq', '/ʃeɪv/', 'He shaves every morning.'],
  ['comb', 'taramoq', '/kəʊm/', 'She combs her hair.'],
  ['prepare', 'tayyorlamoq', '/prɪˈpeər/', 'I prepare breakfast.'],
  ['leave', 'joʻnamoq', '/liːv/', 'I leave home at eight.'],
  ['arrive', 'yetib bormoq', '/əˈraɪv/', 'I arrive at work at nine.'],
  ['return', 'qaytmoq', '/rɪˈtɜːn/', 'I return home at six.'],
  ['rest', 'dam olmoq', '/rest/', 'I rest after lunch.'],
  ['relax', 'hordiq chiqarmoq', '/rɪˈlæks/', 'I relax on weekends.'],
  ['routine', 'kundalik tartib', '/ruːˈtiːn/', 'My morning routine is simple.'],
  ['usually', 'odatda', '/ˈjuːʒuəli/', 'I usually wake up early.'],
  ['always', 'doimo', '/ˈɔːlweɪz/', 'She always drinks tea.'],
  ['sometimes', 'baʼzan', '/ˈsʌmtaɪmz/', 'I sometimes walk to work.'],
  ['often', 'tez-tez', '/ˈɒfən/', 'We often eat out.'],
  ['never', 'hech qachon', '/ˈnevər/', 'I never skip breakfast.'],
  ['early', 'erta', '/ˈɜːli/', 'I go to bed early.'],
  ['late', 'kech', '/leɪt/', 'He woke up late.'],
  ['breakfast time', 'nonushta vaqti', '/ˈbrekfəst taɪm/', 'Breakfast time is at seven.'],
  ['bedtime', 'uyqu vaqti', '/ˈbedtaɪm/', 'Bedtime is at ten.'],
  ['nap', 'mizgʻimoq', '/næp/', 'I take a short nap.'],
  ['exercise', 'mashq qilmoq', '/ˈeksəsaɪz/', 'I exercise every morning.'],
  ['chore', 'uy yumushi', '/tʃɔː/', 'I do my chores after school.'],
  ['tidy', 'tartibga solmoq', '/ˈtaɪdi/', 'Tidy your room, please.'],
  ['vacuum', 'changyutgich bilan tozalamoq', '/ˈvækjuːm/', 'She vacuums the carpet.'],
  ['iron', 'dazmollamoq', '/ˈaɪən/', 'I iron my shirts.'],
  ['laundry', 'kir', '/ˈlɔːndri/', 'I do the laundry on Sunday.'],
  ['feed', 'boqmoq', '/fiːd/', 'I feed the cat every morning.'],
  ['water (verb)', 'sugʻormoq', '/ˈwɔːtər/', 'I water the plants daily.'],
  ['lock', 'qulflamoq', '/lɒk/', 'Lock the door before leaving.'],
  ['unlock', 'qulfni ochmoq', '/ʌnˈlɒk/', 'Unlock the door, please.'],
  ['hurry', 'shoshilmoq', '/ˈhʌri/', 'Hurry, we are late!'],
  ['wait', 'kutmoq', '/weɪt/', 'Please wait a minute.'],
  ['finish', 'tugatmoq', '/ˈfɪnɪʃ/', 'I finish work at five.'],
  ['begin', 'boshlamoq', '/bɪˈɡɪn/', 'Classes begin in September.'],
  ['continue', 'davom etmoq', '/kənˈtɪnjuː/', 'Continue your work.'],
  ['daily', 'kundalik', '/ˈdeɪli/', 'This is my daily habit.'],
  ['weekend', 'dam olish kuni', '/ˈwiːkend/', 'I relax on the weekend.'],
  ['weekday', 'ish kuni', '/ˈwiːkdeɪ/', 'I work on weekdays.'],
  ['schedule', 'jadval', '/ˈʃedjuːl/', 'My schedule is full.'],
  ['habit', 'odat', '/ˈhæbɪt/', 'Reading is a good habit.'],
  ['alarm', 'budilnik', '/əˈlɑːm/', 'My alarm rings at six.'],
  ['snooze', 'budilnikni keyinga surmoq', '/snuːz/', 'I always snooze the alarm.'],
  // ── Work & jobs ──
  ['job', 'ish', '/dʒɒb/', 'She has a good job.'],
  ['office', 'idora', '/ˈɒfɪs/', 'I work in an office.'],
  ['boss', 'rahbar', '/bɒs/', 'My boss is kind.'],
  ['manager', 'menejer', '/ˈmænɪdʒər/', 'The manager is busy.'],
  ['employee', 'xodim', '/ɪmˈplɔɪiː/', 'She is a good employee.'],
  ['colleague', 'hamkasb', '/ˈkɒliːɡ/', 'My colleague is helpful.'],
  ['salary', 'maosh', '/ˈsæləri/', 'He earns a good salary.'],
  ['meeting', 'yigʻilish', '/ˈmiːtɪŋ/', 'We have a meeting at ten.'],
  ['company', 'kompaniya', '/ˈkʌmpəni/', 'She works for a big company.'],
  ['business', 'biznes', '/ˈbɪznəs/', 'He started a business.'],
  ['career', 'kasb', '/kəˈrɪər/', 'She has a great career.'],
  ['interview', 'suhbat', '/ˈɪntəvjuː/', 'I have a job interview today.'],
  ['contract', 'shartnoma', '/ˈkɒntrækt/', 'Sign the contract here.'],
  ['project', 'loyiha', '/ˈprɒdʒekt/', 'The project is finished.'],
  ['task', 'vazifa', '/tɑːsk/', 'This task is difficult.'],
  ['report', 'hisobot', '/rɪˈpɔːt/', 'Write the report by Friday.'],
  ['deadline', 'muddat', '/ˈdedlaɪn/', 'The deadline is tomorrow.'],
  ['overtime', 'qoʻshimcha ish vaqti', '/ˈəʊvətaɪm/', 'I worked overtime yesterday.'],
  ['break', 'tanaffus', '/breɪk/', 'Let us take a break.'],
  ['retire', 'nafaqaga chiqmoq', '/rɪˈtaɪər/', 'He will retire next year.'],
  ['doctor', 'shifokor', '/ˈdɒktər/', 'The doctor helped me.'],
  ['nurse', 'hamshira', '/nɜːs/', 'The nurse is very kind.'],
  ['engineer', 'muhandis', '/ˌendʒɪˈnɪər/', 'He is a software engineer.'],
  ['lawyer', 'yurist', '/ˈlɔːjər/', 'She is a famous lawyer.'],
  ['driver', 'haydovchi', '/ˈdraɪvər/', 'The bus driver was polite.'],
  ['farmer', 'fermer', '/ˈfɑːmər/', 'The farmer grows wheat.'],
  ['cook (job)', 'oshpaz', '/kʊk/', 'The cook made a great meal.'],
  ['waiter', 'ofitsiant', '/ˈweɪtər/', 'The waiter brought the menu.'],
  ['seller', 'sotuvchi', '/ˈselər/', 'The seller was friendly.'],
  ['artist', 'rassom', '/ˈɑːtɪst/', 'She is a talented artist.'],
  ['writer', 'yozuvchi', '/ˈraɪtər/', 'He is a famous writer.'],
  ['scientist', 'olim', '/ˈsaɪəntɪst/', 'The scientist made a discovery.'],
  ['police officer', 'politsiyachi', '/pəˈliːs ˈɒfɪsər/', 'The police officer helped us.'],
  ['firefighter', 'oʻt oʻchiruvchi', '/ˈfaɪəfaɪtər/', 'The firefighter is brave.'],
  ['pilot', 'uchuvchi', '/ˈpaɪlət/', 'The pilot landed safely.'],
  ['soldier', 'askar', '/ˈsəʊldʒər/', 'The soldier is strong.'],
  ['mechanic', 'mexanik', '/məˈkænɪk/', 'The mechanic fixed my car.'],
  ['electrician', 'elektrik', '/ɪˌlekˈtrɪʃən/', 'The electrician fixed the light.'],
  ['plumber', 'santexnik', '/ˈplʌmər/', 'The plumber repaired the pipe.'],
  ['accountant', 'buxgalter', '/əˈkaʊntənt/', 'The accountant checked the numbers.'],
  ['journalist', 'jurnalist', '/ˈdʒɜːnəlɪst/', 'The journalist wrote a story.'],
  ['translator', 'tarjimon', '/trænzˈleɪtər/', 'She works as a translator.'],
  ['dentist', 'tish shifokori', '/ˈdentɪst/', 'I visit the dentist twice a year.'],
  ['chef', 'bosh oshpaz', '/ʃef/', 'The chef cooked a fine meal.'],
  ['actor', 'aktyor', '/ˈæktər/', 'He is a famous actor.'],
  ['singer', 'qoʻshiqchi', '/ˈsɪŋər/', 'The singer has a beautiful voice.'],
  ['employer', 'ish beruvchi', '/ɪmˈplɔɪər/', 'My employer is fair.'],
  // ── Shopping ──
  ['shop', 'doʻkon', '/ʃɒp/', 'The shop is closed.'],
  ['store', 'magazin', '/stɔː/', 'I bought it at the store.'],
  ['market', 'bozor', '/ˈmɑːkɪt/', 'We buy fruit at the market.'],
  ['mall', 'savdo markazi', '/mɔːl/', 'We met at the mall.'],
  ['price', 'narx', '/praɪs/', 'What is the price?'],
  ['cost', 'qiymat', '/kɒst/', 'How much does it cost?'],
  ['cheap', 'arzon', '/tʃiːp/', 'This shirt is cheap.'],
  ['expensive', 'qimmat', '/ɪkˈspensɪv/', 'The car is expensive.'],
  ['money', 'pul', '/ˈmʌni/', 'I have no money.'],
  ['cash', 'naqd pul', '/kæʃ/', 'I paid in cash.'],
  ['card', 'karta', '/kɑːd/', 'Can I pay by card?'],
  ['change', 'qaytim', '/tʃeɪndʒ/', 'Here is your change.'],
  ['receipt', 'chek', '/rɪˈsiːt/', 'Keep your receipt.'],
  ['customer', 'mijoz', '/ˈkʌstəmər/', 'The customer is happy.'],
  ['discount', 'chegirma', '/ˈdɪskaʊnt/', 'They offer a big discount.'],
  ['sale', 'aksiya', '/seɪl/', 'The shoes are on sale.'],
  ['buy (a2)', 'sotib olmoq', '/baɪ/', 'I want to buy a gift.'],
  ['pay', 'toʻlamoq', '/peɪ/', 'I will pay now.'],
  ['spend', 'sarflamoq', '/spend/', 'I spend too much money.'],
  ['save (money)', 'pul yigʻmoq', '/seɪv/', 'I save money every month.'],
  ['afford', 'puli yetmoq', '/əˈfɔːd/', 'I cannot afford a new phone.'],
  ['cheaper', 'arzonroq', '/ˈtʃiːpər/', 'This one is cheaper.'],
  ['bill', 'hisob', '/bɪl/', 'Can I have the bill?'],
  ['coin', 'tanga', '/kɔɪn/', 'I found a gold coin.'],
  ['wallet', 'hamyon', '/ˈwɒlɪt/', 'I lost my wallet.'],
  ['basket', 'savat', '/ˈbɑːskɪt/', 'Put the apples in the basket.'],
  ['trolley', 'arava', '/ˈtrɒli/', 'She pushed the trolley.'],
  ['queue', 'navbat', '/kjuː/', 'There is a long queue.'],
  ['size', 'oʻlcham', '/saɪz/', 'What size do you need?'],
  ['fit', 'mos kelmoq', '/fɪt/', 'These shoes fit well.'],
  ['try on', 'kiyib koʻrmoq', '/traɪ ɒn/', 'Can I try on this jacket?'],
  ['refund', 'pulni qaytarish', '/ˈriːfʌnd/', 'I asked for a refund.'],
  ['exchange', 'almashtirish', '/ɪksˈtʃeɪndʒ/', 'Can I exchange this shirt?'],
  ['shopkeeper', 'doʻkondor', '/ˈʃɒpkiːpər/', 'The shopkeeper was friendly.'],
  ['shopping list', 'xarid roʻyxati', '/ˈʃɒpɪŋ lɪst/', 'I made a shopping list.'],
  ['brand', 'brend', '/brænd/', 'This brand is popular.'],
  ['product', 'mahsulot', '/ˈprɒdʌkt/', 'This product is new.'],
  ['quality', 'sifat', '/ˈkwɒləti/', 'The quality is very good.'],
  ['offer', 'taklif', '/ˈɒfər/', 'There is a special offer.'],
  ['bargain', 'arzon narsa', '/ˈbɑːɡɪn/', 'This jacket is a real bargain.'],
  ['order', 'buyurtma', '/ˈɔːdər/', 'I placed an order online.'],
  ['deliver', 'yetkazib bermoq', '/dɪˈlɪvər/', 'They deliver food fast.'],
  ['package', 'paket', '/ˈpækɪdʒ/', 'The package arrived today.'],
  ['supermarket', 'supermarket', '/ˈsuːpəmɑːkɪt/', 'I shop at the supermarket.'],
  ['grocery', 'oziq-ovqat', '/ˈɡrəʊsəri/', 'I bought groceries today.'],
  ['cashier', 'kassir', '/kæˈʃɪər/', 'The cashier counted the money.'],
  ['expensive item', 'qimmat narsa', '/ɪkˈspensɪv ˈaɪtəm/', 'It is the most expensive item.'],
  // ── Restaurant ──
  ['restaurant', 'restoran', '/ˈrestrɒnt/', 'We ate at a nice restaurant.'],
  ['menu', 'menyu', '/ˈmenjuː/', 'Can I see the menu?'],
  ['table (booking)', 'stol (band qilish)', '/ˈteɪbəl/', 'I booked a table for two.'],
  ['reserve', 'band qilmoq', '/rɪˈzɜːv/', 'I want to reserve a table.'],
  ['waiter (restaurant)', 'ofitsiant', '/ˈweɪtər/', 'The waiter took our order.'],
  ['order (food)', 'buyurtma bermoq', '/ˈɔːdər/', 'I would like to order now.'],
  ['dish', 'taom', '/dɪʃ/', 'This dish is delicious.'],
  ['meal', 'ovqat', '/miːl/', 'It was a wonderful meal.'],
  ['starter', 'birinchi taom', '/ˈstɑːtər/', 'I ordered a soup as a starter.'],
  ['main course', 'asosiy taom', '/meɪn kɔːs/', 'The main course was chicken.'],
  ['dessert', 'shirinlik', '/dɪˈzɜːt/', 'We had cake for dessert.'],
  ['delicious', 'mazali', '/dɪˈlɪʃəs/', 'The food is delicious.'],
  ['tasty', 'shirin', '/ˈteɪsti/', 'This soup is tasty.'],
  ['fresh', 'yangi/taza', '/freʃ/', 'The bread is fresh.'],
  ['spicy', 'achchiq', '/ˈspaɪsi/', 'The food is too spicy.'],
  ['sweet', 'shirin', '/swiːt/', 'This tea is too sweet.'],
  ['sour', 'nordon', '/ˈsaʊər/', 'The lemon is sour.'],
  ['bitter', 'achchiq (taʼm)', '/ˈbɪtər/', 'The coffee is bitter.'],
  ['salty', 'sho-r', '/ˈsɔːlti/', 'The soup is too salty.'],
  ['plate (food)', 'tarelka', '/pleɪt/', 'Bring me a clean plate.'],
  ['glass', 'stakan', '/ɡlɑːs/', 'Can I have a glass of water?'],
  ['napkin', 'salfetka', '/ˈnæpkɪn/', 'Use a napkin, please.'],
  ['tip', 'choychaqa', '/tɪp/', 'We left a good tip.'],
  ['bill (restaurant)', 'hisob', '/bɪl/', 'Can we have the bill?'],
  ['cafe', 'kafe', '/ˈkæfeɪ/', 'We met at a small cafe.'],
  ['snack', 'yengil taom', '/snæk/', 'I had a quick snack.'],
  ['drink (noun)', 'ichimlik', '/drɪŋk/', 'What drink would you like?'],
  ['waitress', 'ofitsiant ayol', '/ˈweɪtrəs/', 'The waitress was helpful.'],
  ['kitchen (restaurant)', 'oshxona', '/ˈkɪtʃɪn/', 'The kitchen is very clean.'],
  ['serve', 'xizmat qilmoq', '/sɜːv/', 'They serve breakfast until ten.'],
  ['recommend', 'tavsiya qilmoq', '/ˌrekəˈmend/', 'What do you recommend?'],
  ['vegetarian', 'vegetarian', '/ˌvedʒəˈteəriən/', 'She is a vegetarian.'],
  ['portion', 'porsiya', '/ˈpɔːʃən/', 'The portion is very big.'],
  ['hungry', 'och', '/ˈhʌŋɡri/', 'I am very hungry.'],
  ['thirsty', 'chanqagan', '/ˈθɜːsti/', 'I am thirsty.'],
  ['full (after eating)', 'toʻq', '/fʊl/', 'I am full, thank you.'],
  ['taste', 'taʼm', '/teɪst/', 'I like the taste of this.'],
  ['cook (verb a2)', 'pishirmoq', '/kʊk/', 'They cook fresh food daily.'],
  ['bake', 'pishirmoq (pechda)', '/beɪk/', 'She bakes bread every day.'],
  ['fry', 'qovurmoq', '/fraɪ/', 'Fry the eggs, please.'],
  ['boil', 'qaynatmoq', '/bɔɪl/', 'Boil the water first.'],
  ['grill', 'panjarada pishirmoq', '/ɡrɪl/', 'They grill the meat outside.'],
  ['recipe', 'retsept', '/ˈresəpi/', 'This recipe is easy.'],
  ['ingredient', 'masalliq', '/ɪnˈɡriːdiənt/', 'We need three ingredients.'],
  ['flavour', 'taʼm', '/ˈfleɪvər/', 'I love this flavour.'],
  ['plate up', 'taomni tortmoq', '/pleɪt ʌp/', 'The chef plated up the food.'],
  ['takeaway', 'olib ketadigan ovqat', '/ˈteɪkəweɪ/', 'We ordered a takeaway.'],
  // ── Transport ──
  ['car', 'mashina', '/kɑː/', 'He drives a fast car.'],
  ['bus', 'avtobus', '/bʌs/', 'I take the bus to work.'],
  ['train', 'poyezd', '/treɪn/', 'The train is late.'],
  ['plane', 'samolyot', '/pleɪn/', 'The plane is ready.'],
  ['bike', 'velosiped', '/baɪk/', 'I ride my bike to school.'],
  ['motorbike', 'mototsikl', '/ˈməʊtəbaɪk/', 'He bought a new motorbike.'],
  ['taxi', 'taksi', '/ˈtæksi/', 'Let us take a taxi.'],
  ['boat', 'qayiq', '/bəʊt/', 'We crossed the river by boat.'],
  ['ship', 'kema', '/ʃɪp/', 'The ship sailed away.'],
  ['truck', 'yuk mashinasi', '/trʌk/', 'The truck is very big.'],
  ['subway', 'metro', '/ˈsʌbweɪ/', 'The subway is fast.'],
  ['station', 'bekat', '/ˈsteɪʃən/', 'Meet me at the station.'],
  ['airport', 'aeroport', '/ˈeəpɔːt/', 'We arrived at the airport early.'],
  ['ticket', 'chipta', '/ˈtɪkɪt/', 'I bought two tickets.'],
  ['platform', 'platforma', '/ˈplætfɔːm/', 'The train leaves from platform two.'],
  ['stop (bus)', 'bekat', '/stɒp/', 'Get off at the next stop.'],
  ['journey', 'sayohat', '/ˈdʒɜːni/', 'The journey was long.'],
  ['trip', 'sayohat', '/trɪp/', 'We had a great trip.'],
  ['drive (a2)', 'haydamoq', '/draɪv/', 'She drives to work.'],
  ['ride', 'minib yurmoq', '/raɪd/', 'I ride my bike daily.'],
  ['fly', 'uchmoq', '/flaɪ/', 'We fly to London tomorrow.'],
  ['catch (a bus)', 'ulgurmoq', '/kætʃ/', 'I need to catch the bus.'],
  ['miss (a train)', 'qoldirmoq', '/mɪs/', 'I missed the last train.'],
  ['traffic', 'tirbandlik', '/ˈtræfɪk/', 'The traffic is heavy today.'],
  ['road', 'yoʻl', '/rəʊd/', 'The road is closed.'],
  ['street', 'koʻcha', '/striːt/', 'I live on this street.'],
  ['bridge', 'koʻprik', '/brɪdʒ/', 'The bridge is very old.'],
  ['corner', 'burchak', '/ˈkɔːnər/', 'Turn at the corner.'],
  ['map', 'xarita', '/mæp/', 'I need a city map.'],
  ['direction', 'yoʻnalish', '/dɪˈrekʃən/', 'Ask for directions.'],
  ['speed', 'tezlik', '/spiːd/', 'Reduce your speed here.'],
  ['parking', 'avtoturargoh', '/ˈpɑːkɪŋ/', 'There is no parking here.'],
  ['fuel', 'yoqilgʻi', '/ˈfjuːəl/', 'We need more fuel.'],
  ['engine', 'dvigatel', '/ˈendʒɪn/', 'The engine is broken.'],
  ['wheel', 'gʻildirak', '/wiːl/', 'The wheel is flat.'],
  ['seat', 'oʻrindiq', '/siːt/', 'Take a seat, please.'],
  ['passenger', 'yoʻlovchi', '/ˈpæsɪndʒər/', 'The passenger was tired.'],
  ['delay', 'kechikish', '/dɪˈleɪ/', 'There was a long delay.'],
  ['arrive on time', 'oʻz vaqtida yetib kelmoq', '/əˈraɪv ɒn taɪm/', 'The bus arrived on time.'],
  ['helmet', 'dubulgʻa', '/ˈhelmɪt/', 'Wear a helmet on the bike.'],
  ['license', 'guvohnoma', '/ˈlaɪsəns/', 'He has a driving license.'],
  ['accident', 'baxtsiz hodisa', '/ˈæksɪdənt/', 'There was an accident here.'],
  ['cross', 'kesib oʻtmoq', '/krɒs/', 'Cross the road carefully.'],
  ['pavement', 'piyodalar yoʻli', '/ˈpeɪvmənt/', 'Walk on the pavement.'],
  ['transport', 'transport', '/ˈtrænspɔːt/', 'Public transport is cheap.'],
  ['fare', 'yoʻl haqi', '/feər/', 'The bus fare went up.'],
  ['departure', 'joʻnab ketish', '/dɪˈpɑːtʃər/', 'Departure is at noon.'],
  // ── Travel ──
  ['travel', 'sayohat qilmoq', '/ˈtrævəl/', 'I love to travel.'],
  ['holiday', 'taʼtil', '/ˈhɒlədeɪ/', 'We are on holiday now.'],
  ['vacation', 'taʼtil', '/vəˈkeɪʃən/', 'They went on vacation.'],
  ['tourist', 'sayyoh', '/ˈtʊərɪst/', 'Many tourists visit this city.'],
  ['hotel', 'mehmonxona', '/həʊˈtel/', 'We stayed at a nice hotel.'],
  ['room (hotel)', 'xona', '/ruːm/', 'I booked a single room.'],
  ['book (verb)', 'bron qilmoq', '/bʊk/', 'I booked the flight online.'],
  ['flight', 'parvoz', '/flaɪt/', 'Our flight is delayed.'],
  ['passport', 'pasport', '/ˈpɑːspɔːt/', 'Do not forget your passport.'],
  ['visa', 'viza', '/ˈviːzə/', 'I need a visa to travel there.'],
  ['luggage', 'yuk', '/ˈlʌɡɪdʒ/', 'My luggage is heavy.'],
  ['suitcase', 'chamadon', '/ˈsuːtkeɪs/', 'Pack your suitcase tonight.'],
  ['backpack', 'ryukzak', '/ˈbækpæk/', 'I carried a small backpack.'],
  ['guide', 'gid', '/ɡaɪd/', 'The guide showed us the city.'],
  ['abroad', 'chet elda', '/əˈbrɔːd/', 'She studied abroad.'],
  ['destination', 'manzil', '/ˌdestɪˈneɪʃən/', 'Our destination is Rome.'],
  ['arrival', 'kelish', '/əˈraɪvəl/', 'Arrival time is six.'],
  ['adventure', 'sarguzasht', '/ədˈventʃər/', 'It was a great adventure.'],
  ['beach', 'plyaj', '/biːtʃ/', 'We relaxed on the beach.'],
  ['mountain', 'togʻ', '/ˈmaʊntɪn/', 'We climbed the mountain.'],
  ['sea', 'dengiz', '/siː/', 'The sea is calm today.'],
  ['lake', 'koʻl', '/leɪk/', 'We swam in the lake.'],
  ['river', 'daryo', '/ˈrɪvər/', 'The river is very wide.'],
  ['forest', 'oʻrmon', '/ˈfɒrɪst/', 'We walked in the forest.'],
  ['island', 'orol', '/ˈaɪlənd/', 'They live on a small island.'],
  ['desert', 'choʻl', '/ˈdezət/', 'The desert is very hot.'],
  ['view', 'manzara', '/vjuː/', 'The view is amazing.'],
  ['camera', 'fotoapparat', '/ˈkæmərə/', 'Bring your camera.'],
  ['photo', 'rasm', '/ˈfəʊtəʊ/', 'Take a photo here.'],
  ['souvenir', 'esdalik sovgʻa', '/ˌsuːvəˈnɪər/', 'I bought a souvenir.'],
  ['explore', 'kashf qilmoq', '/ɪkˈsplɔː/', 'Let us explore the old town.'],
  ['sightseeing', 'diqqatga sazovor joylarni koʻrish', '/ˈsaɪtsiːɪŋ/', 'We went sightseeing all day.'],
  ['tour', 'ekskursiya', '/tʊər/', 'We took a city tour.'],
  ['journey abroad', 'chet el sayohati', '/ˈdʒɜːni əˈbrɔːd/', 'The journey abroad was exciting.'],
  ['check in', 'roʻyxatdan oʻtmoq', '/tʃek ɪn/', 'We checked in at the hotel.'],
  ['check out', 'mehmonxonadan chiqmoq', '/tʃek aʊt/', 'We check out at noon.'],
  ['reception', 'qabulxona', '/rɪˈsepʃən/', 'Ask at the reception.'],
  ['currency', 'valyuta', '/ˈkʌrənsi/', 'I need to change currency.'],
  ['foreign', 'chet el', '/ˈfɒrən/', 'She speaks a foreign language.'],
  ['culture', 'madaniyat', '/ˈkʌltʃər/', 'I love their culture.'],
  ['local', 'mahalliy', '/ˈləʊkəl/', 'We tried local food.'],
  ['guidebook', 'qoʻllanma', '/ˈɡaɪdbʊk/', 'The guidebook was useful.'],
  ['itinerary', 'sayohat rejasi', '/aɪˈtɪnərəri/', 'Here is our itinerary.'],
  ['departure gate', 'chiqish darvozasi', '/dɪˈpɑːtʃər ɡeɪt/', 'Go to the departure gate.'],
  ['delayed flight', 'kechikkan parvoz', '/dɪˈleɪd flaɪt/', 'We had a delayed flight.'],
  ['relaxing', 'dam beruvchi', '/rɪˈlæksɪŋ/', 'It was a relaxing holiday.'],
  ['exciting', 'qiziqarli', '/ɪkˈsaɪtɪŋ/', 'The trip was exciting.'],
  // ── Weather ──
  ['weather', 'ob-havo', '/ˈweðər/', 'The weather is nice today.'],
  ['sun', 'quyosh', '/sʌn/', 'The sun is shining.'],
  ['sunny', 'quyoshli', '/ˈsʌni/', 'It is a sunny day.'],
  ['rain', 'yomgʻir', '/reɪn/', 'It is going to rain.'],
  ['rainy', 'yomgʻirli', '/ˈreɪni/', 'It was a rainy morning.'],
  ['snow', 'qor', '/snəʊ/', 'The snow is white.'],
  ['snowy', 'qorli', '/ˈsnəʊi/', 'It is a snowy day.'],
  ['wind', 'shamol', '/wɪnd/', 'The wind is strong.'],
  ['windy', 'shamolli', '/ˈwɪndi/', 'It is windy outside.'],
  ['cloud', 'bulut', '/klaʊd/', 'There is one cloud in the sky.'],
  ['cloudy', 'bulutli', '/ˈklaʊdi/', 'The sky is cloudy.'],
  ['storm', 'boʻron', '/stɔːm/', 'A storm is coming.'],
  ['fog', 'tuman', '/fɒɡ/', 'The fog is thick.'],
  ['foggy', 'tumanli', '/ˈfɒɡi/', 'It is foggy this morning.'],
  ['ice', 'muz', '/aɪs/', 'The road is covered with ice.'],
  ['warm', 'iliq', '/wɔːm/', 'It is warm today.'],
  ['cool', 'salqin', '/kuːl/', 'The evening is cool.'],
  ['freezing', 'juda sovuq', '/ˈfriːzɪŋ/', 'It is freezing outside.'],
  ['temperature', 'harorat', '/ˈtemprətʃər/', 'The temperature is high.'],
  ['degree', 'gradus', '/dɪˈɡriː/', 'It is thirty degrees today.'],
  ['forecast', 'bashorat', '/ˈfɔːkɑːst/', 'The forecast says rain.'],
  ['climate', 'iqlim', '/ˈklaɪmət/', 'The climate is dry here.'],
  ['season', 'fasl', '/ˈsiːzən/', 'Spring is my favourite season.'],
  ['spring', 'bahor', '/sprɪŋ/', 'Flowers bloom in spring.'],
  ['summer', 'yoz', '/ˈsʌmər/', 'Summer is very hot here.'],
  ['autumn', 'kuz', '/ˈɔːtəm/', 'Leaves fall in autumn.'],
  ['winter', 'qish', '/ˈwɪntər/', 'Winter is cold and long.'],
  ['thunder', 'momaqaldiroq', '/ˈθʌndər/', 'I heard loud thunder.'],
  ['lightning', 'chaqmoq', '/ˈlaɪtnɪŋ/', 'Lightning lit up the sky.'],
  ['shower (rain)', 'yomgʻir', '/ˈʃaʊər/', 'There was a short shower.'],
  ['drop', 'tomchi', '/drɒp/', 'A drop of rain fell.'],
  ['umbrella', 'soyabon', '/ʌmˈbrelə/', 'Take an umbrella with you.'],
  ['wet', 'hoʻl', '/wet/', 'The grass is wet.'],
  ['dry', 'quruq', '/draɪ/', 'The weather is dry.'],
  ['heat', 'jaziramа', '/hiːt/', 'The heat is unbearable.'],
  ['flood', 'toshqin', '/flʌd/', 'The flood damaged the road.'],
  ['rainbow', 'kamalak', '/ˈreɪnbəʊ/', 'We saw a beautiful rainbow.'],
  ['breeze', 'shabada', '/briːz/', 'A cool breeze blew gently.'],
  ['humid', 'nam', '/ˈhjuːmɪd/', 'The air is very humid.'],
  ['mild', 'mayin', '/maɪld/', 'The winter was mild this year.'],
  ['weather report', 'ob-havo maʼlumoti', '/ˈweðər rɪˈpɔːt/', 'I watched the weather report.'],
  ['sunshine', 'quyosh nuri', '/ˈsʌnʃaɪn/', 'I love the morning sunshine.'],
  ['snowfall', 'qor yogʻishi', '/ˈsnəʊfɔːl/', 'There was heavy snowfall.'],
  ['heatwave', 'jazirama davri', '/ˈhiːtweɪv/', 'A heatwave hit the city.'],
  ['frost', 'qirov', '/frɒst/', 'There was frost on the window.'],
  ['weather change', 'ob-havo oʻzgarishi', '/ˈweðər tʃeɪndʒ/', 'A sudden weather change came.'],
  // ── Time expressions ──
  ['minute', 'daqiqa', '/ˈmɪnɪt/', 'Wait one minute, please.'],
  ['hour', 'soat', '/ˈaʊər/', 'I waited for an hour.'],
  ['second', 'soniya', '/ˈsekənd/', 'Wait a second.'],
  ['midnight', 'yarim tun', '/ˈmɪdnaɪt/', 'We left at midnight.'],
  ['noon', 'tush payti', '/nuːn/', 'We met at noon.'],
  ['afternoon', 'tushdan keyin', '/ˌɑːftəˈnuːn/', 'See you in the afternoon.'],
  ['evening', 'kechqurun', '/ˈiːvnɪŋ/', 'Good evening, everyone.'],
  ['tonight', 'bugun kechqurun', '/təˈnaɪt/', 'I am free tonight.'],
  ['soon', 'tez orada', '/suːn/', 'See you soon.'],
  ['later', 'keyinroq', '/ˈleɪtər/', 'I will call you later.'],
  ['before', 'oldin', '/bɪˈfɔː/', 'Call me before noon.'],
  ['after', 'keyin', '/ˈɑːftər/', 'We met after the lesson.'],
  ['during', 'davomida', '/ˈdjʊərɪŋ/', 'Be quiet during the film.'],
  ['until', 'gacha', '/ənˈtɪl/', 'Wait until five oclock.'],
  ['since', 'beri', '/sɪns/', 'I have lived here since 2010.'],
  ['ago', 'oldin', '/əˈɡəʊ/', 'I saw him two days ago.'],
  ['already', 'allaqachon', '/ɔːlˈredi/', 'I have already eaten.'],
  ['yet', 'hali', '/jet/', 'I have not finished yet.'],
  ['still', 'hamon', '/stɪl/', 'He is still sleeping.'],
  ['recently', 'yaqinda', '/ˈriːsəntli/', 'I saw her recently.'],
  ['nowadays', 'hozirgi kunda', '/ˈnaʊədeɪz/', 'Nowadays everyone uses phones.'],
  ['quickly', 'tez', '/ˈkwɪkli/', 'She finished quickly.'],
  ['slowly', 'sekin', '/ˈsləʊli/', 'Please speak slowly.'],
  ['immediately', 'darhol', '/ɪˈmiːdiətli/', 'Come here immediately.'],
  ['suddenly', 'toʻsatdan', '/ˈsʌdənli/', 'Suddenly it started to rain.'],
  ['finally', 'nihoyat', '/ˈfaɪnəli/', 'Finally, we arrived home.'],
  ['monday', 'dushanba', '/ˈmʌndeɪ/', 'I work on Monday.'],
  ['tuesday', 'seshanba', '/ˈtjuːzdeɪ/', 'The meeting is on Tuesday.'],
  ['wednesday', 'chorshanba', '/ˈwenzdeɪ/', 'We meet on Wednesday.'],
  ['thursday', 'payshanba', '/ˈθɜːzdeɪ/', 'See you on Thursday.'],
  ['friday', 'juma', '/ˈfraɪdeɪ/', 'Friday is my favourite day.'],
  ['saturday', 'shanba', '/ˈsætədeɪ/', 'We rest on Saturday.'],
  ['sunday', 'yakshanba', '/ˈsʌndeɪ/', 'Sunday is a quiet day.'],
  ['century', 'asr', '/ˈsentʃəri/', 'This building is a century old.'],
  ['decade', 'oʻn yillik', '/ˈdekeɪd/', 'A decade is ten years.'],
  ['period', 'davr', '/ˈpɪəriəd/', 'It was a difficult period.'],
  ['moment', 'lahza', '/ˈməʊmənt/', 'Wait a moment, please.'],
  ['future', 'kelajak', '/ˈfjuːtʃər/', 'I think about the future.'],
  ['past', 'oʻtmish', '/pɑːst/', 'Do not live in the past.'],
  ['present (time)', 'hozirgi vaqt', '/ˈprezənt/', 'Focus on the present.'],
  ['midday', 'tush payti', '/ˈmɪddeɪ/', 'We meet at midday.'],
  ['dawn', 'tong', '/dɔːn/', 'We left at dawn.'],
  ['dusk', 'qorongʻi tushishi', '/dʌsk/', 'Birds return at dusk.'],
  ['fortnight', 'ikki hafta', '/ˈfɔːtnaɪt/', 'I will be away for a fortnight.'],
  ['anniversary', 'yubiley', '/ˌænɪˈvɜːsəri/', 'It is our anniversary today.'],
  ['rarely', 'kamdan-kam', '/ˈreəli/', 'He rarely watches TV.'],
  // ── Sports ──
  ['sport', 'sport', '/spɔːt/', 'Football is a popular sport.'],
  ['football', 'futbol', '/ˈfʊtbɔːl/', 'They play football on Sunday.'],
  ['basketball', 'basketbol', '/ˈbɑːskɪtbɔːl/', 'She loves basketball.'],
  ['volleyball', 'voleybol', '/ˈvɒlibɔːl/', 'We played volleyball on the beach.'],
  ['tennis', 'tennis', '/ˈtenɪs/', 'He plays tennis well.'],
  ['swimming', 'suzish', '/ˈswɪmɪŋ/', 'Swimming is good exercise.'],
  ['running', 'yugurish', '/ˈrʌnɪŋ/', 'Running keeps me healthy.'],
  ['cycling', 'velosipedda yurish', '/ˈsaɪklɪŋ/', 'Cycling is fun and healthy.'],
  ['boxing', 'boks', '/ˈbɒksɪŋ/', 'Boxing is a tough sport.'],
  ['wrestling', 'kurash', '/ˈreslɪŋ/', 'He won the wrestling match.'],
  ['team', 'jamoa', '/tiːm/', 'Our team won the game.'],
  ['player', 'oʻyinchi', '/ˈpleɪər/', 'He is the best player.'],
  ['coach', 'murabbiy', '/kəʊtʃ/', 'The coach trained the team.'],
  ['match', 'oʻyin', '/mætʃ/', 'The match starts at eight.'],
  ['game', 'oʻyin', '/ɡeɪm/', 'The game was exciting.'],
  ['goal', 'gol', '/ɡəʊl/', 'He scored a great goal.'],
  ['score', 'hisob', '/skɔː/', 'What is the score now?'],
  ['win', 'gʻalaba qozonmoq', '/wɪn/', 'I hope we win the game.'],
  ['lose', 'yutqazmoq', '/luːz/', 'We did not want to lose.'],
  ['draw (sport)', 'durang', '/drɔː/', 'The match ended in a draw.'],
  ['compete', 'musobaqalashmoq', '/kəmˈpiːt/', 'They compete every year.'],
  ['champion', 'chempion', '/ˈtʃæmpiən/', 'She is the world champion.'],
  ['medal', 'medal', '/ˈmedl/', 'He won a gold medal.'],
  ['stadium', 'stadion', '/ˈsteɪdiəm/', 'The stadium was full.'],
  ['gym', 'sport zali', '/dʒɪm/', 'I go to the gym daily.'],
  ['training', 'mashgʻulot', '/ˈtreɪnɪŋ/', 'Training starts at six.'],
  ['fitness', 'jismoniy tayyorgarlik', '/ˈfɪtnəs/', 'Fitness is important.'],
  ['referee', 'hakam', '/ˌrefəˈriː/', 'The referee blew the whistle.'],
  ['ball', 'toʻp', '/bɔːl/', 'Throw the ball to me.'],
  ['race', 'poyga', '/reɪs/', 'He won the race.'],
  ['jump', 'sakramoq', '/dʒʌmp/', 'He can jump very high.'],
  ['throw', 'uloqtirmoq', '/θrəʊ/', 'Throw the ball here.'],
  ['catch', 'ushlamoq', '/kætʃ/', 'Catch the ball!'],
  ['kick', 'tepmoq', '/kɪk/', 'He kicked the ball hard.'],
  ['hit', 'urmoq', '/hɪt/', 'She hit the ball well.'],
  ['climb', 'koʻtarilmoq', '/klaɪm/', 'They climb mountains for fun.'],
  ['skating', 'konkida uchish', '/ˈskeɪtɪŋ/', 'Ice skating is fun.'],
  ['skiing', 'chang\'ida uchish', '/ˈskiːɪŋ/', 'We went skiing in winter.'],
  ['golf', 'golf', '/ɡɒlf/', 'He plays golf on weekends.'],
  ['hockey', 'xokkey', '/ˈhɒki/', 'Hockey is popular in Canada.'],
  ['marathon', 'marafon', '/ˈmærəθən/', 'She ran a marathon.'],
  ['tournament', 'turnir', '/ˈtʊənəmənt/', 'The tournament lasts a week.'],
  ['fan', 'muxlis', '/fæn/', 'He is a football fan.'],
  ['whistle', 'hushtak', '/ˈwɪsəl/', 'The referee blew the whistle.'],
  ['athlete', 'sportchi', '/ˈæθliːt/', 'She is a famous athlete.'],
  ['victory', 'gʻalaba', '/ˈvɪktəri/', 'It was a great victory.'],
  ['defeat', 'magʻlubiyat', '/dɪˈfiːt/', 'The defeat was painful.'],
  // ── Health & body ──
  ['health', 'sogʻliq', '/helθ/', 'Health is more important than money.'],
  ['healthy', 'sogʻlom', '/ˈhelθi/', 'Eat healthy food.'],
  ['ill', 'kasal', '/ɪl/', 'She is ill today.'],
  ['illness', 'kasallik', '/ˈɪlnəs/', 'It is a serious illness.'],
  ['disease', 'kasallik', '/dɪˈziːz/', 'The disease spread fast.'],
  ['pain', 'ogʻriq', '/peɪn/', 'I feel pain in my back.'],
  ['hurt', 'ogʻrimoq', '/hɜːt/', 'My leg hurts.'],
  ['fever', 'isitma', '/ˈfiːvər/', 'He has a high fever.'],
  ['cold (illness)', 'shamollash', '/kəʊld/', 'I have a bad cold.'],
  ['cough', 'yoʻtal', '/kɒf/', 'She has a dry cough.'],
  ['headache', 'bosh ogʻrigʻi', '/ˈhedeɪk/', 'I have a headache.'],
  ['stomachache', 'qorin ogʻrigʻi', '/ˈstʌməkeɪk/', 'He has a stomachache.'],
  ['toothache', 'tish ogʻrigʻi', '/ˈtuːθeɪk/', 'I have a toothache.'],
  ['medicine', 'dori', '/ˈmedsɪn/', 'Take this medicine twice a day.'],
  ['pill', 'tabletka', '/pɪl/', 'Take one pill after dinner.'],
  ['hospital', 'kasalxona', '/ˈhɒspɪtl/', 'He is in the hospital.'],
  ['clinic', 'poliklinika', '/ˈklɪnɪk/', 'The clinic opens at eight.'],
  ['patient', 'bemor', '/ˈpeɪʃənt/', 'The patient feels better.'],
  ['injury', 'jarohat', '/ˈɪndʒəri/', 'It was a serious injury.'],
  ['wound', 'yara', '/wuːnd/', 'The wound is healing.'],
  ['blood', 'qon', '/blʌd/', 'He lost a lot of blood.'],
  ['bone', 'suyak', '/bəʊn/', 'He broke a bone in his arm.'],
  ['skin', 'teri', '/skɪn/', 'Protect your skin from the sun.'],
  ['muscle', 'mushak', '/ˈmʌsəl/', 'Exercise builds strong muscles.'],
  ['breathe', 'nafas olmoq', '/briːð/', 'Breathe deeply and relax.'],
  ['recover', 'tuzalmoq', '/rɪˈkʌvər/', 'She is recovering well.'],
  ['cure', 'davolamoq', '/kjʊə/', 'There is no cure yet.'],
  ['treatment', 'davolash', '/ˈtriːtmənt/', 'The treatment was successful.'],
  ['prescription', 'retsept', '/prɪˈskrɪpʃən/', 'The doctor wrote a prescription.'],
  ['ambulance', 'tez yordam', '/ˈæmbjʊləns/', 'Call an ambulance now.'],
  ['emergency', 'favqulodda holat', '/ɪˈmɜːdʒənsi/', 'This is an emergency.'],
  ['operation', 'operatsiya', '/ˌɒpəˈreɪʃən/', 'The operation went well.'],
  ['allergy', 'allergiya', '/ˈælədʒi/', 'I have a food allergy.'],
  ['vitamin', 'vitamin', '/ˈvɪtəmɪn/', 'Oranges have vitamin C.'],
  ['diet', 'parhez', '/ˈdaɪət/', 'She is on a strict diet.'],
  ['weight', 'vazn', '/weɪt/', 'I want to lose weight.'],
  ['exercise (health)', 'jismoniy mashq', '/ˈeksəsaɪz/', 'Daily exercise is healthy.'],
  ['rest (health)', 'dam olish', '/rest/', 'You need plenty of rest.'],
  ['checkup', 'tibbiy koʻrik', '/ˈtʃekʌp/', 'I had a medical checkup.'],
  ['dentist (a2)', 'tish shifokori', '/ˈdentɪst/', 'Visit the dentist regularly.'],
  ['bandage', 'bint', '/ˈbændɪdʒ/', 'Put a bandage on the wound.'],
  ['painful', 'ogʻriqli', '/ˈpeɪnfəl/', 'The injection was painful.'],
  ['sneeze', 'aksirmoq', '/sniːz/', 'I sneeze when I have a cold.'],
  ['dizzy', 'boshi aylanmoq', '/ˈdɪzi/', 'I feel dizzy today.'],
  ['tired', 'charchagan', '/ˈtaɪəd/', 'I am very tired tonight.'],
  ['energy', 'energiya', '/ˈenədʒi/', 'I have no energy today.'],
  ['strong', 'kuchli', '/strɒŋ/', 'He is very strong.'],
  ['weak', 'zaif', '/wiːk/', 'I feel weak after the flu.'],
  // ── Education ──
  ['education', 'taʼlim', '/ˌedjʊˈkeɪʃən/', 'Education is very important.'],
  ['university', 'universitet', '/ˌjuːnɪˈvɜːsəti/', 'She studies at university.'],
  ['college', 'kollej', '/ˈkɒlɪdʒ/', 'He goes to college.'],
  ['subject', 'fan', '/ˈsʌbdʒɪkt/', 'Math is my favourite subject.'],
  ['math', 'matematika', '/mæθ/', 'I am good at math.'],
  ['science', 'fan', '/ˈsaɪəns/', 'Science is interesting.'],
  ['history', 'tarix', '/ˈhɪstəri/', 'I love history lessons.'],
  ['geography', 'geografiya', '/dʒiˈɒɡrəfi/', 'Geography is fun to learn.'],
  ['biology', 'biologiya', '/baɪˈɒlədʒi/', 'Biology is about living things.'],
  ['chemistry', 'kimyo', '/ˈkemɪstri/', 'Chemistry class is at ten.'],
  ['physics', 'fizika', '/ˈfɪzɪks/', 'Physics is difficult for me.'],
  ['language', 'til', '/ˈlæŋɡwɪdʒ/', 'English is a useful language.'],
  ['grammar', 'grammatika', '/ˈɡræmər/', 'English grammar is hard.'],
  ['vocabulary', 'lugʻat', '/vəˈkæbjʊləri/', 'Build your vocabulary daily.'],
  ['dictionary', 'lugʻat kitobi', '/ˈdɪkʃənəri/', 'Use a dictionary to check words.'],
  ['library', 'kutubxona', '/ˈlaɪbrəri/', 'I study in the library.'],
  ['classroom', 'sinfxona', '/ˈklɑːsruːm/', 'The classroom is bright.'],
  ['professor', 'professor', '/prəˈfesər/', 'The professor is famous.'],
  ['degree (education)', 'ilmiy daraja', '/dɪˈɡriː/', 'She has a university degree.'],
  ['diploma', 'diplom', '/dɪˈpləʊmə/', 'He earned his diploma.'],
  ['certificate', 'sertifikat', '/səˈtɪfɪkət/', 'I got a language certificate.'],
  ['knowledge', 'bilim', '/ˈnɒlɪdʒ/', 'Knowledge is power.'],
  ['study', 'oʻrganmoq', '/ˈstʌdi/', 'I study every evening.'],
  ['teach', 'oʻrgatmoq', '/tiːtʃ/', 'She teaches English.'],
  ['explain', 'tushuntirmoq', '/ɪkˈspleɪn/', 'Please explain this rule.'],
  ['understand', 'tushunmoq', '/ˌʌndəˈstænd/', 'I do not understand this.'],
  ['remember', 'eslamoq', '/rɪˈmembər/', 'I cannot remember his name.'],
  ['forget', 'unutmoq', '/fəˈɡet/', 'Do not forget your homework.'],
  ['mistake', 'xato', '/mɪˈsteɪk/', 'Everyone makes mistakes.'],
  ['correct', 'toʻgʻrilamoq', '/kəˈrekt/', 'Correct your mistakes.'],
  ['grade', 'baho', '/ɡreɪd/', 'She got a good grade.'],
  ['mark', 'baho/belgi', '/mɑːk/', 'He got a high mark.'],
  ['pass (exam)', 'oʻtmoq', '/pɑːs/', 'I hope to pass the exam.'],
  ['fail', 'yiqilmoq', '/feɪl/', 'He failed the test.'],
  ['result', 'natija', '/rɪˈzʌlt/', 'The results were good.'],
  ['practice', 'mashq', '/ˈpræktɪs/', 'Practice makes perfect.'],
  ['revise', 'takrorlamoq', '/rɪˈvaɪz/', 'I revise before exams.'],
  ['attend', 'qatnashmoq', '/əˈtend/', 'She attends every lesson.'],
  ['graduate', 'bitirmoq', '/ˈɡrædʒueɪt/', 'I will graduate next year.'],
  ['scholarship', 'stipendiya', '/ˈskɒləʃɪp/', 'She won a scholarship.'],
  ['textbook', 'darslik', '/ˈtekstbʊk/', 'Open your textbook to page ten.'],
  ['note', 'qaydlar', '/nəʊt/', 'Take notes during the lesson.'],
  ['essay', 'insho', '/ˈeseɪ/', 'Write a short essay.'],
  ['research', 'tadqiqot', '/rɪˈsɜːtʃ/', 'She is doing research.'],
  ['course', 'kurs', '/kɔːs/', 'I joined an English course.'],
  ['term', 'oʻquv chorak', '/tɜːm/', 'The new term starts soon.'],
  ['pupil', 'oʻquvchi', '/ˈpjuːpəl/', 'Every pupil has a book.'],
  ['skill', 'koʻnikma', '/skɪl/', 'Reading is an important skill.'],
  // ── Technology ──
  ['computer', 'kompyuter', '/kəmˈpjuːtər/', 'My computer is slow.'],
  ['laptop', 'noutbuk', '/ˈlæptɒp/', 'She bought a new laptop.'],
  ['phone', 'telefon', '/fəʊn/', 'My phone is ringing.'],
  ['smartphone', 'smartfon', '/ˈsmɑːtfəʊn/', 'Everyone has a smartphone now.'],
  ['internet', 'internet', '/ˈɪntənet/', 'The internet is very slow.'],
  ['website', 'veb-sayt', '/ˈwebsaɪt/', 'Visit our website.'],
  ['email', 'elektron pochta', '/ˈiːmeɪl/', 'Send me an email.'],
  ['message', 'xabar', '/ˈmesɪdʒ/', 'I got your message.'],
  ['screen', 'ekran', '/skriːn/', 'The screen is too bright.'],
  ['keyboard', 'klaviatura', '/ˈkiːbɔːd/', 'The keyboard is broken.'],
  ['mouse (device)', 'sichqoncha', '/maʊs/', 'The mouse is not working.'],
  ['file', 'fayl', '/faɪl/', 'Save the file, please.'],
  ['folder', 'papka', '/ˈfəʊldər/', 'Put it in this folder.'],
  ['password', 'parol', '/ˈpɑːswɜːd/', 'Do not share your password.'],
  ['download', 'yuklab olmoq', '/ˈdaʊnləʊd/', 'Download the app now.'],
  ['upload', 'yuklamoq', '/ˈʌpləʊd/', 'Upload your photo here.'],
  ['click', 'bosmoq', '/klɪk/', 'Click the blue button.'],
  ['delete', 'oʻchirmoq', '/dɪˈliːt/', 'Delete that old file.'],
  ['save (file)', 'saqlamoq', '/seɪv/', 'Save your work often.'],
  ['print', 'chop etmoq', '/prɪnt/', 'Print two copies, please.'],
  ['software', 'dasturiy taʼminot', '/ˈsɒftweə/', 'Install the new software.'],
  ['app', 'ilova', '/æp/', 'This app is very useful.'],
  ['network', 'tarmoq', '/ˈnetwɜːk/', 'The network is down.'],
  ['device', 'qurilma', '/dɪˈvaɪs/', 'This device is small.'],
  ['battery', 'batareya', '/ˈbætəri/', 'My battery is low.'],
  ['charge', 'quvvatlamoq', '/tʃɑːdʒ/', 'Charge your phone tonight.'],
  ['connect', 'ulanmoq', '/kəˈnekt/', 'Connect to the Wi-Fi.'],
  ['update', 'yangilamoq', '/ʌpˈdeɪt/', 'Update the app today.'],
  ['account', 'hisob qaydnomasi', '/əˈkaʊnt/', 'Create a new account.'],
  ['social media', 'ijtimoiy tarmoqlar', '/ˈsəʊʃəl ˈmiːdiə/', 'She uses social media a lot.'],
  ['online', 'onlayn', '/ˌɒnˈlaɪn/', 'I work online from home.'],
  ['offline', 'oflayn', '/ˌɒfˈlaɪn/', 'The site is offline now.'],
  ['robot', 'robot', '/ˈrəʊbɒt/', 'The robot cleans the floor.'],
  ['camera (device)', 'kamera', '/ˈkæmərə/', 'The camera takes clear photos.'],
  ['headphones', 'quloqchin', '/ˈhedfəʊnz/', 'I listen with headphones.'],
  ['speaker', 'karnay', '/ˈspiːkər/', 'The speaker is very loud.'],
  ['charger', 'zaryadlovchi', '/ˈtʃɑːdʒər/', 'I forgot my charger.'],
  ['signal', 'signal', '/ˈsɪɡnəl/', 'There is no signal here.'],
  ['data', 'maʼlumot', '/ˈdeɪtə/', 'I am out of mobile data.'],
  ['search', 'qidirmoq', '/sɜːtʃ/', 'Search for it online.'],
  ['browser', 'brauzer', '/ˈbraʊzər/', 'Open a new browser tab.'],
  ['link', 'havola', '/lɪŋk/', 'Click on this link.'],
  ['code', 'kod', '/kəʊd/', 'He writes computer code.'],
  ['virus', 'virus', '/ˈvaɪrəs/', 'A virus damaged my computer.'],
  ['repair', 'taʼmirlamoq', '/rɪˈpeər/', 'He can repair the laptop.'],
  ['technology', 'texnologiya', '/tekˈnɒlədʒi/', 'Technology changes fast.'],
  ['digital', 'raqamli', '/ˈdɪdʒɪtəl/', 'We live in a digital world.'],
  // ── Feelings & emotions ──
  ['feeling', 'his', '/ˈfiːlɪŋ/', 'I have a strange feeling.'],
  ['emotion', 'hissiyot', '/ɪˈməʊʃən/', 'He hides his emotions.'],
  ['glad', 'mamnun', '/ɡlæd/', 'I am glad to see you.'],
  ['joy', 'quvonch', '/dʒɔɪ/', 'The news brought us joy.'],
  ['excited', 'hayajonlangan', '/ɪkˈsaɪtɪd/', 'I am excited about the trip.'],
  ['nervous', 'asabiy', '/ˈnɜːvəs/', 'I feel nervous before exams.'],
  ['worried', 'xavotirli', '/ˈwʌrɪd/', 'She is worried about her son.'],
  ['afraid', 'qoʻrqqan', '/əˈfreɪd/', 'I am afraid of dogs.'],
  ['scared', 'qoʻrqib ketgan', '/skeəd/', 'The child was scared.'],
  ['angry', 'jahli chiqqan', '/ˈæŋɡri/', 'He was angry with me.'],
  ['upset', 'xafa', '/ʌpˈset/', 'She was upset by the news.'],
  ['lonely', 'yolgʻiz', '/ˈləʊnli/', 'He feels lonely at night.'],
  ['bored', 'zerikkan', '/bɔːd/', 'I am bored at home.'],
  ['surprised', 'hayron', '/səˈpraɪzd/', 'I was surprised by the gift.'],
  ['confused', 'chalkash', '/kənˈfjuːzd/', 'I am confused about the rules.'],
  ['proud', 'faxrlanmoq', '/praʊd/', 'I am proud of you.'],
  ['shy', 'uyatchan', '/ʃaɪ/', 'She is very shy.'],
  ['calm', 'tinch', '/kɑːm/', 'Stay calm and relax.'],
  ['relaxed', 'xotirjam', '/rɪˈlækst/', 'I feel relaxed now.'],
  ['comfortable', 'qulay', '/ˈkʌmftəbəl/', 'This chair is comfortable.'],
  ['uncomfortable', 'noqulay', '/ʌnˈkʌmftəbəl/', 'I feel uncomfortable here.'],
  ['jealous', 'rashk qiluvchi', '/ˈdʒeləs/', 'He is jealous of his brother.'],
  ['grateful', 'minnatdor', '/ˈɡreɪtfəl/', 'I am grateful for your help.'],
  ['disappointed', 'umidsiz', '/ˌdɪsəˈpɔɪntɪd/', 'She was disappointed in me.'],
  ['embarrassed', 'xijolat tortgan', '/ɪmˈbærəst/', 'I felt embarrassed.'],
  ['hopeful', 'umidvor', '/ˈhəʊpfəl/', 'I am hopeful about the future.'],
  ['stressed', 'asabiy zoʻriqishda', '/strest/', 'I am stressed at work.'],
  ['cheerful', 'quvnoq', '/ˈtʃɪəfəl/', 'She is always cheerful.'],
  ['frightened', 'qoʻrqqan', '/ˈfraɪtənd/', 'The noise frightened the cat.'],
  ['amazed', 'lol qolgan', '/əˈmeɪzd/', 'I was amazed by the show.'],
  ['curious', 'qiziquvchan', '/ˈkjʊəriəs/', 'Children are very curious.'],
  ['serious', 'jiddiy', '/ˈsɪəriəs/', 'He has a serious face.'],
  ['mood', 'kayfiyat', '/muːd/', 'She is in a good mood.'],
  ['smile', 'tabassum', '/smaɪl/', 'She has a lovely smile.'],
  ['laugh', 'kulmoq', '/lɑːf/', 'We laughed a lot.'],
  ['cry', 'yigʻlamoq', '/kraɪ/', 'The baby began to cry.'],
  ['enjoy', 'zavqlanmoq', '/ɪnˈdʒɔɪ/', 'I enjoy this music.'],
  ['hope', 'umid qilmoq', '/həʊp/', 'I hope to see you soon.'],
  ['hate', 'yomon koʻrmoq', '/heɪt/', 'I hate cold weather.'],
  ['miss (someone)', 'sogʻinmoq', '/mɪs/', 'I miss my family.'],
  ['care', 'gʻamxoʻrlik qilmoq', '/keər/', 'I care about you.'],
  ['trust', 'ishonmoq', '/trʌst/', 'I trust my best friend.'],
  ['worry', 'xavotir olmoq', '/ˈwʌri/', 'Do not worry about it.'],
  ['fear', 'qoʻrquv', '/fɪər/', 'He has a fear of heights.'],
  ['pleasure', 'zavq', '/ˈpleʒər/', 'It is a pleasure to meet you.'],
  ['pride', 'gʻurur', '/praɪd/', 'She felt great pride.'],
  ['anger', 'gʻazab', '/ˈæŋɡər/', 'He controlled his anger.'],
  ['sadness', 'gʻam', '/ˈsædnəs/', 'There was sadness in her eyes.'],
  // ── House & furniture ──
  ['home', 'uy/maskan', '/həʊm/', 'There is no place like home.'],
  ['flat', 'kvartira', '/flæt/', 'They rented a small flat.'],
  ['apartment', 'kvartira', '/əˈpɑːtmənt/', 'She lives in a city apartment.'],
  ['garden', 'bogʻ', '/ˈɡɑːdən/', 'We have a small garden.'],
  ['yard', 'hovli', '/jɑːd/', 'The children play in the yard.'],
  ['garage', 'garaj', '/ˈɡærɑːʒ/', 'The car is in the garage.'],
  ['stairs', 'zinapoya', '/steəz/', 'Go up the stairs.'],
  ['hall', 'dahliz', '/hɔːl/', 'Leave your shoes in the hall.'],
  ['ceiling', 'shift', '/ˈsiːlɪŋ/', 'The ceiling is very high.'],
  ['carpet', 'gilam', '/ˈkɑːpɪt/', 'The carpet is soft.'],
  ['curtain', 'parda', '/ˈkɜːtən/', 'Close the curtains, please.'],
  ['cupboard', 'shkaf', '/ˈkʌbəd/', 'The cups are in the cupboard.'],
  ['shelf', 'javon', '/ʃelf/', 'Put the book on the shelf.'],
  ['drawer', 'tortma', '/drɔː/', 'The keys are in the drawer.'],
  ['wardrobe', 'kiyim shkafi', '/ˈwɔːdrəʊb/', 'My clothes are in the wardrobe.'],
  ['fridge', 'muzlatgich', '/frɪdʒ/', 'Put the milk in the fridge.'],
  ['oven', 'duxovka', '/ˈʌvən/', 'The bread is in the oven.'],
  ['stove', 'plita', '/stəʊv/', 'The soup is on the stove.'],
  ['sink', 'rakovina', '/sɪŋk/', 'Wash the dishes in the sink.'],
  ['toilet', 'hojatxona', '/ˈtɔɪlət/', 'Where is the toilet?'],
  ['shower (room)', 'dush', '/ˈʃaʊər/', 'The shower is not working.'],
  ['bath', 'vanna', '/bɑːθ/', 'I take a bath in the evening.'],
  ['blanket', 'koʻrpa', '/ˈblæŋkɪt/', 'It is cold; take a blanket.'],
  ['pillow', 'yostiq', '/ˈpɪləʊ/', 'This pillow is very soft.'],
  ['sheet', 'choyshab', '/ʃiːt/', 'Change the bed sheets.'],
  ['towel', 'sochiq', '/ˈtaʊəl/', 'Bring me a clean towel.'],
  ['furniture', 'mebel', '/ˈfɜːnɪtʃər/', 'The furniture is new.'],
  ['armchair', 'kreslo', '/ˈɑːmtʃeər/', 'He sat in the armchair.'],
  ['bookshelf', 'kitob javoni', '/ˈbʊkʃelf/', 'The bookshelf is full.'],
  ['television', 'televizor', '/ˈtelɪvɪʒən/', 'Turn off the television.'],
  ['fan (device)', 'ventilyator', '/fæn/', 'Switch on the fan, please.'],
  ['heater', 'isitgich', '/ˈhiːtər/', 'The heater keeps us warm.'],
  ['switch', 'vyklyuchatel', '/swɪtʃ/', 'Turn off the light switch.'],
  ['socket', 'rozetka', '/ˈsɒkɪt/', 'Plug it into the socket.'],
  ['rent', 'ijara', '/rent/', 'The rent is too high.'],
  ['neighbour', 'qoʻshni', '/ˈneɪbər/', 'My neighbour is friendly.'],
  ['address', 'manzil', '/əˈdres/', 'What is your home address?'],
  ['move (house)', 'koʻchmoq', '/muːv/', 'We will move next month.'],
  ['build', 'qurmoq', '/bɪld/', 'They build new houses here.'],
  ['decorate', 'bezamoq', '/ˈdekəreɪt/', 'We decorate the room for parties.'],
  ['clean (house)', 'tozalamoq', '/kliːn/', 'I clean the house on Sunday.'],
  ['fix', 'tuzatmoq', '/fɪks/', 'Can you fix the door?'],
  ['comfortable home', 'qulay uy', '/ˈkʌmftəbəl həʊm/', 'They have a comfortable home.'],
  ['spacious', 'keng', '/ˈspeɪʃəs/', 'The living room is spacious.'],
  ['cosy', 'shinam', '/ˈkəʊzi/', 'The room feels cosy and warm.'],
  ['living room', 'mehmonxona', '/ˈlɪvɪŋ ruːm/', 'We watch TV in the living room.'],
  ['dining room', 'ovqatxona', '/ˈdaɪnɪŋ ruːm/', 'We eat in the dining room.'],
  // ── Clothes ──
  ['clothes', 'kiyim', '/kləʊðz/', 'I need new clothes.'],
  ['shirt', 'koʻylak', '/ʃɜːt/', 'He wears a white shirt.'],
  ['trousers', 'shim', '/ˈtraʊzəz/', 'These trousers are too long.'],
  ['jeans', 'jinsi shim', '/dʒiːnz/', 'She wears blue jeans.'],
  ['dress', 'koʻylak (ayollar)', '/dres/', 'She bought a red dress.'],
  ['skirt', 'yubka', '/skɜːt/', 'The skirt is too short.'],
  ['jacket', 'kurtka', '/ˈdʒækɪt/', 'Take a jacket; it is cold.'],
  ['coat', 'palto', '/kəʊt/', 'Wear a warm coat.'],
  ['sweater', 'sviter', '/ˈswetər/', 'This sweater is warm.'],
  ['T-shirt', 'futbolka', '/ˈtiːʃɜːt/', 'He wears a black T-shirt.'],
  ['suit', 'kostyum', '/suːt/', 'He wore a dark suit.'],
  ['tie', 'galstuk', '/taɪ/', 'He wears a blue tie.'],
  ['hat', 'shlyapa', '/hæt/', 'Wear a hat in the sun.'],
  ['cap', 'kepka', '/kæp/', 'He wears a baseball cap.'],
  ['scarf', 'sharf', '/skɑːf/', 'Wear a scarf in winter.'],
  ['gloves', 'qoʻlqop', '/ɡlʌvz/', 'My gloves keep my hands warm.'],
  ['socks', 'paypoq', '/sɒks/', 'I need clean socks.'],
  ['shoes', 'tufli', '/ʃuːz/', 'These shoes are new.'],
  ['boots', 'etik', '/buːts/', 'She wears winter boots.'],
  ['sandals', 'sandal', '/ˈsændəlz/', 'I wear sandals in summer.'],
  ['belt', 'kamar', '/belt/', 'He wears a leather belt.'],
  ['pocket', 'cho-ntak', '/ˈpɒkɪt/', 'My keys are in my pocket.'],
  ['button', 'tugma', '/ˈbʌtən/', 'A button is missing.'],
  ['zip', 'zamok', '/zɪp/', 'The zip is broken.'],
  ['wear', 'kiymoq', '/weər/', 'What will you wear today?'],
  ['put on', 'kiymoq', '/pʊt ɒn/', 'Put on your coat.'],
  ['take off', 'yechmoq', '/teɪk ɒf/', 'Take off your shoes here.'],
  ['fit (clothes)', 'mos kelmoq', '/fɪt/', 'This jacket fits me well.'],
  ['tight', 'tor', '/taɪt/', 'These shoes are too tight.'],
  ['loose', 'keng/boʻsh', '/luːs/', 'This shirt is too loose.'],
  ['fashion', 'moda', '/ˈfæʃən/', 'She follows the latest fashion.'],
  ['style', 'uslub', '/staɪl/', 'I like your style.'],
  ['cotton', 'paxta', '/ˈkɒtən/', 'This shirt is made of cotton.'],
  ['wool', 'jun', '/wʊl/', 'The sweater is made of wool.'],
  ['leather', 'charm', '/ˈleðər/', 'He has a leather bag.'],
  ['uniform', 'forma', '/ˈjuːnɪfɔːm/', 'Students wear a uniform.'],
  ['jewellery', 'zargarlik buyumlari', '/ˈdʒuːəlri/', 'She wears gold jewellery.'],
  ['ring (jewel)', 'uzuk', '/rɪŋ/', 'She wears a wedding ring.'],
  ['watch (clothes)', 'qoʻl soati', '/wɒtʃ/', 'He bought a new watch.'],
  ['glasses', 'koʻzoynak', '/ˈɡlɑːsɪz/', 'I wear glasses to read.'],
  ['bag (clothes)', 'sumka', '/bæɡ/', 'She carries a small bag.'],
  ['umbrella (clothes)', 'soyabon', '/ʌmˈbrelə/', 'Take an umbrella; it may rain.'],
  ['wash (clothes)', 'yuvmoq', '/wɒʃ/', 'I wash my clothes on Sunday.'],
  ['change (clothes)', 'almashtirmoq', '/tʃeɪndʒ/', 'Change your wet clothes.'],
  ['outfit', 'kiyim toʻplami', '/ˈaʊtfɪt/', 'I like your outfit today.'],
  ['casual', 'kundalik', '/ˈkæʒuəl/', 'He wears casual clothes.'],
  ['formal', 'rasmiy', '/ˈfɔːməl/', 'Wear formal clothes to the meeting.'],
  ['comfortable clothes', 'qulay kiyim', '/ˈkʌmftəbəl kləʊðz/', 'I prefer comfortable clothes.'],
  // ── City & places ──
  ['city', 'shahar', '/ˈsɪti/', 'I live in a big city.'],
  ['town', 'shaharcha', '/taʊn/', 'It is a small quiet town.'],
  ['village', 'qishloq', '/ˈvɪlɪdʒ/', 'My grandparents live in a village.'],
  ['capital', 'poytaxt', '/ˈkæpɪtəl/', 'Tashkent is the capital.'],
  ['centre', 'markaz', '/ˈsentər/', 'The shop is in the city centre.'],
  ['square', 'maydon', '/skweə/', 'We met in the main square.'],
  ['park', 'park', '/pɑːk/', 'We walk in the park.'],
  ['museum', 'muzey', '/mjuːˈziːəm/', 'The museum is closed today.'],
  ['theatre', 'teatr', '/ˈθɪətər/', 'We went to the theatre.'],
  ['cinema', 'kinoteatr', '/ˈsɪnəmə/', 'There is a new cinema here.'],
  ['bank', 'bank', '/bæŋk/', 'The bank opens at nine.'],
  ['post office', 'pochta', '/pəʊst ˈɒfɪs/', 'I went to the post office.'],
  ['hospital (city)', 'kasalxona', '/ˈhɒspɪtl/', 'The hospital is near here.'],
  ['church', 'cherkov', '/tʃɜːtʃ/', 'The old church is beautiful.'],
  ['mosque', 'masjid', '/mɒsk/', 'The mosque is very old.'],
  ['market (place)', 'bozor', '/ˈmɑːkɪt/', 'The market is busy today.'],
  ['bridge (city)', 'koʻprik', '/brɪdʒ/', 'The bridge connects two parts.'],
  ['building', 'bino', '/ˈbɪldɪŋ/', 'That building is very tall.'],
  ['tower', 'minora', '/ˈtaʊər/', 'The tower is famous.'],
  ['factory', 'zavod', '/ˈfæktəri/', 'He works in a factory.'],
  ['station (city)', 'stansiya', '/ˈsteɪʃən/', 'The station is crowded.'],
  ['airport (city)', 'aeroport', '/ˈeəpɔːt/', 'The airport is far from here.'],
  ['hotel (city)', 'mehmonxona', '/həʊˈtel/', 'There is a hotel near the park.'],
  ['restaurant (city)', 'restoran', '/ˈrestrɒnt/', 'A new restaurant opened.'],
  ['cafe (city)', 'kafe', '/ˈkæfeɪ/', 'Let us meet at the cafe.'],
  ['shop (city)', 'doʻkon', '/ʃɒp/', 'The shop is on the corner.'],
  ['school (city)', 'maktab', '/skuːl/', 'The school is near my house.'],
  ['library (city)', 'kutubxona', '/ˈlaɪbrəri/', 'The library is very quiet.'],
  ['street (city)', 'koʻcha', '/striːt/', 'This street is very long.'],
  ['avenue', 'shoh koʻcha', '/ˈævənjuː/', 'They live on a wide avenue.'],
  ['crossroads', 'chorraha', '/ˈkrɒsrəʊdz/', 'Turn left at the crossroads.'],
  ['traffic light', 'svetofor', '/ˈtræfɪk laɪt/', 'Stop at the traffic light.'],
  ['bus stop', 'avtobus bekati', '/bʌs stɒp/', 'Wait at the bus stop.'],
  ['playground', 'oʻyin maydoni', '/ˈpleɪɡraʊnd/', 'Children play in the playground.'],
  ['zoo', 'hayvonot bogʻi', '/zuː/', 'We took the kids to the zoo.'],
  ['gallery', 'galereya', '/ˈɡæləri/', 'The art gallery is amazing.'],
  ['stadium (city)', 'stadion', '/ˈsteɪdiəm/', 'The stadium is near the river.'],
  ['gym (city)', 'sport zali', '/dʒɪm/', 'There is a gym in the centre.'],
  ['pharmacy', 'dorixona', '/ˈfɑːməsi/', 'The pharmacy is open late.'],
  ['supermarket (city)', 'supermarket', '/ˈsuːpəmɑːkɪt/', 'The supermarket is huge.'],
  ['petrol station', 'yoqilgʻi shoxobchasi', '/ˈpetrəl ˈsteɪʃən/', 'Stop at the petrol station.'],
  ['fountain', 'favvora', '/ˈfaʊntɪn/', 'There is a fountain in the square.'],
  ['monument', 'haykal', '/ˈmɒnjʊmənt/', 'The monument is in the park.'],
  ['public', 'jamoat', '/ˈpʌblɪk/', 'It is a public garden.'],
  ['crowded', 'gavjum', '/ˈkraʊdɪd/', 'The market was very crowded.'],
  ['quiet (place)', 'tinch', '/ˈkwaɪət/', 'This is a quiet street.'],
  ['noisy', 'shovqinli', '/ˈnɔɪzi/', 'The city is very noisy.'],
  ['modern', 'zamonaviy', '/ˈmɒdən/', 'It is a modern building.'],
  // ── Hobbies ──
  ['hobby', 'sevimli mashgʻulot', '/ˈhɒbi/', 'Reading is my hobby.'],
  ['reading', 'kitob oʻqish', '/ˈriːdɪŋ/', 'Reading is relaxing.'],
  ['writing', 'yozish', '/ˈraɪtɪŋ/', 'Writing is my passion.'],
  ['drawing', 'rasm chizish', '/ˈdrɔːɪŋ/', 'She is good at drawing.'],
  ['painting', 'rang berish', '/ˈpeɪntɪŋ/', 'Painting calms my mind.'],
  ['music', 'musiqa', '/ˈmjuːzɪk/', 'I love listening to music.'],
  ['dancing', 'raqs', '/ˈdɑːnsɪŋ/', 'Dancing is great exercise.'],
  ['singing', 'qoʻshiq aytish', '/ˈsɪŋɪŋ/', 'She enjoys singing.'],
  ['cooking', 'ovqat pishirish', '/ˈkʊkɪŋ/', 'Cooking is fun for me.'],
  ['gardening', 'bogʻdorchilik', '/ˈɡɑːdənɪŋ/', 'Gardening is his hobby.'],
  ['fishing', 'baliq ovi', '/ˈfɪʃɪŋ/', 'We go fishing on weekends.'],
  ['hiking', 'piyoda yurish', '/ˈhaɪkɪŋ/', 'Hiking in the mountains is great.'],
  ['camping', 'lager qurish', '/ˈkæmpɪŋ/', 'We went camping last summer.'],
  ['travelling', 'sayohat', '/ˈtrævəlɪŋ/', 'Travelling is my favourite hobby.'],
  ['photography', 'fotografiya', '/fəˈtɒɡrəfi/', 'Photography is her passion.'],
  ['collecting', 'toʻplash', '/kəˈlektɪŋ/', 'He likes collecting coins.'],
  ['knitting', 'toʻqish', '/ˈnɪtɪŋ/', 'My grandmother enjoys knitting.'],
  ['chess', 'shaxmat', '/tʃes/', 'We play chess every evening.'],
  ['puzzle', 'boshqotirma', '/ˈpʌzəl/', 'I solved a hard puzzle.'],
  ['game (hobby)', 'oʻyin', '/ɡeɪm/', 'Video games are fun.'],
  ['instrument', 'cholgʻu asbobi', '/ˈɪnstrʊmənt/', 'She plays an instrument.'],
  ['guitar', 'gitara', '/ɡɪˈtɑː/', 'He plays the guitar well.'],
  ['piano', 'pianino', '/piˈænəʊ/', 'She plays the piano beautifully.'],
  ['violin', 'skripka', '/ˌvaɪəˈlɪn/', 'He learns the violin.'],
  ['drum', 'baraban', '/drʌm/', 'My brother plays the drums.'],
  ['movie', 'kino', '/ˈmuːvi/', 'We watched a great movie.'],
  ['film', 'film', '/fɪlm/', 'This film is very interesting.'],
  ['concert', 'konsert', '/ˈkɒnsət/', 'We went to a rock concert.'],
  ['party', 'bazm', '/ˈpɑːti/', 'The party was a lot of fun.'],
  ['picnic', 'sayl', '/ˈpɪknɪk/', 'We had a picnic in the park.'],
  ['walk (hobby)', 'sayr', '/wɔːk/', 'I take a walk every evening.'],
  ['jog', 'yengil yugurish', '/dʒɒɡ/', 'I jog in the park each morning.'],
  ['surf', 'internetda yurish', '/sɜːf/', 'He surfs the internet for hours.'],
  ['blog', 'blog', '/blɒɡ/', 'She writes a travel blog.'],
  ['craft', 'hunarmandchilik', '/krɑːft/', 'She enjoys craft activities.'],
  ['baking', 'pishiriqlar tayyorlash', '/ˈbeɪkɪŋ/', 'Baking cakes is her hobby.'],
  ['volunteer', 'koʻngilli', '/ˌvɒlənˈtɪər/', 'She volunteers at a shelter.'],
  ['interest', 'qiziqish', '/ˈɪntrəst/', 'Music is my main interest.'],
  ['favourite', 'sevimli', '/ˈfeɪvərɪt/', 'This is my favourite hobby.'],
  ['relaxing hobby', 'dam beruvchi mashgʻulot', '/rɪˈlæksɪŋ ˈhɒbi/', 'Painting is a relaxing hobby.'],
  ['creative', 'ijodiy', '/kriˈeɪtɪv/', 'She is very creative.'],
  ['talent', 'isteʼdod', '/ˈtælənt/', 'He has a great talent for music.'],
  ['practise', 'mashq qilmoq', '/ˈpræktɪs/', 'I practise the guitar daily.'],
  ['join', 'qoʻshilmoq', '/dʒɔɪn/', 'I want to join a sports club.'],
  ['club', 'toʻgarak', '/klʌb/', 'She joined a book club.'],
  ['member', 'aʼzo', '/ˈmembər/', 'I am a member of the gym.'],
  ['activity', 'mashgʻulot', '/ækˈtɪvəti/', 'Swimming is a fun activity.'],
  ['enjoyable', 'yoqimli', '/ɪnˈdʒɔɪəbəl/', 'It was an enjoyable evening.'],
]

