// B1 — 1200 ta so'z (week 5,6,7,8): 1100 general + 100 phrasal
// [word, translation, phonetic, example_sentence]

export const B1_PHRASAL_RAW: [string, string, string, string][] = [
  ['give up', 'voz kechmoq', '/ɡɪv ʌp/', 'Never give up on your dreams.'],
  ['look after', 'gʻamxoʻrlik qilmoq', '/lʊk ˈɑːftər/', 'She looks after her sister.'],
  ['break down', 'buzilmoq', '/breɪk daʊn/', 'My car broke down on the way.'],
  ['carry out', 'amalga oshirmoq', '/ˈkæri aʊt/', 'They carried out the plan.'],
  ['come across', 'duch kelmoq', '/kʌm əˈkrɒs/', 'I came across an old photo.'],
  ['deal with', 'hal qilmoq', '/diːl wɪð/', 'He can deal with problems calmly.'],
  ['fall behind', 'orqada qolmoq', '/fɔːl bɪˈhaɪnd/', 'Do not fall behind in your studies.'],
  ['figure out', 'yechmoq, tushunmoq', '/ˈfɪɡər aʊt/', 'I cannot figure out this puzzle.'],
  ['get along', 'chiqishmoq', '/ɡet əˈlɒŋ/', 'They get along very well.'],
  ['go through', 'boshdan kechirmoq', '/ɡəʊ θruː/', 'She went through hard times.'],
  ['keep up', 'yetishmoq', '/kiːp ʌp/', 'I cannot keep up with the news.'],
  ['look into', 'tekshirmoq', '/lʊk ˈɪntuː/', 'The police will look into it.'],
  ['make up', 'oʻylab topmoq, yarashmoq', '/meɪk ʌp/', 'They made up after the argument.'],
  ['pick up', 'olib ketmoq', '/pɪk ʌp/', 'I will pick you up at six.'],
  ['point out', 'koʻrsatmoq', '/pɔɪnt aʊt/', 'She pointed out my mistake.'],
  ['put off', 'kechiktirmoq', '/pʊt ɒf/', 'Do not put off your homework.'],
  ['run out', 'tugamoq', '/rʌn aʊt/', 'We ran out of milk.'],
  ['set up', 'tashkil qilmoq', '/set ʌp/', 'They set up a new company.'],
  ['work out', 'hal boʻlmoq, shugʻullanmoq', '/wɜːk aʊt/', 'It will work out fine.'],
  ['turn out', 'maʼlum boʻlmoq', '/tɜːn aʊt/', 'It turned out to be true.'],
  ['bring up', 'tarbiyalamoq, koʻtarmoq', '/brɪŋ ʌp/', 'She brought up three children.'],
  ['call off', 'bekor qilmoq', '/kɔːl ɒf/', 'They called off the meeting.'],
  ['come up with', 'oʻylab topmoq', '/kʌm ʌp wɪð/', 'He came up with a great idea.'],
  ['cut down', 'kamaytirmoq', '/kʌt daʊn/', 'You should cut down on sugar.'],
  ['get over', 'yengmoq', '/ɡet ˈəʊvər/', 'It took her months to get over it.'],
  ['hold on', 'kutmoq', '/həʊld ɒn/', 'Hold on, I will check.'],
  ['give back', 'qaytarib bermoq', '/ɡɪv bæk/', 'Please give back my pen.'],
  ['take off', 'uchib ketmoq, yechmoq', '/teɪk ɒf/', 'The plane took off late.'],
  ['put on', 'kiymoq', '/pʊt ɒn/', 'Put on your jacket.'],
  ['look up', 'qidirib topmoq', '/lʊk ʌp/', 'Look up the word in a dictionary.'],
  ['find out', 'bilib olmoq', '/faɪnd aʊt/', 'I want to find out the truth.'],
  ['go on', 'davom etmoq', '/ɡəʊ ɒn/', 'Please go on with your story.'],
  ['get back', 'qaytmoq', '/ɡet bæk/', 'I will get back by noon.'],
  ['turn on', 'yoqmoq', '/tɜːn ɒn/', 'Turn on the light, please.'],
  ['turn off', 'oʻchirmoq', '/tɜːn ɒf/', 'Turn off the TV.'],
  ['turn down', 'rad etmoq', '/tɜːn daʊn/', 'She turned down the offer.'],
  ['turn up', 'paydo boʻlmoq', '/tɜːn ʌp/', 'He turned up late again.'],
  ['take care of', 'parvarish qilmoq', '/teɪk keər ɒv/', 'Take care of yourself.'],
  ['get up', 'oʻrindan turmoq', '/ɡet ʌp/', 'I get up at six.'],
  ['sit down', 'oʻtirmoq', '/sɪt daʊn/', 'Please sit down.'],
  ['stand up', 'oʻrnidan turmoq', '/stænd ʌp/', 'Stand up, everyone.'],
  ['wake up', 'uygʻonmoq', '/weɪk ʌp/', 'I wake up early.'],
  ['grow up', 'ulgʻaymoq', '/ɡrəʊ ʌp/', 'I grew up in a village.'],
  ['show up', 'kelmoq', '/ʃəʊ ʌp/', 'He did not show up.'],
  ['give in', 'taslim boʻlmoq', '/ɡɪv ɪn/', 'Do not give in to pressure.'],
  ['break up', 'ajralmoq', '/breɪk ʌp/', 'They broke up last month.'],
  ['catch up', 'yetib olmoq', '/kætʃ ʌp/', 'I need to catch up on work.'],
  ['hang out', 'vaqt oʻtkazmoq', '/hæŋ aʊt/', 'We hang out on weekends.'],
  ['hang on', 'kutmoq', '/hæŋ ɒn/', 'Hang on a second.'],
  ['hang up', 'goʻshakni qoʻymoq', '/hæŋ ʌp/', 'She hung up the phone.'],
  ['call back', 'qayta qoʻngʻiroq qilmoq', '/kɔːl bæk/', 'I will call you back.'],
  ['fill in', 'toʻldirmoq', '/fɪl ɪn/', 'Fill in this form, please.'],
  ['fill out', 'toʻldirmoq', '/fɪl aʊt/', 'Fill out the application.'],
  ['put away', 'joyiga qoʻymoq', '/pʊt əˈweɪ/', 'Put away your toys.'],
  ['put up with', 'chidamoq', '/pʊt ʌp wɪð/', 'I cannot put up with the noise.'],
  ['get rid of', 'qutulmoq', '/ɡet rɪd ɒv/', 'Get rid of the old furniture.'],
  ['look forward to', 'sabrsizlik bilan kutmoq', '/lʊk ˈfɔːwəd tuː/', 'I look forward to seeing you.'],
  ['run into', 'tasodifan uchratmoq', '/rʌn ˈɪntuː/', 'I ran into an old friend.'],
  ['go off', 'jiringlamoq, buzilmoq', '/ɡəʊ ɒf/', 'The alarm went off early.'],
  ['set off', 'yoʻlga chiqmoq', '/set ɒf/', 'We set off at dawn.'],
  ['take up', 'shugʻullana boshlamoq', '/teɪk ʌp/', 'He took up painting.'],
  ['take over', 'boshqaruvni olmoq', '/teɪk ˈəʊvər/', 'She took over the company.'],
  ['give away', 'sovgʻa qilmoq', '/ɡɪv əˈweɪ/', 'They gave away free tickets.'],
  ['back up', 'qoʻllab-quvvatlamoq', '/bæk ʌp/', 'I will back you up.'],
  ['bring back', 'qaytarib olib kelmoq', '/brɪŋ bæk/', 'Bring back my book tomorrow.'],
  ['bring about', 'sodir etmoq', '/brɪŋ əˈbaʊt/', 'The reforms brought about change.'],
  ['carry on', 'davom ettirmoq', '/ˈkæri ɒn/', 'Carry on with your work.'],
  ['check in', 'roʻyxatdan oʻtmoq', '/tʃek ɪn/', 'We checked in at the hotel.'],
  ['check out', 'tekshirib koʻrmoq', '/tʃek aʊt/', 'Check out this new app.'],
  ['clean up', 'tozalamoq', '/kliːn ʌp/', 'Clean up the kitchen, please.'],
  ['come back', 'qaytib kelmoq', '/kʌm bæk/', 'Come back soon.'],
  ['come in', 'kirmoq', '/kʌm ɪn/', 'Please come in.'],
  ['come out', 'chiqmoq', '/kʌm aʊt/', 'The sun came out.'],
  ['count on', 'ishonmoq', '/kaʊnt ɒn/', 'You can count on me.'],
  ['drop off', 'qoldirib ketmoq', '/drɒp ɒf/', 'I will drop you off at school.'],
  ['eat out', 'tashqarida ovqatlanmoq', '/iːt aʊt/', 'We eat out on Fridays.'],
  ['end up', 'oxir-oqibat boʻlmoq', '/end ʌp/', 'We ended up taking a taxi.'],
  ['get away', 'qochib ketmoq', '/ɡet əˈweɪ/', 'The thief got away.'],
  ['get in', 'kirmoq', '/ɡet ɪn/', 'Get in the car.'],
  ['get off', 'tushmoq', '/ɡet ɒf/', 'Get off at the next stop.'],
  ['get on', 'minmoq', '/ɡet ɒn/', 'Get on the bus quickly.'],
  ['give out', 'tarqatmoq', '/ɡɪv aʊt/', 'They gave out leaflets.'],
  ['go ahead', 'davom etmoq', '/ɡəʊ əˈhed/', 'Go ahead and start.'],
  ['go away', 'ketmoq', '/ɡəʊ əˈweɪ/', 'Please go away.'],
  ['go back', 'qaytmoq', '/ɡəʊ bæk/', 'Let us go back home.'],
  ['go down', 'pasaymoq', '/ɡəʊ daʊn/', 'Prices went down.'],
  ['go up', 'koʻtarilmoq', '/ɡəʊ ʌp/', 'Prices went up again.'],
  ['hand in', 'topshirmoq', '/hænd ɪn/', 'Hand in your homework.'],
  ['hand out', 'tarqatmoq', '/hænd aʊt/', 'The teacher handed out papers.'],
  ['keep on', 'davom ettirmoq', '/kiːp ɒn/', 'Keep on trying.'],
  ['leave out', 'tushirib qoldirmoq', '/liːv aʊt/', 'You left out one name.'],
  ['let down', 'umidsizlantirmoq', '/let daʊn/', 'Do not let me down.'],
  ['log in', 'tizimga kirmoq', '/lɒɡ ɪn/', 'Log in with your password.'],
  ['move in', 'koʻchib kirmoq', '/muːv ɪn/', 'They moved in last week.'],
  ['move out', 'koʻchib chiqmoq', '/muːv aʊt/', 'We move out next month.'],
  ['pass away', 'vafot etmoq', '/pɑːs əˈweɪ/', 'His grandfather passed away.'],
  ['pay back', 'qarzni qaytarmoq', '/peɪ bæk/', 'I will pay you back soon.'],
  ['set out', 'yoʻlga chiqmoq', '/set aʊt/', 'They set out early.'],
  ['sort out', 'hal qilmoq', '/sɔːt aʊt/', 'I will sort out the problem.'],
  ['warm up', 'qizdirmoq', '/wɔːm ʌp/', 'Warm up before exercise.'],
]

export const B1_GENERAL_RAW: [string, string, string, string][] = [
  // ── Society & culture ──
  ['society', 'jamiyat', '/səˈsaɪəti/', 'Society is changing fast.'],
  ['community', 'jamoa', '/kəˈmjuːnəti/', 'The community supports each other.'],
  ['tradition', 'anʼana', '/trəˈdɪʃən/', 'We respect old traditions.'],
  ['custom', 'urf-odat', '/ˈkʌstəm/', 'It is a local custom.'],
  ['culture', 'madaniyat', '/ˈkʌltʃər/', 'Their culture is very rich.'],
  ['heritage', 'meros', '/ˈherɪtɪdʒ/', 'We protect our cultural heritage.'],
  ['religion', 'din', '/rɪˈlɪdʒən/', 'Religion plays a big role here.'],
  ['belief', 'eʼtiqod', '/bɪˈliːf/', 'Everyone has their own beliefs.'],
  ['value', 'qadriyat', '/ˈvæljuː/', 'Family values are important.'],
  ['generation', 'avlod', '/ˌdʒenəˈreɪʃən/', 'The young generation thinks differently.'],
  ['population', 'aholi', '/ˌpɒpjʊˈleɪʃən/', 'The population is growing.'],
  ['citizen', 'fuqaro', '/ˈsɪtɪzən/', 'Every citizen has rights.'],
  ['equality', 'tenglik', '/ɪˈkwɒləti/', 'We believe in equality.'],
  ['freedom', 'erkinlik', '/ˈfriːdəm/', 'Freedom is a basic right.'],
  ['justice', 'adolat', '/ˈdʒʌstɪs/', 'People demand justice.'],
  ['responsibility', 'masʼuliyat', '/rɪˌspɒnsəˈbɪləti/', 'It is our responsibility.'],
  ['respect', 'hurmat', '/rɪˈspekt/', 'Show respect to elders.'],
  ['behaviour', 'xulq-atvor', '/bɪˈheɪvjər/', 'His behaviour was rude.'],
  ['attitude', 'munosabat', '/ˈætɪtjuːd/', 'She has a positive attitude.'],
  ['identity', 'oʻziga xoslik', '/aɪˈdentəti/', 'Language is part of identity.'],
  ['diversity', 'rang-baranglik', '/daɪˈvɜːsəti/', 'The city celebrates diversity.'],
  ['minority', 'ozchilik', '/maɪˈnɒrəti/', 'Minority rights are protected.'],
  ['discrimination', 'kamsitish', '/dɪˌskrɪmɪˈneɪʃən/', 'Discrimination is illegal.'],
  ['prejudice', 'xurofot', '/ˈpredʒʊdɪs/', 'We must fight prejudice.'],
  ['stereotype', 'qolip', '/ˈsteriətaɪp/', 'Avoid using stereotypes.'],
  ['custom (social)', 'odat', '/ˈkʌstəm/', 'Shaking hands is a common custom.'],
  ['festival', 'bayram', '/ˈfestɪvəl/', 'The festival lasts three days.'],
  ['ceremony', 'marosim', '/ˈserəməni/', 'The wedding ceremony was lovely.'],
  ['celebration', 'nishonlash', '/ˌselɪˈbreɪʃən/', 'It was a joyful celebration.'],
  ['ritual', 'urf-odat', '/ˈrɪtʃuəl/', 'It is an ancient ritual.'],
  ['social', 'ijtimoiy', '/ˈsəʊʃəl/', 'Social problems need solutions.'],
  ['urban', 'shahar', '/ˈɜːbən/', 'Urban life is busy.'],
  ['rural', 'qishloq', '/ˈrʊərəl/', 'Rural areas are quiet.'],
  ['lifestyle', 'turmush tarzi', '/ˈlaɪfstaɪl/', 'They have a healthy lifestyle.'],
  ['poverty', 'qashshoqlik', '/ˈpɒvəti/', 'Poverty remains a problem.'],
  ['wealth', 'boylik', '/welθ/', 'Wealth is not everything.'],
  ['class (social)', 'tabaqa', '/klɑːs/', 'The middle class is growing.'],
  ['status', 'maqom', '/ˈsteɪtəs/', 'Social status matters to some.'],
  ['gender', 'jins', '/ˈdʒendər/', 'Gender equality is important.'],
  ['immigration', 'immigratsiya', '/ˌɪmɪˈɡreɪʃən/', 'Immigration changed the city.'],
  ['integration', 'integratsiya', '/ˌɪntɪˈɡreɪʃən/', 'Integration takes time.'],
  ['globalisation', 'globallashuv', '/ˌɡləʊbəlaɪˈzeɪʃən/', 'Globalisation affects every country.'],
  ['custom officer', 'bojxona xodimi', '/ˈkʌstəm ˈɒfɪsər/', 'The customs officer checked our bags.'],
  ['volunteer (b1)', 'koʻngilli', '/ˌvɒlənˈtɪər/', 'Volunteers helped the victims.'],
  ['charity', 'xayriya', '/ˈtʃærəti/', 'They donated to charity.'],
  ['donation', 'xayriya badali', '/dəʊˈneɪʃən/', 'Every donation helps.'],
  ['support', 'qoʻllab-quvvatlash', '/səˈpɔːt/', 'They need our support.'],
  ['cooperation', 'hamkorlik', '/kəʊˌɒpəˈreɪʃən/', 'Cooperation leads to success.'],
  ['conflict', 'nizo', '/ˈkɒnflɪkt/', 'They resolved the conflict.'],
  ['agreement', 'kelishuv', '/əˈɡriːmənt/', 'They reached an agreement.'],
  // ── Environment ──
  ['environment', 'atrof-muhit', '/ɪnˈvaɪrənmənt/', 'We must protect the environment.'],
  ['nature', 'tabiat', '/ˈneɪtʃər/', 'Nature is beautiful here.'],
  ['pollution', 'ifloslanish', '/pəˈluːʃən/', 'Air pollution is a serious issue.'],
  ['climate change', 'iqlim oʻzgarishi', '/ˈklaɪmət tʃeɪndʒ/', 'Climate change affects us all.'],
  ['global warming', 'global isish', '/ˈɡləʊbəl ˈwɔːmɪŋ/', 'Global warming melts the ice.'],
  ['recycle', 'qayta ishlamoq', '/ˌriːˈsaɪkəl/', 'We recycle paper and glass.'],
  ['waste', 'chiqindi', '/weɪst/', 'Do not waste water.'],
  ['energy (env)', 'energiya', '/ˈenədʒi/', 'Solar energy is clean.'],
  ['resource', 'resurs', '/rɪˈzɔːs/', 'Water is a vital resource.'],
  ['natural', 'tabiiy', '/ˈnætʃərəl/', 'We use natural materials.'],
  ['forest (env)', 'oʻrmon', '/ˈfɒrɪst/', 'The forest is being cut down.'],
  ['wildlife', 'yovvoyi tabiat', '/ˈwaɪldlaɪf/', 'Wildlife needs protection.'],
  ['species', 'tur', '/ˈspiːʃiːz/', 'This species is endangered.'],
  ['endangered', 'yoʻqolib ketayotgan', '/ɪnˈdeɪndʒəd/', 'Tigers are an endangered animal.'],
  ['extinct', 'qirilib ketgan', '/ɪkˈstɪŋkt/', 'Dinosaurs are extinct.'],
  ['protect', 'himoya qilmoq', '/prəˈtekt/', 'We must protect the forests.'],
  ['conservation', 'muhofaza', '/ˌkɒnsəˈveɪʃən/', 'Conservation saves species.'],
  ['sustainable', 'barqaror', '/səˈsteɪnəbəl/', 'We need sustainable energy.'],
  ['renewable', 'qayta tiklanadigan', '/rɪˈnjuːəbəl/', 'Wind is renewable energy.'],
  ['carbon', 'uglerod', '/ˈkɑːbən/', 'Cars produce carbon emissions.'],
  ['emission', 'chiqindi (gaz)', '/ɪˈmɪʃən/', 'Reduce carbon emissions.'],
  ['greenhouse', 'issiqxona', '/ˈɡriːnhaʊs/', 'Greenhouse gases trap heat.'],
  ['ozone', 'ozon', '/ˈəʊzəʊn/', 'The ozone layer protects us.'],
  ['drought', 'qurgʻoqchilik', '/draʊt/', 'The drought destroyed the crops.'],
  ['flood (env)', 'toshqin', '/flʌd/', 'The flood damaged many homes.'],
  ['earthquake', 'zilzila', '/ˈɜːθkweɪk/', 'The earthquake was very strong.'],
  ['disaster', 'falokat', '/dɪˈzɑːstər/', 'It was a natural disaster.'],
  ['damage', 'zarar', '/ˈdæmɪdʒ/', 'The storm caused great damage.'],
  ['destroy', 'vayron qilmoq', '/dɪˈstrɔɪ/', 'Fire destroyed the building.'],
  ['plastic', 'plastik', '/ˈplæstɪk/', 'Plastic pollutes the ocean.'],
  ['litter', 'axlat', '/ˈlɪtər/', 'Do not drop litter here.'],
  ['rubbish', 'chiqindi', '/ˈrʌbɪʃ/', 'Take out the rubbish.'],
  ['atmosphere', 'atmosfera', '/ˈætməsfɪər/', 'Gases pollute the atmosphere.'],
  ['ocean', 'okean', '/ˈəʊʃən/', 'The ocean is full of plastic.'],
  ['planet', 'sayyora', '/ˈplænɪt/', 'We must save our planet.'],
  ['earth', 'yer', '/ɜːθ/', 'The earth is warming up.'],
  ['solar', 'quyosh', '/ˈsəʊlər/', 'Solar panels save money.'],
  ['fossil fuel', 'qazib olinadigan yoqilgʻi', '/ˈfɒsəl ˈfjuːəl/', 'Fossil fuels cause pollution.'],
  ['eco-friendly', 'ekologik toza', '/ˈiːkəʊ ˈfrendli/', 'This product is eco-friendly.'],
  ['organic', 'organik', '/ɔːˈɡænɪk/', 'They grow organic vegetables.'],
  ['contaminate', 'ifloslantirmoq', '/kənˈtæmɪneɪt/', 'Waste contaminates the river.'],
  ['preserve', 'asramoq', '/prɪˈzɜːv/', 'We must preserve nature.'],
  ['habitat', 'yashash joyi', '/ˈhæbɪtæt/', 'Animals lose their habitat.'],
  ['ecosystem', 'ekotizim', '/ˈiːkəʊsɪstəm/', 'Pollution harms the ecosystem.'],
  ['temperature rise', 'harorat koʻtarilishi', '/ˈtemprətʃər raɪz/', 'The temperature rise worries scientists.'],
  ['deforestation', 'oʻrmonlarni kesish', '/ˌdiːˌfɒrɪˈsteɪʃən/', 'Deforestation destroys habitats.'],
  ['recycling', 'qayta ishlash', '/ˌriːˈsaɪklɪŋ/', 'Recycling reduces waste.'],
  ['environmental', 'ekologik', '/ɪnˌvaɪrənˈmentl/', 'Environmental problems are serious.'],
  // ── Economy ──
  ['economy', 'iqtisodiyot', '/ɪˈkɒnəmi/', 'The economy is growing.'],
  ['economic', 'iqtisodiy', '/ˌiːkəˈnɒmɪk/', 'Economic growth is slow.'],
  ['finance', 'moliya', '/ˈfaɪnæns/', 'He studies finance.'],
  ['budget', 'byudjet', '/ˈbʌdʒɪt/', 'We have a tight budget.'],
  ['income', 'daromad', '/ˈɪnkʌm/', 'Their income is low.'],
  ['profit', 'foyda', '/ˈprɒfɪt/', 'The company made a profit.'],
  ['loss', 'zarar', '/lɒs/', 'They suffered a big loss.'],
  ['investment', 'investitsiya', '/ɪnˈvestmənt/', 'It was a good investment.'],
  ['invest', 'sarmoya kiritmoq', '/ɪnˈvest/', 'They invest in technology.'],
  ['market (economy)', 'bozor', '/ˈmɑːkɪt/', 'The market is unstable.'],
  ['trade', 'savdo', '/treɪd/', 'International trade is growing.'],
  ['export', 'eksport', '/ˈekspɔːt/', 'They export cotton abroad.'],
  ['import', 'import', '/ˈɪmpɔːt/', 'We import many goods.'],
  ['demand', 'talab', '/dɪˈmɑːnd/', 'Demand for oil is high.'],
  ['supply', 'taklif', '/səˈplaɪ/', 'The supply is limited.'],
  ['inflation', 'inflyatsiya', '/ɪnˈfleɪʃən/', 'Inflation reduces purchasing power.'],
  ['recession', 'tanglik', '/rɪˈseʃən/', 'The recession hit many families.'],
  ['unemployment', 'ishsizlik', '/ˌʌnɪmˈplɔɪmənt/', 'Unemployment is rising.'],
  ['debt', 'qarz', '/det/', 'The country has a huge debt.'],
  ['loan', 'kredit', '/ləʊn/', 'He took a bank loan.'],
  ['interest (bank)', 'foiz', '/ˈɪntrəst/', 'The interest rate went up.'],
  ['tax', 'soliq', '/tæks/', 'We pay income tax.'],
  ['currency (economy)', 'valyuta', '/ˈkʌrənsi/', 'The national currency is weak.'],
  ['exchange rate', 'valyuta kursi', '/ɪksˈtʃeɪndʒ reɪt/', 'The exchange rate changed.'],
  ['stock', 'aksiya', '/stɒk/', 'He bought company stock.'],
  ['share', 'ulush', '/ʃeər/', 'She owns shares in the firm.'],
  ['economy class', 'ekonom-klass', '/ɪˈkɒnəmi klɑːs/', 'We flew economy class.'],
  ['wealthy', 'badavlat', '/ˈwelθi/', 'They are a wealthy family.'],
  ['afford (economy)', 'puli yetmoq', '/əˈfɔːd/', 'They cannot afford a house.'],
  ['expense', 'xarajat', '/ɪkˈspens/', 'Travel expenses are high.'],
  ['cost of living', 'turmush qiymati', '/kɒst ɒv ˈlɪvɪŋ/', 'The cost of living rose.'],
  ['salary (economy)', 'oylik maosh', '/ˈsæləri/', 'Her salary increased.'],
  ['wage', 'ish haqi', '/weɪdʒ/', 'They earn a minimum wage.'],
  ['bankrupt', 'bankrot', '/ˈbæŋkrʌpt/', 'The company went bankrupt.'],
  ['financial', 'moliyaviy', '/faɪˈnænʃəl/', 'They have financial problems.'],
  ['economic growth', 'iqtisodiy oʻsish', '/ˌiːkəˈnɒmɪk ɡrəʊθ/', 'Economic growth created jobs.'],
  ['development', 'rivojlanish', '/dɪˈveləpmənt/', 'Development takes years.'],
  ['industry', 'sanoat', '/ˈɪndəstri/', 'The car industry is huge.'],
  ['production', 'ishlab chiqarish', '/prəˈdʌkʃən/', 'Production increased this year.'],
  ['consumer', 'isteʼmolchi', '/kənˈsjuːmər/', 'Consumers want low prices.'],
  ['goods', 'tovarlar', '/ɡʊdz/', 'These goods are imported.'],
  ['service (economy)', 'xizmat', '/ˈsɜːvɪs/', 'The service sector is growing.'],
  ['competition', 'raqobat', '/ˌkɒmpəˈtɪʃən/', 'There is strong competition.'],
  ['customer (economy)', 'mijoz', '/ˈkʌstəmər/', 'The customer is always right.'],
  ['monopoly', 'monopoliya', '/məˈnɒpəli/', 'They have a monopoly here.'],
  ['entrepreneur', 'tadbirkor', '/ˌɒntrəprəˈnɜː/', 'She is a young entrepreneur.'],
  ['stock market', 'fond bozori', '/stɒk ˈmɑːkɪt/', 'The stock market fell sharply.'],
  ['economist', 'iqtisodchi', '/ɪˈkɒnəmɪst/', 'The economist gave a forecast.'],
  // ── Relationships ──
  ['relationship', 'munosabat', '/rɪˈleɪʃənʃɪp/', 'They have a strong relationship.'],
  ['friendship', 'doʻstlik', '/ˈfrendʃɪp/', 'Their friendship is real.'],
  ['marriage', 'nikoh', '/ˈmærɪdʒ/', 'Their marriage is happy.'],
  ['wedding', 'toʻy', '/ˈwedɪŋ/', 'The wedding was beautiful.'],
  ['divorce', 'ajralish', '/dɪˈvɔːs/', 'They got a divorce.'],
  ['couple', 'er-xotin', '/ˈkʌpəl/', 'They are a lovely couple.'],
  ['partner', 'sherik', '/ˈpɑːtnər/', 'She lives with her partner.'],
  ['engaged', 'unashtirilgan', '/ɪnˈɡeɪdʒd/', 'They are engaged now.'],
  ['relative', 'qarindosh', '/ˈrelətɪv/', 'All my relatives came.'],
  ['neighbour (rel)', 'qoʻshni', '/ˈneɪbər/', 'My neighbours are kind.'],
  ['acquaintance', 'tanish', '/əˈkweɪntəns/', 'He is just an acquaintance.'],
  ['stranger', 'notanish', '/ˈstreɪndʒər/', 'Do not talk to strangers.'],
  ['trust (rel)', 'ishonch', '/trʌst/', 'Trust is the basis of love.'],
  ['loyalty', 'sadoqat', '/ˈlɔɪəlti/', 'Loyalty matters in friendship.'],
  ['honesty', 'halollik', '/ˈɒnəsti/', 'Honesty builds trust.'],
  ['argument', 'tortishuv', '/ˈɑːɡjʊmənt/', 'They had a big argument.'],
  ['quarrel', 'janjal', '/ˈkwɒrəl/', 'They had a small quarrel.'],
  ['apology', 'uzr', '/əˈpɒlədʒi/', 'He owes me an apology.'],
  ['forgive', 'kechirmoq', '/fəˈɡɪv/', 'Please forgive me.'],
  ['promise', 'vaʼda', '/ˈprɒmɪs/', 'He kept his promise.'],
  ['support (rel)', 'qoʻllab-quvvatlash', '/səˈpɔːt/', 'My family supports me.'],
  ['care for', 'gʻamxoʻrlik qilmoq', '/keər fɔː/', 'She cares for her parents.'],
  ['get to know', 'tanishmoq', '/ɡet tuː nəʊ/', 'I want to get to know you.'],
  ['date', 'uchrashuv', '/deɪt/', 'They went on a first date.'],
  ['affair', 'munosabat', '/əˈfeər/', 'It was a brief affair.'],
  ['romance', 'ishq', '/ˈrəʊmæns/', 'Their romance began at work.'],
  ['fiancé', 'kuyov', '/fiˈɒnseɪ/', 'Her fiancé is an engineer.'],
  ['in-laws', 'qaynonalar', '/ˈɪnlɔːz/', 'My in-laws are friendly.'],
  ['twin', 'egizak', '/twɪn/', 'They are identical twins.'],
  ['ancestor', 'ajdod', '/ˈænsestər/', 'Our ancestors lived here.'],
  ['descendant', 'avlod', '/dɪˈsendənt/', 'They are his descendants.'],
  ['bond', 'rishta', '/bɒnd/', 'They share a strong bond.'],
  ['intimate', 'yaqin', '/ˈɪntɪmət/', 'They have an intimate friendship.'],
  ['mutual', 'oʻzaro', '/ˈmjuːtʃuəl/', 'The respect is mutual.'],
  ['companion', 'hamroh', '/kəmˈpænjən/', 'A dog is a loyal companion.'],
  ['get along with', 'chiqishmoq', '/ɡet əˈlɒŋ wɪð/', 'I get along with my colleagues.'],
  ['fall in love', 'oshiq boʻlmoq', '/fɔːl ɪn lʌv/', 'They fell in love quickly.'],
  ['break up (rel)', 'ajralmoq', '/breɪk ʌp/', 'They broke up last year.'],
  ['split up', 'ajralib ketmoq', '/splɪt ʌp/', 'The couple split up.'],
  ['reconcile', 'yarashmoq', '/ˈrekənsaɪl/', 'They reconciled after the fight.'],
  ['betray', 'xiyonat qilmoq', '/bɪˈtreɪ/', 'He betrayed his friend.'],
  ['jealousy', 'rashk', '/ˈdʒeləsi/', 'Jealousy ruined their bond.'],
  ['affection', 'mehr', '/əˈfekʃən/', 'She showed great affection.'],
  ['sympathy', 'hamdardlik', '/ˈsɪmpəθi/', 'He has my sympathy.'],
  ['empathy', 'hamdardlik', '/ˈempəθi/', 'Empathy helps relationships.'],
  ['commitment', 'sodiqlik', '/kəˈmɪtmənt/', 'Marriage requires commitment.'],
  ['engagement', 'unashtirish', '/ɪnˈɡeɪdʒmənt/', 'They announced their engagement.'],
  ['get married', 'turmush qurmoq', '/ɡet ˈmærɪd/', 'They will get married in June.'],
  ['close friend', 'yaqin doʻst', '/kləʊs frend/', 'She is my close friend.'],
  // ── Science & technology ──
  ['science (b1)', 'fan', '/ˈsaɪəns/', 'Science improves our lives.'],
  ['research (b1)', 'tadqiqot', '/rɪˈsɜːtʃ/', 'The research took two years.'],
  ['experiment', 'tajriba', '/ɪkˈsperɪmənt/', 'They did a science experiment.'],
  ['theory', 'nazariya', '/ˈθɪəri/', 'It is just a theory.'],
  ['discovery', 'kashfiyot', '/dɪsˈkʌvəri/', 'It was an amazing discovery.'],
  ['invention', 'ixtiro', '/ɪnˈvenʃən/', 'The wheel was a great invention.'],
  ['invent', 'ixtiro qilmoq', '/ɪnˈvent/', 'He invented a new machine.'],
  ['discover', 'kashf etmoq', '/dɪsˈkʌvər/', 'They discovered a new planet.'],
  ['develop', 'rivojlantirmoq', '/dɪˈveləp/', 'They develop new software.'],
  ['technology (b1)', 'texnologiya', '/tekˈnɒlədʒi/', 'Technology changes everything.'],
  ['innovation', 'innovatsiya', '/ˌɪnəˈveɪʃən/', 'Innovation drives progress.'],
  ['engineering', 'muhandislik', '/ˌendʒɪˈnɪərɪŋ/', 'She studies engineering.'],
  ['laboratory', 'laboratoriya', '/ləˈbɒrətəri/', 'They work in a laboratory.'],
  ['equipment', 'jihozlar', '/ɪˈkwɪpmənt/', 'The lab has modern equipment.'],
  ['machine', 'mashina', '/məˈʃiːn/', 'The machine works automatically.'],
  ['robot (b1)', 'robot', '/ˈrəʊbɒt/', 'Robots build cars now.'],
  ['artificial intelligence', 'sunʼiy intellekt', '/ˌɑːtɪˈfɪʃəl ɪnˈtelɪdʒəns/', 'Artificial intelligence is growing fast.'],
  ['data (b1)', 'maʼlumotlar', '/ˈdeɪtə/', 'They collected a lot of data.'],
  ['analysis', 'tahlil', '/əˈnæləsɪs/', 'The analysis took a week.'],
  ['result (science)', 'natija', '/rɪˈzʌlt/', 'The results were surprising.'],
  ['evidence', 'dalil', '/ˈevɪdəns/', 'There is strong evidence.'],
  ['proof', 'isbot', '/pruːf/', 'We need solid proof.'],
  ['method', 'usul', '/ˈmeθəd/', 'They used a new method.'],
  ['process (science)', 'jarayon', '/ˈprəʊses/', 'It is a slow process.'],
  ['system', 'tizim', '/ˈsɪstəm/', 'The system is complex.'],
  ['function', 'vazifa', '/ˈfʌŋkʃən/', 'Each part has a function.'],
  ['structure', 'tuzilma', '/ˈstrʌktʃər/', 'The structure is strong.'],
  ['material', 'material', '/məˈtɪəriəl/', 'It is made of light material.'],
  ['chemical', 'kimyoviy modda', '/ˈkemɪkəl/', 'This chemical is dangerous.'],
  ['element', 'element', '/ˈelɪmənt/', 'Oxygen is a chemical element.'],
  ['atom', 'atom', '/ˈætəm/', 'An atom is very small.'],
  ['cell', 'hujayra', '/sel/', 'The body has many cells.'],
  ['gene', 'gen', '/dʒiːn/', 'Genes carry information.'],
  ['DNA', 'DNK', '/ˌdiː en ˈeɪ/', 'DNA holds genetic data.'],
  ['gravity', 'tortishish kuchi', '/ˈɡrævəti/', 'Gravity pulls things down.'],
  ['energy (science)', 'energiya', '/ˈenədʒi/', 'Energy cannot be destroyed.'],
  ['force', 'kuch', '/fɔːs/', 'Force changes motion.'],
  ['speed (science)', 'tezlik', '/spiːd/', 'Light travels at high speed.'],
  ['measure', 'oʻlchamoq', '/ˈmeʒər/', 'Measure the temperature now.'],
  ['calculate', 'hisoblamoq', '/ˈkælkjʊleɪt/', 'Calculate the total cost.'],
  ['estimate', 'taxmin qilmoq', '/ˈestɪmeɪt/', 'Estimate the distance.'],
  ['observe', 'kuzatmoq', '/əbˈzɜːv/', 'Scientists observe the stars.'],
  ['prove', 'isbotlamoq', '/pruːv/', 'They proved the theory.'],
  ['solve', 'yechmoq', '/sɒlv/', 'They solved the problem.'],
  ['design', 'loyihalamoq', '/dɪˈzaɪn/', 'Engineers design bridges.'],
  ['device (b1)', 'qurilma', '/dɪˈvaɪs/', 'This device saves energy.'],
  ['scientific', 'ilmiy', '/ˌsaɪənˈtɪfɪk/', 'It is a scientific fact.'],
  ['nuclear', 'yadroviy', '/ˈnjuːkliər/', 'Nuclear power is powerful.'],
  ['satellite', 'sunʼiy yoʻldosh', '/ˈsætəlaɪt/', 'The satellite orbits the earth.'],
  // ── Media ──
  ['media', 'ommaviy axborot vositalari', '/ˈmiːdiə/', 'The media reported the news.'],
  ['news', 'yangiliklar', '/njuːz/', 'The news is on at nine.'],
  ['newspaper', 'gazeta', '/ˈnjuːzpeɪpər/', 'I read the newspaper daily.'],
  ['magazine', 'jurnal', '/ˌmæɡəˈziːn/', 'She bought a fashion magazine.'],
  ['journalist (b1)', 'jurnalist', '/ˈdʒɜːnəlɪst/', 'The journalist wrote a report.'],
  ['report (media)', 'xabar', '/rɪˈpɔːt/', 'They aired a special report.'],
  ['article', 'maqola', '/ˈɑːtɪkəl/', 'I read an interesting article.'],
  ['headline', 'sarlavha', '/ˈhedlaɪn/', 'The headline was shocking.'],
  ['broadcast', 'efir', '/ˈbrɔːdkɑːst/', 'The match was broadcast live.'],
  ['channel', 'kanal', '/ˈtʃænəl/', 'Change the TV channel.'],
  ['programme', 'dastur', '/ˈprəʊɡræm/', 'This programme is educational.'],
  ['advertisement', 'reklama', '/ədˈvɜːtɪsmənt/', 'The advertisement was funny.'],
  ['advertising', 'reklama biznesi', '/ˈædvətaɪzɪŋ/', 'Advertising is everywhere.'],
  ['audience', 'tomoshabinlar', '/ˈɔːdiəns/', 'The audience clapped loudly.'],
  ['viewer', 'tomoshabin', '/ˈvjuːər/', 'Millions of viewers watched it.'],
  ['report (verb)', 'xabar bermoq', '/rɪˈpɔːt/', 'They report the news daily.'],
  ['publish', 'nashr qilmoq', '/ˈpʌblɪʃ/', 'They publish a daily paper.'],
  ['press', 'matbuot', '/pres/', 'The press covered the event.'],
  ['interview (media)', 'intervyu', '/ˈɪntəvjuː/', 'She gave an interview on TV.'],
  ['source', 'manba', '/sɔːs/', 'Check your sources carefully.'],
  ['fact', 'fakt', '/fækt/', 'Report only the facts.'],
  ['opinion', 'fikr', '/əˈpɪnjən/', 'Everyone has an opinion.'],
  ['rumour', 'mish-mish', '/ˈruːmər/', 'It was just a rumour.'],
  ['fake news', 'soxta yangilik', '/feɪk njuːz/', 'Fake news spreads fast.'],
  ['influence', 'taʼsir', '/ˈɪnflʊəns/', 'Media has a big influence.'],
  ['celebrity', 'mashhur shaxs', '/səˈlebrəti/', 'The celebrity gave a speech.'],
  ['popular', 'mashhur', '/ˈpɒpjʊlər/', 'This show is very popular.'],
  ['trend', 'tendentsiya', '/trend/', 'It became a global trend.'],
  ['content', 'kontent', '/ˈkɒntent/', 'They create video content.'],
  ['post', 'post', '/pəʊst/', 'She posted a photo online.'],
  ['comment', 'izoh', '/ˈkɒment/', 'He left a rude comment.'],
  ['follower', 'obunachi', '/ˈfɒləʊər/', 'She has many followers.'],
  ['viral', 'viral', '/ˈvaɪrəl/', 'The video went viral.'],
  ['stream', 'jonli efir', '/striːm/', 'They stream the match online.'],
  ['podcast', 'podkast', '/ˈpɒdkɑːst/', 'I listen to a podcast daily.'],
  ['documentary', 'hujjatli film', '/ˌdɒkjʊˈmentəri/', 'We watched a nature documentary.'],
  ['edit', 'tahrirlamoq', '/ˈedɪt/', 'She edits the videos.'],
  ['editor', 'muharrir', '/ˈedɪtər/', 'The editor checked the article.'],
  ['report a story', 'voqeani yoritmoq', '/rɪˈpɔːt ə ˈstɔːri/', 'They reported the story first.'],
  ['cover (news)', 'yoritmoq', '/ˈkʌvər/', 'The news covered the protest.'],
  ['announce', 'eʼlon qilmoq', '/əˈnaʊns/', 'They announced the results.'],
  ['statement', 'bayonot', '/ˈsteɪtmənt/', 'He made a public statement.'],
  ['interview (verb)', 'suhbatlashmoq', '/ˈɪntəvjuː/', 'They interviewed the witness.'],
  ['criticise', 'tanqid qilmoq', '/ˈkrɪtɪsaɪz/', 'Critics criticised the film.'],
  ['review (media)', 'sharh', '/rɪˈvjuː/', 'The film got good reviews.'],
  ['informative', 'maʼlumotli', '/ɪnˈfɔːmətɪv/', 'The article was very informative.'],
  ['biased', 'bir tomonlama', '/ˈbaɪəst/', 'The report was biased.'],
  ['reliable', 'ishonchli', '/rɪˈlaɪəbəl/', 'Use reliable news sources.'],
  ['journalism', 'jurnalistika', '/ˈdʒɜːnəlɪzəm/', 'She studies journalism.'],
  // ── Politics ──
  ['politics', 'siyosat', '/ˈpɒlətɪks/', 'He is interested in politics.'],
  ['government', 'hukumat', '/ˈɡʌvənmənt/', 'The government passed a law.'],
  ['president', 'prezident', '/ˈprezɪdənt/', 'The president gave a speech.'],
  ['minister', 'vazir', '/ˈmɪnɪstər/', 'The minister visited the school.'],
  ['parliament', 'parlament', '/ˈpɑːləmənt/', 'Parliament debated the issue.'],
  ['election', 'saylov', '/ɪˈlekʃən/', 'The election is next month.'],
  ['vote', 'ovoz bermoq', '/vəʊt/', 'Everyone has the right to vote.'],
  ['voter', 'saylovchi', '/ˈvəʊtər/', 'Voters chose a new leader.'],
  ['candidate', 'nomzod', '/ˈkændɪdeɪt/', 'She is a strong candidate.'],
  ['party (politics)', 'partiya', '/ˈpɑːti/', 'He joined a political party.'],
  ['policy', 'siyosat (yoʻnalish)', '/ˈpɒləsi/', 'The new policy helps farmers.'],
  ['law', 'qonun', '/lɔː/', 'The law protects citizens.'],
  ['leader', 'rahbar', '/ˈliːdər/', 'He is a great leader.'],
  ['power (politics)', 'hokimiyat', '/ˈpaʊər/', 'They came to power in 2020.'],
  ['authority', 'hokimiyat organi', '/ɔːˈθɒrəti/', 'The local authority decides this.'],
  ['rights', 'huquqlar', '/raɪts/', 'Human rights must be respected.'],
  ['democracy', 'demokratiya', '/dɪˈmɒkrəsi/', 'Democracy gives people a voice.'],
  ['republic', 'respublika', '/rɪˈpʌblɪk/', 'It became a republic in 1991.'],
  ['nation', 'millat', '/ˈneɪʃən/', 'The whole nation celebrated.'],
  ['national', 'milliy', '/ˈnæʃənəl/', 'It is a national holiday.'],
  ['international', 'xalqaro', '/ˌɪntəˈnæʃənəl/', 'It is an international issue.'],
  ['border', 'chegara', '/ˈbɔːdər/', 'They crossed the border.'],
  ['war', 'urush', '/wɔː/', 'The war lasted four years.'],
  ['peace', 'tinchlik', '/piːs/', 'Everyone wants peace.'],
  ['conflict (politics)', 'mojaro', '/ˈkɒnflɪkt/', 'The conflict ended peacefully.'],
  ['negotiate', 'muzokara olib bormoq', '/nɪˈɡəʊʃieɪt/', 'They negotiated a deal.'],
  ['treaty', 'shartnoma', '/ˈtriːti/', 'They signed a peace treaty.'],
  ['campaign', 'kampaniya', '/kæmˈpeɪn/', 'The campaign was successful.'],
  ['protest', 'norozilik', '/ˈprəʊtest/', 'Thousands joined the protest.'],
  ['reform', 'islohot', '/rɪˈfɔːm/', 'The reform improved education.'],
  ['corruption', 'korrupsiya', '/kəˈrʌpʃən/', 'They fight against corruption.'],
  ['speech', 'nutq', '/spiːtʃ/', 'The leader gave a long speech.'],
  ['debate', 'munozara', '/dɪˈbeɪt/', 'The debate lasted two hours.'],
  ['decision', 'qaror', '/dɪˈsɪʒən/', 'It was a difficult decision.'],
  ['agreement (politics)', 'kelishuv', '/əˈɡriːmənt/', 'They reached an agreement.'],
  ['ambassador', 'elchi', '/æmˈbæsədər/', 'The ambassador met the president.'],
  ['embassy', 'elchixona', '/ˈembəsi/', 'I went to the embassy.'],
  ['official', 'amaldor', '/əˈfɪʃəl/', 'A government official spoke.'],
  ['public opinion', 'jamoatchilik fikri', '/ˈpʌblɪk əˈpɪnjən/', 'Public opinion is divided.'],
  ['constitution', 'konstitutsiya', '/ˌkɒnstɪˈtjuːʃən/', 'The constitution protects rights.'],
  ['independence', 'mustaqillik', '/ˌɪndɪˈpendəns/', 'They gained independence.'],
  ['federal', 'federal', '/ˈfedərəl/', 'It is a federal law.'],
  ['liberal', 'liberal', '/ˈlɪbərəl/', 'He has liberal views.'],
  ['conservative', 'konservativ', '/kənˈsɜːvətɪv/', 'She holds conservative views.'],
  ['opposition', 'muxolifat', '/ˌɒpəˈzɪʃən/', 'The opposition criticised the plan.'],
  ['govern', 'boshqarmoq', '/ˈɡʌvən/', 'They govern the country wisely.'],
  ['represent', 'vakillik qilmoq', '/ˌreprɪˈzent/', 'He represents our region.'],
  ['citizenship', 'fuqarolik', '/ˈsɪtɪzənʃɪp/', 'She applied for citizenship.'],
  ['diplomacy', 'diplomatiya', '/dɪˈpləʊməsi/', 'Diplomacy avoided the war.'],
  ['sanction', 'sanksiya', '/ˈsæŋkʃən/', 'They imposed economic sanctions.'],
  // ── Health & medicine ──
  ['medicine (b1)', 'tibbiyot', '/ˈmedsɪn/', 'Medicine has advanced greatly.'],
  ['surgery', 'jarrohlik', '/ˈsɜːdʒəri/', 'She had heart surgery.'],
  ['surgeon', 'jarroh', '/ˈsɜːdʒən/', 'The surgeon was very skilled.'],
  ['diagnosis', 'tashxis', '/ˌdaɪəɡˈnəʊsɪs/', 'The diagnosis was correct.'],
  ['symptom', 'alomat', '/ˈsɪmptəm/', 'A fever is a common symptom.'],
  ['infection', 'infeksiya', '/ɪnˈfekʃən/', 'The infection spread quickly.'],
  ['virus (health)', 'virus', '/ˈvaɪrəs/', 'The virus is contagious.'],
  ['bacteria', 'bakteriya', '/bækˈtɪəriə/', 'Bacteria can cause illness.'],
  ['vaccine', 'vaksina', '/ˈvæksiːn/', 'The vaccine prevents the disease.'],
  ['immune', 'immunitetli', '/ɪˈmjuːn/', 'A strong immune system helps.'],
  ['therapy', 'terapiya', '/ˈθerəpi/', 'She started physical therapy.'],
  ['treatment (b1)', 'davolash', '/ˈtriːtmənt/', 'The treatment was effective.'],
  ['recovery', 'tuzalish', '/rɪˈkʌvəri/', 'His recovery was fast.'],
  ['prevention', 'oldini olish', '/prɪˈvenʃən/', 'Prevention is better than cure.'],
  ['nutrition', 'oziqlanish', '/njuˈtrɪʃən/', 'Good nutrition keeps you healthy.'],
  ['mental health', 'ruhiy salomatlik', '/ˈmentəl helθ/', 'Mental health is important.'],
  ['stress (health)', 'stress', '/stres/', 'Stress harms your health.'],
  ['fitness (b1)', 'sportiv holat', '/ˈfɪtnəs/', 'Fitness improves your mood.'],
  ['obesity', 'semizlik', '/əʊˈbiːsəti/', 'Obesity is a growing problem.'],
  ['cancer', 'saraton', '/ˈkænsər/', 'Early detection of cancer helps.'],
  ['disease (b1)', 'kasallik', '/dɪˈziːz/', 'Heart disease is common.'],
  ['pandemic', 'pandemiya', '/pænˈdemɪk/', 'The pandemic changed the world.'],
  ['epidemic', 'epidemiya', '/ˌepɪˈdemɪk/', 'The epidemic spread fast.'],
  ['hygiene', 'gigiyena', '/ˈhaɪdʒiːn/', 'Good hygiene prevents illness.'],
  ['clinic (b1)', 'klinika', '/ˈklɪnɪk/', 'The clinic offers free checkups.'],
  ['physician', 'shifokor', '/fɪˈzɪʃən/', 'The physician examined the patient.'],
  ['specialist', 'mutaxassis', '/ˈspeʃəlɪst/', 'She saw a heart specialist.'],
  ['injection', 'ukol', '/ɪnˈdʒekʃən/', 'The injection did not hurt.'],
  ['antibiotic', 'antibiotik', '/ˌæntibaɪˈɒtɪk/', 'The doctor prescribed antibiotics.'],
  ['painkiller', 'ogʻriq qoldiruvchi', '/ˈpeɪnkɪlər/', 'Take a painkiller for the ache.'],
  ['dose', 'doza', '/dəʊs/', 'Take the correct dose.'],
  ['heal', 'davolanmoq', '/hiːl/', 'The wound will heal soon.'],
  ['cure (b1)', 'davo', '/kjʊə/', 'Scientists seek a cure.'],
  ['examine', 'tekshirmoq', '/ɪɡˈzæmɪn/', 'The doctor examined me.'],
  ['prescribe', 'dori belgilamoq', '/prɪˈskraɪb/', 'The doctor prescribed rest.'],
  ['suffer', 'azob chekmoq', '/ˈsʌfər/', 'He suffers from headaches.'],
  ['breath', 'nafas', '/breθ/', 'Take a deep breath.'],
  ['pulse', 'tomir urishi', '/pʌls/', 'The nurse checked my pulse.'],
  ['organ', 'aʼzo', '/ˈɔːɡən/', 'The heart is a vital organ.'],
  ['brain', 'miya', '/breɪn/', 'The brain controls the body.'],
  ['lung', 'oʻpka', '/lʌŋ/', 'Smoking damages the lungs.'],
  ['kidney', 'buyrak', '/ˈkɪdni/', 'He had a kidney problem.'],
  ['liver', 'jigar', '/ˈlɪvər/', 'Alcohol harms the liver.'],
  ['nerve', 'asab', '/nɜːv/', 'A nerve was damaged.'],
  ['painful (b1)', 'ogʻriqli', '/ˈpeɪnfəl/', 'The treatment was painful.'],
  ['chronic', 'surunkali', '/ˈkrɒnɪk/', 'She has a chronic illness.'],
  ['severe', 'ogʻir', '/sɪˈvɪər/', 'He had a severe headache.'],
  ['fatal', 'oʻlim bilan tugaydigan', '/ˈfeɪtəl/', 'The disease can be fatal.'],
  ['healthy diet', 'sogʻlom ovqatlanish', '/ˈhelθi ˈdaɪət/', 'A healthy diet prevents disease.'],
  ['well-being', 'farovonlik', '/wel ˈbiːɪŋ/', 'Exercise improves well-being.'],
  // ── Education system ──
  ['curriculum', 'oʻquv dasturi', '/kəˈrɪkjʊləm/', 'The curriculum was updated.'],
  ['syllabus', 'oʻquv reja', '/ˈsɪləbəs/', 'The syllabus covers ten topics.'],
  ['kindergarten', 'bogʻcha', '/ˈkɪndəɡɑːtən/', 'My son goes to kindergarten.'],
  ['primary school', 'boshlangʻich maktab', '/ˈpraɪməri skuːl/', 'She teaches at a primary school.'],
  ['secondary school', 'oʻrta maktab', '/ˈsekəndəri skuːl/', 'He finished secondary school.'],
  ['academic', 'akademik', '/ˌækəˈdemɪk/', 'She has academic skills.'],
  ['tuition', 'oʻquv toʻlovi', '/tjuˈɪʃən/', 'University tuition is expensive.'],
  ['lecture', 'maʼruza', '/ˈlektʃər/', 'The lecture was interesting.'],
  ['seminar', 'seminar', '/ˈsemɪnɑː/', 'I attended a science seminar.'],
  ['assignment', 'topshiriq', '/əˈsaɪnmənt/', 'Submit your assignment on time.'],
  ['deadline (edu)', 'muddat', '/ˈdedlaɪn/', 'The essay deadline is Friday.'],
  ['qualification', 'malaka', '/ˌkwɒlɪfɪˈkeɪʃən/', 'He has the right qualifications.'],
  ['degree (b1)', 'daraja', '/dɪˈɡriː/', 'She earned a master’s degree.'],
  ['bachelor', 'bakalavr', '/ˈbætʃələr/', 'He has a bachelor’s degree.'],
  ['master', 'magistr', '/ˈmɑːstər/', 'She is doing a master’s.'],
  ['doctorate', 'doktorlik', '/ˈdɒktərət/', 'He earned a doctorate.'],
  ['graduate (b1)', 'bitiruvchi', '/ˈɡrædʒuət/', 'She is a recent graduate.'],
  ['assessment', 'baholash', '/əˈsesmənt/', 'The assessment was fair.'],
  ['evaluation', 'baholash', '/ɪˌvæljuˈeɪʃən/', 'The evaluation is detailed.'],
  ['feedback', 'fikr-mulohaza', '/ˈfiːdbæk/', 'The teacher gave feedback.'],
  ['progress', 'taraqqiyot', '/ˈprəʊɡres/', 'She made good progress.'],
  ['achievement', 'yutuq', '/əˈtʃiːvmənt/', 'It was a great achievement.'],
  ['discipline', 'intizom', '/ˈdɪsəplɪn/', 'The school has strict discipline.'],
  ['motivation', 'motivatsiya', '/ˌməʊtɪˈveɪʃən/', 'Motivation drives learning.'],
  ['concentrate', 'diqqatni jamlamoq', '/ˈkɒnsəntreɪt/', 'I cannot concentrate here.'],
  ['memorise', 'yodlamoq', '/ˈmeməraɪz/', 'Memorise the new words.'],
  ['analyse', 'tahlil qilmoq', '/ˈænəlaɪz/', 'Analyse the data carefully.'],
  ['summarise', 'xulosalamoq', '/ˈsʌməraɪz/', 'Summarise the article.'],
  ['compare', 'taqqoslamoq', '/kəmˈpeər/', 'Compare these two methods.'],
  ['discuss', 'muhokama qilmoq', '/dɪsˈkʌs/', 'Let us discuss the topic.'],
  ['explain (edu)', 'tushuntirmoq', '/ɪkˈspleɪn/', 'Can you explain this rule?'],
  ['describe', 'taʼriflamoq', '/dɪsˈkraɪb/', 'Describe your hometown.'],
  ['define', 'taʼrif bermoq', '/dɪˈfaɪn/', 'Define the word clearly.'],
  ['identify', 'aniqlamoq', '/aɪˈdentɪfaɪ/', 'Identify the main idea.'],
  ['conclude', 'xulosa chiqarmoq', '/kənˈkluːd/', 'They concluded the lesson.'],
  ['knowledge (b1)', 'bilim', '/ˈnɒlɪdʒ/', 'Knowledge opens doors.'],
  ['intelligence', 'aql-zakovat', '/ɪnˈtelɪdʒəns/', 'She has high intelligence.'],
  ['skill (b1)', 'mahorat', '/skɪl/', 'Communication is a key skill.'],
  ['ability', 'qobiliyat', '/əˈbɪləti/', 'He has great ability.'],
  ['talented', 'isteʼdodli', '/ˈtæləntɪd/', 'She is a talented student.'],
  ['fluent', 'ravon', '/ˈfluːənt/', 'He is fluent in English.'],
  ['literacy', 'savodxonlik', '/ˈlɪtərəsi/', 'Literacy rates are rising.'],
  ['scholar', 'olim', '/ˈskɒlər/', 'He is a respected scholar.'],
  ['institution', 'muassasa', '/ˌɪnstɪˈtjuːʃən/', 'It is a famous institution.'],
  ['faculty', 'fakultet', '/ˈfækəlti/', 'She joined the law faculty.'],
  ['enrol', 'roʻyxatdan oʻtmoq', '/ɪnˈrəʊl/', 'I will enrol next year.'],
  ['exam (b1)', 'imtihon', '/ɪɡˈzæm/', 'The final exam is difficult.'],
  ['cheat', 'koʻchirmoq', '/tʃiːt/', 'Do not cheat in the exam.'],
  ['plagiarism', 'plagiat', '/ˈpleɪdʒərɪzəm/', 'Plagiarism is a serious offence.'],
  ['educate', 'taʼlim bermoq', '/ˈedjʊkeɪt/', 'They educate young children.'],
  // ── Work & career ──
  ['profession', 'kasb', '/prəˈfeʃən/', 'Teaching is a noble profession.'],
  ['occupation', 'mashgʻulot', '/ˌɒkjʊˈpeɪʃən/', 'What is your occupation?'],
  ['employment', 'bandlik', '/ɪmˈplɔɪmənt/', 'Employment rates improved.'],
  ['recruitment', 'ishga yollash', '/rɪˈkruːtmənt/', 'The recruitment process is long.'],
  ['applicant', 'nomzod', '/ˈæplɪkənt/', 'There were many applicants.'],
  ['candidate (work)', 'nomzod', '/ˈkændɪdeɪt/', 'She is the best candidate.'],
  ['CV', 'rezyume', '/ˌsiː ˈviː/', 'Send your CV by email.'],
  ['resume', 'rezyume', '/ˈrezjʊmeɪ/', 'Update your resume regularly.'],
  ['vacancy', 'boʻsh ish oʻrni', '/ˈveɪkənsi/', 'There is a job vacancy.'],
  ['position', 'lavozim', '/pəˈzɪʃən/', 'He applied for the position.'],
  ['promotion', 'lavozimga koʻtarilish', '/prəˈməʊʃən/', 'She got a promotion.'],
  ['responsibility (work)', 'majburiyat', '/rɪˌspɒnsəˈbɪləti/', 'It is a big responsibility.'],
  ['duty', 'vazifa', '/ˈdjuːti/', 'It is my duty to help.'],
  ['skill set', 'koʻnikmalar toʻplami', '/skɪl set/', 'She has a strong skill set.'],
  ['experience', 'tajriba', '/ɪkˈspɪəriəns/', 'He has ten years of experience.'],
  ['expertise', 'mutaxassislik', '/ˌekspɜːˈtiːz/', 'Her expertise is valuable.'],
  ['training (work)', 'oʻqitish', '/ˈtreɪnɪŋ/', 'New staff get training.'],
  ['workplace', 'ish joyi', '/ˈwɜːkpleɪs/', 'The workplace is friendly.'],
  ['workforce', 'ishchi kuchi', '/ˈwɜːkfɔːs/', 'The workforce is skilled.'],
  ['staff', 'xodimlar', '/stɑːf/', 'The staff are very helpful.'],
  ['team (work)', 'jamoa', '/tiːm/', 'We work well as a team.'],
  ['teamwork', 'jamoaviy ish', '/ˈtiːmwɜːk/', 'Teamwork brings success.'],
  ['leadership', 'rahbarlik', '/ˈliːdəʃɪp/', 'Good leadership matters.'],
  ['management', 'boshqaruv', '/ˈmænɪdʒmənt/', 'Time management is essential.'],
  ['supervisor', 'nazoratchi', '/ˈsuːpəvaɪzər/', 'My supervisor is supportive.'],
  ['client', 'mijoz', '/ˈklaɪənt/', 'The client was satisfied.'],
  ['deadline (work)', 'muddat', '/ˈdedlaɪn/', 'We met the deadline.'],
  ['shift', 'smena', '/ʃɪft/', 'I work the night shift.'],
  ['part-time', 'yarim stavka', '/ˌpɑːt ˈtaɪm/', 'She has a part-time job.'],
  ['full-time', 'toʻliq stavka', '/ˌfʊl ˈtaɪm/', 'He works full-time.'],
  ['freelance', 'frilans', '/ˈfriːlɑːns/', 'She works as a freelance writer.'],
  ['resign', 'isteʼfoga chiqmoq', '/rɪˈzaɪn/', 'He decided to resign.'],
  ['dismiss', 'ishdan boʻshatmoq', '/dɪsˈmɪs/', 'They dismissed two workers.'],
  ['unemployed', 'ishsiz', '/ˌʌnɪmˈplɔɪd/', 'He has been unemployed for months.'],
  ['pension', 'nafaqa', '/ˈpenʃən/', 'He receives a monthly pension.'],
  ['benefit', 'imtiyoz', '/ˈbenɪfɪt/', 'The job has good benefits.'],
  ['bonus', 'bonus', '/ˈbəʊnəs/', 'She received a year-end bonus.'],
  ['negotiation', 'muzokara', '/nɪˌɡəʊʃiˈeɪʃən/', 'The salary negotiation went well.'],
  ['productivity', 'unumdorlik', '/ˌprɒdʌkˈtɪvəti/', 'Productivity has increased.'],
  ['efficient', 'samarali', '/ɪˈfɪʃənt/', 'She is a very efficient worker.'],
  ['ambitious', 'shijoatli', '/æmˈbɪʃəs/', 'He is an ambitious young man.'],
  ['professional', 'professional', '/prəˈfeʃənəl/', 'She is a true professional.'],
  ['colleague (work)', 'hamkasb', '/ˈkɒliːɡ/', 'My colleagues are friendly.'],
  ['apply (work)', 'ariza bermoq', '/əˈplaɪ/', 'I will apply for the job.'],
  ['hire', 'ishga olmoq', '/ˈhaɪər/', 'They hired ten new staff.'],
  ['earn', 'ishlab topmoq', '/ɜːn/', 'She earns a good income.'],
  ['achieve', 'erishmoq', '/əˈtʃiːv/', 'You can achieve your goals.'],
  ['succeed', 'muvaffaqiyat qozonmoq', '/səkˈsiːd/', 'Hard work helps you succeed.'],
  ['career path', 'kasb yoʻli', '/kəˈrɪər pɑːθ/', 'She planned her career path.'],
  ['workload', 'ish yuki', '/ˈwɜːkləʊd/', 'My workload is heavy this week.'],
  // ── General advanced (B1) ──
  ['ability (gen)', 'qobiliyat', '/əˈbɪləti/', 'He has the ability to learn fast.'],
  ['accept', 'qabul qilmoq', '/əkˈsept/', 'Please accept my apology.'],
  ['according to', 'koʻra', '/əˈkɔːdɪŋ tuː/', 'According to the report, it is true.'],
  ['achievement (gen)', 'yutuq', '/əˈtʃiːvmənt/', 'It was her greatest achievement.'],
  ['acknowledge', 'tan olmoq', '/əkˈnɒlɪdʒ/', 'He acknowledged his mistake.'],
  ['adapt', 'moslashmoq', '/əˈdæpt/', 'They adapted to the change.'],
  ['additional', 'qoʻshimcha', '/əˈdɪʃənəl/', 'We need additional time.'],
  ['adequate', 'yetarli', '/ˈædɪkwət/', 'The food was adequate.'],
  ['adjust', 'moslashtirmoq', '/əˈdʒʌst/', 'Adjust the volume, please.'],
  ['admire', 'qoyil qolmoq', '/ədˈmaɪər/', 'I admire her courage.'],
  ['admit', 'tan olmoq', '/ədˈmɪt/', 'He admitted his fault.'],
  ['advance', 'ilgarilamoq', '/ədˈvɑːns/', 'Technology advances rapidly.'],
  ['advantage', 'afzallik', '/ədˈvɑːntɪdʒ/', 'Speed is a big advantage.'],
  ['affect', 'taʼsir qilmoq', '/əˈfekt/', 'Stress can affect your health.'],
  ['afford (gen)', 'qodir boʻlmoq', '/əˈfɔːd/', 'I cannot afford it now.'],
  ['aim', 'maqsad', '/eɪm/', 'My aim is to pass the test.'],
  ['allow', 'ruxsat bermoq', '/əˈlaʊ/', 'They do not allow smoking.'],
  ['alternative', 'muqobil', '/ɔːlˈtɜːnətɪv/', 'Is there an alternative plan?'],
  ['amount', 'miqdor', '/əˈmaʊnt/', 'A small amount of salt is enough.'],
  ['announce (gen)', 'eʼlon qilmoq', '/əˈnaʊns/', 'They announced the winner.'],
  ['anxious', 'tashvishli', '/ˈæŋkʃəs/', 'She felt anxious about the exam.'],
  ['apologise', 'uzr soʻramoq', '/əˈpɒlədʒaɪz/', 'I apologise for being late.'],
  ['appear (gen)', 'paydo boʻlmoq', '/əˈpɪər/', 'A problem appeared suddenly.'],
  ['appreciate', 'qadrlamoq', '/əˈpriːʃieɪt/', 'I appreciate your help.'],
  ['appropriate', 'mos', '/əˈprəʊpriət/', 'Wear appropriate clothes.'],
  ['approve', 'maʼqullamoq', '/əˈpruːv/', 'The boss approved the plan.'],
  ['arrange', 'tashkil qilmoq', '/əˈreɪndʒ/', 'I will arrange a meeting.'],
  ['assist', 'yordam bermoq', '/əˈsɪst/', 'Can you assist me, please?'],
  ['assume', 'taxmin qilmoq', '/əˈsjuːm/', 'Do not assume the worst.'],
  ['attempt', 'urinish', '/əˈtempt/', 'It was a brave attempt.'],
  ['attract', 'jalb qilmoq', '/əˈtrækt/', 'The city attracts tourists.'],
  ['avoid', 'qochmoq', '/əˈvɔɪd/', 'Avoid junk food.'],
  ['aware', 'xabardor', '/əˈweər/', 'I am aware of the risks.'],
  ['balance', 'muvozanat', '/ˈbæləns/', 'Keep a healthy balance.'],
  ['behave', 'oʻzini tutmoq', '/bɪˈheɪv/', 'The children behaved well.'],
  ['benefit (gen)', 'foyda', '/ˈbenɪfɪt/', 'Exercise has many benefits.'],
  ['blame', 'aybdor qilmoq', '/bleɪm/', 'Do not blame yourself.'],
  ['borrow', 'qarz olmoq', '/ˈbɒrəʊ/', 'Can I borrow your pen?'],
  ['brief', 'qisqa', '/briːf/', 'He gave a brief speech.'],
  ['cause', 'sabab boʻlmoq', '/kɔːz/', 'Smoking causes diseases.'],
  ['challenge', 'qiyinchilik', '/ˈtʃælɪndʒ/', 'It was a difficult challenge.'],
  ['choice', 'tanlov', '/tʃɔɪs/', 'You have a good choice.'],
  ['claim', 'daʼvo qilmoq', '/kleɪm/', 'He claims to be innocent.'],
  ['clarify', 'aniqlashtirmoq', '/ˈklærɪfaɪ/', 'Please clarify your point.'],
  ['combine', 'birlashtirmoq', '/kəmˈbaɪn/', 'Combine the two methods.'],
  ['comment (gen)', 'izoh bermoq', '/ˈkɒment/', 'She did not comment on it.'],
  ['common', 'umumiy', '/ˈkɒmən/', 'It is a common mistake.'],
  ['communicate', 'muloqot qilmoq', '/kəˈmjuːnɪkeɪt/', 'They communicate by email.'],
  ['complain', 'shikoyat qilmoq', '/kəmˈpleɪn/', 'He complained about the noise.'],
  ['complete', 'tugatmoq', '/kəmˈpliːt/', 'Please complete the form.'],
  ['complex', 'murakkab', '/ˈkɒmpleks/', 'It is a complex problem.'],
  ['concern', 'tashvish', '/kənˈsɜːn/', 'Safety is our main concern.'],
  ['conclude (gen)', 'xulosa qilmoq', '/kənˈkluːd/', 'We concluded the talks.'],
  ['confident', 'ishonchli', '/ˈkɒnfɪdənt/', 'She is confident and calm.'],
  ['confirm', 'tasdiqlamoq', '/kənˈfɜːm/', 'Please confirm your booking.'],
  ['confuse', 'chalkashtirmoq', '/kənˈfjuːz/', 'The signs confuse drivers.'],
  ['connect (gen)', 'bogʻlamoq', '/kəˈnekt/', 'The road connects two towns.'],
  ['consider', 'koʻrib chiqmoq', '/kənˈsɪdər/', 'Consider all the options.'],
  ['consist', 'iborat boʻlmoq', '/kənˈsɪst/', 'The team consists of five people.'],
  ['contain', 'tarkibida boʻlmoq', '/kənˈteɪn/', 'This drink contains sugar.'],
  ['continue (gen)', 'davom etmoq', '/kənˈtɪnjuː/', 'Continue until you finish.'],
  ['contribute', 'hissa qoʻshmoq', '/kənˈtrɪbjuːt/', 'Everyone contributed money.'],
  ['convince', 'ishontirmoq', '/kənˈvɪns/', 'He convinced me to stay.'],
  ['create', 'yaratmoq', '/kriˈeɪt/', 'They create new jobs.'],
  ['decide', 'qaror qilmoq', '/dɪˈsaɪd/', 'I decided to leave early.'],
  ['decrease', 'kamaymoq', '/dɪˈkriːs/', 'Prices decreased last month.'],
  ['define (gen)', 'taʼriflamoq', '/dɪˈfaɪn/', 'Define your goals first.'],
  ['deliver (gen)', 'yetkazmoq', '/dɪˈlɪvər/', 'They deliver within an hour.'],
  ['demand (gen)', 'talab qilmoq', '/dɪˈmɑːnd/', 'Workers demanded higher pay.'],
  ['deny', 'inkor etmoq', '/dɪˈnaɪ/', 'He denied the accusation.'],
  ['depend', 'bogʻliq boʻlmoq', '/dɪˈpend/', 'It depends on the weather.'],
  ['describe (gen)', 'tasvirlamoq', '/dɪsˈkraɪb/', 'Describe what you saw.'],
  ['deserve', 'loyiq boʻlmoq', '/dɪˈzɜːv/', 'You deserve a reward.'],
  ['desire', 'istak', '/dɪˈzaɪər/', 'She has a strong desire to win.'],
  ['determine', 'aniqlamoq', '/dɪˈtɜːmɪn/', 'Tests determine the cause.'],
  ['develop (gen)', 'rivojlanmoq', '/dɪˈveləp/', 'The plan is still developing.'],
  ['difference', 'farq', '/ˈdɪfərəns/', 'There is a big difference.'],
  ['discuss (gen)', 'muhokama qilmoq', '/dɪsˈkʌs/', 'We discussed the budget.'],
  ['distance', 'masofa', '/ˈdɪstəns/', 'The distance is long.'],
  ['divide', 'boʻlmoq', '/dɪˈvaɪd/', 'Divide the work fairly.'],
  ['effect', 'taʼsir', '/ɪˈfekt/', 'The medicine had a quick effect.'],
  ['effort', 'sayʼ-harakat', '/ˈefət/', 'It took a lot of effort.'],
  ['encourage', 'ragʻbatlantirmoq', '/ɪnˈkʌrɪdʒ/', 'Teachers encourage students.'],
  ['ensure', 'taʼminlamoq', '/ɪnˈʃʊə/', 'Ensure the door is locked.'],
  ['environment (gen)', 'sharoit', '/ɪnˈvaɪrənmənt/', 'A calm environment helps work.'],
  ['establish', 'tashkil etmoq', '/ɪˈstæblɪʃ/', 'They established a new firm.'],
  ['estimate (gen)', 'baholamoq', '/ˈestɪmeɪt/', 'Estimate the total cost.'],
  ['evidence (gen)', 'dalil', '/ˈevɪdəns/', 'There is no clear evidence.'],
  ['examine (gen)', 'koʻrib chiqmoq', '/ɪɡˈzæmɪn/', 'Examine the results carefully.'],
  ['exist', 'mavjud boʻlmoq', '/ɪɡˈzɪst/', 'Such problems still exist.'],
  ['expand', 'kengaytirmoq', '/ɪkˈspænd/', 'They plan to expand the business.'],
  ['expect', 'kutmoq', '/ɪkˈspekt/', 'I expect good results.'],
  ['experience (gen)', 'boshdan kechirmoq', '/ɪkˈspɪəriəns/', 'We experienced heavy rain.'],
  ['explore (gen)', 'oʻrganmoq', '/ɪkˈsplɔː/', 'Explore all the options.'],
  ['express', 'ifodalamoq', '/ɪkˈspres/', 'Express your opinion clearly.'],
  ['extend', 'uzaytirmoq', '/ɪkˈstend/', 'They extended the deadline.'],
  ['familiar', 'tanish', '/fəˈmɪliər/', 'This place looks familiar.'],
  ['focus', 'eʼtibor qaratmoq', '/ˈfəʊkəs/', 'Focus on your studies.'],
  ['force (gen)', 'majburlamoq', '/fɔːs/', 'Do not force him to go.'],
  ['frequent', 'tez-tez', '/ˈfriːkwənt/', 'He is a frequent visitor.'],
  ['gain', 'erishmoq', '/ɡeɪn/', 'You will gain experience.'],
  ['generate', 'hosil qilmoq', '/ˈdʒenəreɪt/', 'The plant generates power.'],
  ['guarantee', 'kafolat bermoq', '/ˌɡærənˈtiː/', 'We guarantee good quality.'],
  ['handle', 'uddalamoq', '/ˈhændəl/', 'She can handle pressure.'],
  ['identify (gen)', 'aniqlamoq', '/aɪˈdentɪfaɪ/', 'Identify the main problem.'],
  ['ignore', 'eʼtiborsiz qoldirmoq', '/ɪɡˈnɔː/', 'Do not ignore the warning.'],
  ['imagine', 'tasavvur qilmoq', '/ɪˈmædʒɪn/', 'Imagine a better future.'],
  ['impact', 'taʼsir', '/ˈɪmpækt/', 'The decision had a big impact.'],
  ['improve', 'yaxshilamoq', '/ɪmˈpruːv/', 'I want to improve my English.'],
  ['include', 'oʻz ichiga olmoq', '/ɪnˈkluːd/', 'The price includes tax.'],
  ['increase', 'oshirmoq', '/ɪnˈkriːs/', 'They increased the prices.'],
  ['indicate', 'koʻrsatmoq', '/ˈɪndɪkeɪt/', 'The signs indicate danger.'],
  ['influence (gen)', 'taʼsir qilmoq', '/ˈɪnflʊəns/', 'Parents influence children.'],
  ['inform', 'xabardor qilmoq', '/ɪnˈfɔːm/', 'Please inform me of changes.'],
  ['injure', 'jarohatlamoq', '/ˈɪndʒər/', 'He injured his knee.'],
  ['intend', 'niyat qilmoq', '/ɪnˈtend/', 'I intend to study abroad.'],
  ['introduce', 'tanishtirmoq', '/ˌɪntrəˈdjuːs/', 'Let me introduce my friend.'],
  ['involve', 'jalb qilmoq', '/ɪnˈvɒlv/', 'The job involves travel.'],
  ['judge', 'baholamoq', '/dʒʌdʒ/', 'Do not judge people quickly.'],
  ['knowledge (gen)', 'bilim', '/ˈnɒlɪdʒ/', 'Her knowledge is impressive.'],
  ['lack', 'yetishmaslik', '/læk/', 'There is a lack of water.'],
  ['limit', 'cheklamoq', '/ˈlɪmɪt/', 'Limit your screen time.'],
  ['locate', 'joylashtirmoq', '/ləʊˈkeɪt/', 'The office is located downtown.'],
  ['maintain', 'saqlab turmoq', '/meɪnˈteɪn/', 'Maintain a healthy diet.'],
  ['manage', 'boshqarmoq', '/ˈmænɪdʒ/', 'She manages a large team.'],
  ['measure (gen)', 'oʻlchamoq', '/ˈmeʒər/', 'Measure the room first.'],
  ['mention', 'eslatmoq', '/ˈmenʃən/', 'He did not mention the cost.'],
  ['method (gen)', 'usul', '/ˈmeθəd/', 'Try a different method.'],
  ['notice', 'sezmoq', '/ˈnəʊtɪs/', 'I did not notice the sign.'],
  ['obtain', 'qoʻlga kiritmoq', '/əbˈteɪn/', 'You can obtain a visa here.'],
  ['occur', 'sodir boʻlmoq', '/əˈkɜː/', 'The accident occurred at night.'],
  ['offer (gen)', 'taklif qilmoq', '/ˈɒfər/', 'They offered me a job.'],
  ['operate', 'ishlatmoq', '/ˈɒpəreɪt/', 'He can operate the machine.'],
  ['oppose', 'qarshi chiqmoq', '/əˈpəʊz/', 'Many people opposed the law.'],
  ['organise', 'tashkillashtirmoq', '/ˈɔːɡənaɪz/', 'She organised the event.'],
  ['participate', 'qatnashmoq', '/pɑːˈtɪsɪpeɪt/', 'Everyone can participate.'],
  ['perform', 'bajarmoq', '/pəˈfɔːm/', 'The team performed well.'],
  ['permit', 'ruxsat bermoq', '/pəˈmɪt/', 'They do not permit pets.'],
  ['persuade', 'koʻndirmoq', '/pəˈsweɪd/', 'She persuaded him to stay.'],
  ['plan', 'rejalashtirmoq', '/plæn/', 'We plan to travel in summer.'],
  ['predict', 'bashorat qilmoq', '/prɪˈdɪkt/', 'No one can predict the future.'],
  ['prefer', 'afzal koʻrmoq', '/prɪˈfɜː/', 'I prefer tea to coffee.'],
  ['prepare (gen)', 'tayyorlanmoq', '/prɪˈpeər/', 'Prepare for the meeting.'],
  ['prevent', 'oldini olmoq', '/prɪˈvent/', 'Exercise can prevent illness.'],
  ['produce', 'ishlab chiqarmoq', '/prəˈdjuːs/', 'They produce furniture.'],
  ['promote', 'targʻib qilmoq', '/prəˈməʊt/', 'They promote healthy living.'],
  ['propose', 'taklif qilmoq', '/prəˈpəʊz/', 'He proposed a new idea.'],
  ['provide', 'taʼminlamoq', '/prəˈvaɪd/', 'They provide free meals.'],
  ['publish (gen)', 'chop etmoq', '/ˈpʌblɪʃ/', 'She published her first book.'],
  ['purchase', 'sotib olmoq', '/ˈpɜːtʃəs/', 'They purchased a new car.'],
  ['purpose', 'maqsad', '/ˈpɜːpəs/', 'What is the purpose of this?'],
  ['reach', 'yetib bormoq', '/riːtʃ/', 'We reached the top by noon.'],
  ['realise', 'anglamoq', '/ˈrɪəlaɪz/', 'I realised my mistake.'],
  ['receive', 'olmoq', '/rɪˈsiːv/', 'I received your letter.'],
  ['recognise', 'tanimoq', '/ˈrekəɡnaɪz/', 'I did not recognise you.'],
  ['recommend (gen)', 'tavsiya qilmoq', '/ˌrekəˈmend/', 'I recommend this book.'],
  ['reduce', 'kamaytirmoq', '/rɪˈdjuːs/', 'Reduce your sugar intake.'],
  ['refer', 'murojaat qilmoq', '/rɪˈfɜː/', 'Refer to the manual.'],
  ['reflect', 'aks ettirmoq', '/rɪˈflekt/', 'The price reflects the quality.'],
  ['refuse', 'rad etmoq', '/rɪˈfjuːz/', 'She refused the offer.'],
  ['regret', 'afsuslanmoq', '/rɪˈɡret/', 'I regret my decision.'],
  ['relate', 'bogʻlamoq', '/rɪˈleɪt/', 'I cannot relate to this.'],
  ['relax (gen)', 'dam olmoq', '/rɪˈlæks/', 'Try to relax and breathe.'],
  ['release', 'chiqarmoq', '/rɪˈliːs/', 'They released a new album.'],
  ['rely', 'tayanmoq', '/rɪˈlaɪ/', 'You can rely on her.'],
  ['remain', 'qolmoq', '/rɪˈmeɪn/', 'Few people remained.'],
  ['remind', 'eslatmoq', '/rɪˈmaɪnd/', 'Remind me to call him.'],
  ['remove', 'olib tashlamoq', '/rɪˈmuːv/', 'Remove your shoes here.'],
  ['repair (gen)', 'taʼmirlamoq', '/rɪˈpeər/', 'He repaired the roof.'],
  ['replace', 'almashtirmoq', '/rɪˈpleɪs/', 'Replace the broken part.'],
  ['represent (gen)', 'ifodalamoq', '/ˌreprɪˈzent/', 'The flag represents freedom.'],
  ['require', 'talab qilmoq', '/rɪˈkwaɪər/', 'This job requires skill.'],
  ['research (verb)', 'tadqiq qilmoq', '/rɪˈsɜːtʃ/', 'They research new methods.'],
  ['respond', 'javob bermoq', '/rɪˈspɒnd/', 'Please respond quickly.'],
  ['responsible', 'masʼul', '/rɪˈspɒnsəbəl/', 'He is responsible for safety.'],
  ['result (verb)', 'natija bermoq', '/rɪˈzʌlt/', 'Hard work results in success.'],
  ['reveal', 'oshkor qilmoq', '/rɪˈviːl/', 'The study revealed the truth.'],
  ['satisfy', 'qoniqtirmoq', '/ˈsætɪsfaɪ/', 'The result satisfied everyone.'],
  ['seek', 'izlamoq', '/siːk/', 'They seek a better life.'],
  ['select', 'tanlamoq', '/sɪˈlekt/', 'Select the best option.'],
  ['separate', 'ajratmoq', '/ˈsepəreɪt/', 'Separate the items by colour.'],
  ['settle', 'joylashmoq', '/ˈsetəl/', 'They settled in a new town.'],
  ['situation', 'vaziyat', '/ˌsɪtʃuˈeɪʃən/', 'It is a difficult situation.'],
  ['solution', 'yechim', '/səˈluːʃən/', 'We found a good solution.'],
  ['source (gen)', 'manba', '/sɔːs/', 'The sun is a source of energy.'],
  ['specific', 'aniq', '/spəˈsɪfɪk/', 'Be specific in your answer.'],
  ['split', 'boʻlmoq', '/splɪt/', 'Let us split the bill.'],
  ['spread', 'tarqalmoq', '/spred/', 'The news spread quickly.'],
  ['state', 'bayon qilmoq', '/steɪt/', 'Please state your name.'],
  ['struggle', 'kurashmoq', '/ˈstrʌɡəl/', 'They struggle to pay rent.'],
  ['succeed (gen)', 'erishmoq', '/səkˈsiːd/', 'She succeeded in business.'],
  ['suggest', 'taklif qilmoq', '/səˈdʒest/', 'I suggest we leave now.'],
  ['suitable', 'mos', '/ˈsuːtəbəl/', 'Find a suitable time.'],
  ['supply (gen)', 'yetkazib bermoq', '/səˈplaɪ/', 'They supply fresh bread.'],
  ['suppose', 'taxmin qilmoq', '/səˈpəʊz/', 'I suppose you are right.'],
  ['survive', 'omon qolmoq', '/səˈvaɪv/', 'They survived the storm.'],
  ['tend', 'moyil boʻlmoq', '/tend/', 'Prices tend to rise.'],
  ['threaten', 'tahdid qilmoq', '/ˈθretən/', 'Pollution threatens nature.'],
  ['tolerate', 'chidamoq', '/ˈtɒləreɪt/', 'I cannot tolerate rudeness.'],
  ['transfer', 'koʻchirmoq', '/trænsˈfɜː/', 'Transfer the money today.'],
  ['translate', 'tarjima qilmoq', '/trænzˈleɪt/', 'Translate this into English.'],
  ['treat', 'munosabatda boʻlmoq', '/triːt/', 'Treat others with respect.'],
  ['understand (gen)', 'tushunmoq', '/ˌʌndəˈstænd/', 'I understand your problem.'],
  ['value (verb)', 'qadrlamoq', '/ˈvæljuː/', 'I value your honesty.'],
  ['vary', 'oʻzgarmoq', '/ˈveəri/', 'Prices vary by season.'],
  ['view', 'fikr', '/vjuː/', 'In my view, this is wrong.'],
  ['warn', 'ogohlantirmoq', '/wɔːn/', 'They warned us about the storm.'],
  ['waste (verb)', 'isrof qilmoq', '/weɪst/', 'Do not waste your time.'],
  ['accurate', 'aniq', '/ˈækjʊrət/', 'The report is accurate.'],
  ['active', 'faol', '/ˈæktɪv/', 'She leads an active life.'],
  ['actual', 'haqiqiy', '/ˈæktʃuəl/', 'What is the actual cost?'],
  ['aggressive', 'tajovuzkor', '/əˈɡresɪv/', 'The dog was aggressive.'],
  ['ancient', 'qadimiy', '/ˈeɪnʃənt/', 'They found an ancient city.'],
  ['anxious (gen)', 'bezovta', '/ˈæŋkʃəs/', 'He felt anxious before the trip.'],
  ['available', 'mavjud', '/əˈveɪləbəl/', 'The room is available now.'],
  ['average', 'oʻrtacha', '/ˈævərɪdʒ/', 'The average score was high.'],
  ['aware (gen)', 'ogoh', '/əˈweər/', 'Be aware of the dangers.'],
  ['basic', 'asosiy', '/ˈbeɪsɪk/', 'He has basic knowledge.'],
  ['brief (gen)', 'qisqa', '/briːf/', 'Keep your answer brief.'],
  ['capable', 'qodir', '/ˈkeɪpəbəl/', 'She is capable of more.'],
  ['certain', 'aniq', '/ˈsɜːtən/', 'I am certain about it.'],
  ['complex (gen)', 'murakkab', '/ˈkɒmpleks/', 'It is a complex topic.'],
  ['constant', 'doimiy', '/ˈkɒnstənt/', 'There is constant noise here.'],
  ['contemporary', 'zamonaviy', '/kənˈtempərəri/', 'I like contemporary art.'],
  ['crucial', 'hal qiluvchi', '/ˈkruːʃəl/', 'This step is crucial.'],
  ['current', 'joriy', '/ˈkʌrənt/', 'What is the current situation?'],
  ['definite', 'aniq', '/ˈdefɪnət/', 'We need a definite answer.'],
  ['dependent', 'bogʻliq', '/dɪˈpendənt/', 'Children are dependent on parents.'],
  ['detailed', 'batafsil', '/ˈdiːteɪld/', 'She gave a detailed report.'],
  ['efficient (gen)', 'samarali', '/ɪˈfɪʃənt/', 'It is an efficient system.'],
  ['essential', 'zarur', '/ɪˈsenʃəl/', 'Water is essential for life.'],
  ['exact', 'aniq', '/ɪɡˈzækt/', 'Tell me the exact time.'],
  ['extreme', 'haddan tashqari', '/ɪkˈstriːm/', 'It was an extreme case.'],
  ['flexible', 'moslashuvchan', '/ˈfleksəbəl/', 'My schedule is flexible.'],
  ['frequent (gen)', 'tez-tez boʻladigan', '/ˈfriːkwənt/', 'Frequent breaks help focus.'],
  ['general', 'umumiy', '/ˈdʒenərəl/', 'This is general advice.'],
  ['genuine', 'haqiqiy', '/ˈdʒenjuɪn/', 'She has a genuine smile.'],
  ['gradual', 'asta-sekin', '/ˈɡrædʒuəl/', 'There was a gradual change.'],
  ['immediate', 'tezkor', '/ɪˈmiːdiət/', 'We need an immediate answer.'],
  ['independent', 'mustaqil', '/ˌɪndɪˈpendənt/', 'She is financially independent.'],
  ['inevitable', 'muqarrar', '/ɪnˈevɪtəbəl/', 'Change is inevitable.'],
  ['intense', 'kuchli', '/ɪnˈtens/', 'The heat was intense.'],
  ['major', 'asosiy', '/ˈmeɪdʒər/', 'It is a major problem.'],
  ['mature', 'yetuk', '/məˈtʃʊə/', 'He is very mature for his age.'],
  ['minor', 'kichik', '/ˈmaɪnər/', 'It was only a minor issue.'],
  ['multiple', 'koʻp', '/ˈmʌltɪpəl/', 'There are multiple reasons.'],
  ['negative', 'salbiy', '/ˈneɡətɪv/', 'He has a negative attitude.'],
  ['obvious', 'aniq', '/ˈɒbviəs/', 'The answer is obvious.'],
  ['ordinary', 'oddiy', '/ˈɔːdənəri/', 'It was an ordinary day.'],
  ['permanent', 'doimiy', '/ˈpɜːmənənt/', 'He found a permanent job.'],
  ['positive', 'ijobiy', '/ˈpɒzətɪv/', 'Stay positive and calm.'],
  ['potential', 'salohiyat', '/pəˈtenʃəl/', 'She has great potential.'],
  ['previous', 'oldingi', '/ˈpriːviəs/', 'See the previous chapter.'],
  ['primary', 'birlamchi', '/ˈpraɪməri/', 'Safety is our primary goal.'],
  ['rare', 'kam uchraydigan', '/reər/', 'It is a rare disease.'],
  ['recent', 'soʻnggi', '/ˈriːsənt/', 'In recent years, things changed.'],
  ['relevant', 'tegishli', '/ˈreləvənt/', 'Give me relevant facts.'],
  ['reliable (gen)', 'ishonchli', '/rɪˈlaɪəbəl/', 'He is a reliable worker.'],
  ['significant', 'muhim', '/sɪɡˈnɪfɪkənt/', 'It was a significant change.'],
  ['similar', 'oʻxshash', '/ˈsɪmɪlər/', 'These two are similar.'],
  ['stable', 'barqaror', '/ˈsteɪbəl/', 'The economy is stable.'],
  ['standard', 'standart', '/ˈstændəd/', 'It meets the standard.'],
  ['sufficient', 'yetarli', '/səˈfɪʃənt/', 'We have sufficient time.'],
  ['typical', 'odatiy', '/ˈtɪpɪkəl/', 'It was a typical morning.'],
  ['unique', 'noyob', '/juˈniːk/', 'Each person is unique.'],
  ['urgent', 'shoshilinch', '/ˈɜːdʒənt/', 'This is an urgent matter.'],
  ['valuable', 'qimmatli', '/ˈvæljʊəbəl/', 'Your advice is valuable.'],
  ['various', 'turli', '/ˈveəriəs/', 'There are various options.'],
  ['virtual', 'virtual', '/ˈvɜːtʃuəl/', 'We had a virtual meeting.'],
  ['vital', 'hayotiy', '/ˈvaɪtəl/', 'Sleep is vital for health.'],
  ['attempt (verb)', 'urinmoq', '/əˈtempt/', 'He attempted to fix it.'],
  ['benefit (verb)', 'foyda koʻrmoq', '/ˈbenɪfɪt/', 'You will benefit from this.'],
  ['challenge (verb)', 'eʼtiroz bildirmoq', '/ˈtʃælɪndʒ/', 'They challenged the decision.'],
  ['concern (verb)', 'tashvishlantirmoq', '/kənˈsɜːn/', 'The news concerned everyone.'],
  ['contrast', 'qarama-qarshilik', '/ˈkɒntrɑːst/', 'There is a sharp contrast.'],
  ['decline', 'kamayish', '/dɪˈklaɪn/', 'Sales are in decline.'],
  ['demand (noun gen)', 'talab', '/dɪˈmɑːnd/', 'There is high demand for it.'],
  ['emphasis', 'urgʻu', '/ˈemfəsɪs/', 'Put emphasis on accuracy.'],
  ['failure', 'muvaffaqiyatsizlik', '/ˈfeɪljər/', 'Failure teaches us lessons.'],
  ['feature', 'xususiyat', '/ˈfiːtʃər/', 'This phone has a new feature.'],
  ['function (verb)', 'ishlamoq', '/ˈfʌŋkʃən/', 'The machine functions well.'],
  ['growth', 'oʻsish', '/ɡrəʊθ/', 'Economic growth is steady.'],
  ['impact (verb)', 'taʼsir koʻrsatmoq', '/ˈɪmpækt/', 'The law impacts everyone.'],
  ['issue', 'masala', '/ˈɪʃuː/', 'We discussed an important issue.'],
  ['method (noun)', 'metod', '/ˈmeθəd/', 'This method works best.'],
  ['nevertheless', 'shunga qaramay', '/ˌnevəðəˈles/', 'It was hard; nevertheless, we won.'],
  ['outcome', 'natija', '/ˈaʊtkʌm/', 'The outcome was positive.'],
  ['perspective', 'nuqtai nazar', '/pəˈspektɪv/', 'Try a new perspective.'],
  ['principle', 'tamoyil', '/ˈprɪnsəpəl/', 'He acts on strong principles.'],
  ['quality (gen)', 'sifat', '/ˈkwɒləti/', 'Quality matters more than quantity.'],
  ['range', 'doira', '/reɪndʒ/', 'They sell a wide range of goods.'],
  ['response', 'javob', '/rɪˈspɒns/', 'I got a quick response.'],
  ['role', 'rol', '/rəʊl/', 'She plays a key role.'],
  ['strategy', 'strategiya', '/ˈstrætədʒi/', 'We need a clear strategy.'],
  ['trend (gen)', 'oqim', '/trend/', 'It is a worrying trend.'],
  ['variety', 'xilma-xillik', '/vəˈraɪəti/', 'There is a variety of food.'],
  ['version', 'versiya', '/ˈvɜːʃən/', 'This is the latest version.'],
  ['attitude (gen)', 'qarash', '/ˈætɪtjuːd/', 'Change your attitude.'],
  ['circumstance', 'holat', '/ˈsɜːkəmstɑːns/', 'In these circumstances, we wait.'],
  ['consequence', 'oqibat', '/ˈkɒnsɪkwəns/', 'Every action has a consequence.'],
  ['context', 'kontekst', '/ˈkɒntekst/', 'Read the word in context.'],
  ['contribution', 'hissa', '/ˌkɒntrɪˈbjuːʃən/', 'Thank you for your contribution.'],
  ['definition', 'taʼrif', '/ˌdefɪˈnɪʃən/', 'Look up the definition.'],
  ['evaluation (gen)', 'baholash', '/ɪˌvæljuˈeɪʃən/', 'The evaluation was fair.'],
  ['expectation', 'kutilma', '/ˌekspekˈteɪʃən/', 'It met our expectations.'],
  ['explanation', 'tushuntirish', '/ˌekspləˈneɪʃən/', 'Give a clear explanation.'],
  ['factor', 'omil', '/ˈfæktər/', 'Cost is a key factor.'],
  ['interpretation', 'talqin', '/ɪnˌtɜːprɪˈteɪʃən/', 'That is one interpretation.'],
  ['observation', 'kuzatuv', '/ˌɒbzəˈveɪʃən/', 'She made a sharp observation.'],
  ['possibility', 'imkoniyat', '/ˌpɒsəˈbɪləti/', 'There is a possibility of rain.'],
  ['preparation', 'tayyorgarlik', '/ˌprepəˈreɪʃən/', 'Good preparation is the key.'],
  ['proposal', 'taklif', '/prəˈpəʊzəl/', 'They accepted our proposal.'],
  ['reaction', 'reaksiya', '/riˈækʃən/', 'His reaction surprised me.'],
  ['recommendation', 'tavsiya', '/ˌrekəmenˈdeɪʃən/', 'I followed your recommendation.'],
  ['reduction', 'kamaytirish', '/rɪˈdʌkʃən/', 'There was a price reduction.'],
  ['relationship (gen)', 'aloqa', '/rɪˈleɪʃənʃɪp/', 'There is a clear relationship.'],
  ['requirement', 'talab', '/rɪˈkwaɪəmənt/', 'Meet all the requirements.'],
  ['solution (gen)', 'yechim', '/səˈluːʃən/', 'There is no easy solution.'],
  ['statement (gen)', 'bayonot', '/ˈsteɪtmənt/', 'He made a clear statement.'],
  ['suggestion', 'taklif', '/səˈdʒestʃən/', 'That is a good suggestion.'],
  ['tendency', 'moyillik', '/ˈtendənsi/', 'He has a tendency to be late.'],
  // ── More general B1 ──
  ['abandon (b1)', 'tark etmoq', '/əˈbændən/', 'They abandoned the car.'],
  ['absence', 'yoʻqlik', '/ˈæbsəns/', 'Her absence was noticed.'],
  ['absolute', 'mutlaq', '/ˈæbsəluːt/', 'I have absolute trust in her.'],
  ['abstract (b1)', 'mavhum', '/ˈæbstrækt/', 'The idea is too abstract.'],
  ['accent', 'urgʻu, talaffuz', '/ˈæksent/', 'She has a slight accent.'],
  ['accompany (b1)', 'hamroh boʻlmoq', '/əˈkʌmpəni/', 'I will accompany you home.'],
  ['accomplish (b1)', 'bajarmoq', '/əˈkʌmplɪʃ/', 'We accomplished the task.'],
  ['accurate (b1)', 'aniq', '/ˈækjʊrət/', 'The clock is accurate.'],
  ['accuse', 'ayblamoq', '/əˈkjuːz/', 'They accused him of lying.'],
  ['adopt', 'qabul qilmoq', '/əˈdɒpt/', 'They adopted a new rule.'],
  ['advance (b1)', 'ilgarilash', '/ədˈvɑːns/', 'Medical advances save lives.'],
  ['agency', 'agentlik', '/ˈeɪdʒənsi/', 'She works for a travel agency.'],
  ['alarm (b1)', 'xavotir', '/əˈlɑːm/', 'There is no cause for alarm.'],
  ['alter', 'oʻzgartirmoq', '/ˈɔːltər/', 'They altered the schedule.'],
  ['amount (b1)', 'miqdor', '/əˈmaʊnt/', 'A large amount of work remains.'],
  ['annual', 'yillik', '/ˈænjuəl/', 'It is an annual event.'],
  ['apparent (b1)', 'sezilarli', '/əˈpærənt/', 'It became apparent quickly.'],
  ['approach', 'yondashuv', '/əˈprəʊtʃ/', 'We need a new approach.'],
  ['approximately', 'taxminan', '/əˈprɒksɪmətli/', 'It costs approximately ten dollars.'],
  ['argue', 'bahslashmoq', '/ˈɑːɡjuː/', 'They argue about money.'],
  ['arise', 'paydo boʻlmoq', '/əˈraɪz/', 'Problems may arise later.'],
  ['aspect', 'jihat', '/ˈæspekt/', 'Consider every aspect.'],
  ['assemble (b1)', 'yigʻmoq', '/əˈsembəl/', 'They assembled the furniture.'],
  ['associate', 'bogʻlamoq', '/əˈsəʊsieɪt/', 'I associate this song with summer.'],
  ['assure', 'ishontirmoq', '/əˈʃʊə/', 'I assure you it is safe.'],
  ['attach', 'biriktirmoq', '/əˈtætʃ/', 'Attach the file to the email.'],
  ['audience (b1)', 'tinglovchilar', '/ˈɔːdiəns/', 'The audience was silent.'],
  ['authority (b1)', 'vakolat', '/ɔːˈθɒrəti/', 'He has the authority to decide.'],
  ['available (b1)', 'mavjud', '/əˈveɪləbəl/', 'Are the tickets available?'],
  ['awareness', 'xabardorlik', '/əˈweənəs/', 'They raised public awareness.'],
  ['barrier', 'toʻsiq', '/ˈbæriər/', 'Language is a barrier here.'],
  ['basis', 'asos', '/ˈbeɪsɪs/', 'We meet on a weekly basis.'],
  ['bear', 'koʻtarmoq, chidamoq', '/beər/', 'I cannot bear the noise.'],
  ['boundary', 'chegara', '/ˈbaʊndəri/', 'They marked the boundary.'],
  ['campaign (b1)', 'kampaniya', '/kæmˈpeɪn/', 'They ran a health campaign.'],
  ['capacity', 'sigʻim', '/kəˈpæsəti/', 'The hall has a large capacity.'],
  ['category', 'toifa', '/ˈkætəɡəri/', 'It fits into this category.'],
  ['ceremony (b1)', 'marosim', '/ˈserəməni/', 'The ceremony lasted an hour.'],
  ['characteristic', 'xususiyat', '/ˌkærɪktəˈrɪstɪk/', 'It is a key characteristic.'],
  ['circumstances', 'sharoit', '/ˈsɜːkəmstɑːnsɪz/', 'Under the circumstances, we waited.'],
  ['client (b1)', 'mijoz', '/ˈklaɪənt/', 'The client signed the deal.'],
  ['colleague (b1)', 'hamkasb', '/ˈkɒliːɡ/', 'My colleague helped me.'],
  ['comment (b1)', 'izoh', '/ˈkɒment/', 'He made a helpful comment.'],
  ['commission', 'komissiya', '/kəˈmɪʃən/', 'They set up a commission.'],
  ['commit', 'sodir etmoq', '/kəˈmɪt/', 'He committed a serious error.'],
  ['committee', 'qoʻmita', '/kəˈmɪti/', 'The committee met today.'],
  ['compete (b1)', 'raqobatlashmoq', '/kəmˈpiːt/', 'Small firms compete with big ones.'],
  ['component (b1)', 'qism', '/kəmˈpəʊnənt/', 'Each component is tested.'],
  ['concept', 'tushuncha', '/ˈkɒnsept/', 'The concept is simple.'],
  ['conduct', 'oʻtkazmoq', '/kənˈdʌkt/', 'They conduct surveys yearly.'],
  ['confidence', 'ishonch', '/ˈkɒnfɪdəns/', 'She speaks with confidence.'],
  ['consequence (b1)', 'oqibat', '/ˈkɒnsɪkwəns/', 'Face the consequences.'],
  ['considerable (b1)', 'salmoqli', '/kənˈsɪdərəbəl/', 'It saved considerable time.'],
  ['constant (b1)', 'doimiy', '/ˈkɒnstənt/', 'There was constant pressure.'],
  ['construct', 'qurmoq', '/kənˈstrʌkt/', 'They construct bridges.'],
  ['consult', 'maslahatlashmoq', '/kənˈsʌlt/', 'Consult a doctor first.'],
  ['consume', 'isteʼmol qilmoq', '/kənˈsjuːm/', 'We consume too much sugar.'],
  ['contact', 'aloqa qilmoq', '/ˈkɒntækt/', 'Contact me by email.'],
  ['contemporary (b1)', 'zamonaviy', '/kənˈtempərəri/', 'He likes contemporary music.'],
  ['content (b1)', 'mazmun', '/ˈkɒntent/', 'The content was useful.'],
  ['controversy', 'munozara', '/ˈkɒntrəvɜːsi/', 'The plan caused controversy.'],
  ['convenient', 'qulay', '/kənˈviːniənt/', 'Is this time convenient?'],
  ['convention', 'anjuman', '/kənˈvenʃən/', 'They attended the convention.'],
  ['convey', 'yetkazmoq', '/kənˈveɪ/', 'Words convey meaning.'],
  ['core', 'oʻzak', '/kɔː/', 'It is the core of the issue.'],
  ['corporate', 'korporativ', '/ˈkɔːpərət/', 'He works in the corporate world.'],
  ['correspond (b1)', 'mos kelmoq', '/ˌkɒrɪˈspɒnd/', 'The names correspond.'],
  ['credit', 'kredit', '/ˈkredɪt/', 'They bought it on credit.'],
  ['crisis', 'inqiroz', '/ˈkraɪsɪs/', 'The country faced a crisis.'],
  ['criticism', 'tanqid', '/ˈkrɪtɪsɪzəm/', 'She accepted the criticism.'],
  ['cultural', 'madaniy', '/ˈkʌltʃərəl/', 'It is a cultural event.'],
  ['data analysis', 'maʼlumot tahlili', '/ˈdeɪtə əˈnæləsɪs/', 'Data analysis takes time.'],
  ['debate (b1)', 'bahs', '/dɪˈbeɪt/', 'They had a long debate.'],
  ['decade (b1)', 'oʻn yillik', '/ˈdekeɪd/', 'Things changed in a decade.'],
  ['declare', 'eʼlon qilmoq', '/dɪˈkleər/', 'They declared independence.'],
  ['dedicate (b1)', 'bagʻishlamoq', '/ˈdedɪkeɪt/', 'He dedicated the book to her.'],
  ['defeat (b1)', 'magʻlubiyat', '/dɪˈfiːt/', 'It was a painful defeat.'],
  ['defend', 'himoya qilmoq', '/dɪˈfend/', 'They defended their rights.'],
  ['define (b1)', 'aniqlamoq', '/dɪˈfaɪn/', 'Define the term clearly.'],
  ['delay (b1)', 'kechiktirmoq', '/dɪˈleɪ/', 'They delayed the launch.'],
  ['demonstrate (b1)', 'namoyish etmoq', '/ˈdemənstreɪt/', 'Demonstrate how it works.'],
  ['deny (b1)', 'inkor qilmoq', '/dɪˈnaɪ/', 'He denied any wrongdoing.'],
  ['department', 'boʻlim', '/dɪˈpɑːtmənt/', 'She leads the sales department.'],
  ['derive (b1)', 'olmoq', '/dɪˈraɪv/', 'They derive profit from sales.'],
  ['despite', 'qaramasdan', '/dɪˈspaɪt/', 'Despite the rain, we left.'],
  ['detail', 'tafsilot', '/ˈdiːteɪl/', 'Explain it in detail.'],
  ['detect', 'aniqlamoq', '/dɪˈtekt/', 'The sensor detects smoke.'],
  ['determine (b1)', 'belgilamoq', '/dɪˈtɜːmɪn/', 'Cost determines the choice.'],
  ['device (gen b1)', 'qurilma', '/dɪˈvaɪs/', 'It is a clever device.'],
  ['dimension', 'oʻlcham', '/daɪˈmenʃən/', 'It adds a new dimension.'],
  ['diminish (b1)', 'kamaytirmoq', '/dɪˈmɪnɪʃ/', 'The pain diminished slowly.'],
  ['discipline (b1)', 'intizom', '/ˈdɪsəplɪn/', 'Sport teaches discipline.'],
  ['distinct (b1)', 'aniq', '/dɪˈstɪŋkt/', 'There is a distinct smell.'],
  ['distribute', 'tarqatmoq', '/dɪˈstrɪbjuːt/', 'They distribute free food.'],
  ['domestic', 'ichki, mahalliy', '/dəˈmestɪk/', 'It is a domestic flight.'],
  ['dominate', 'hukmronlik qilmoq', '/ˈdɒmɪneɪt/', 'One team dominated the match.'],
  ['dramatic', 'keskin', '/drəˈmætɪk/', 'There was a dramatic change.'],
  ['economy (b1 gen)', 'tejamkorlik', '/ɪˈkɒnəmi/', 'They run the firm with economy.'],
  ['edition', 'nashr', '/ɪˈdɪʃən/', 'This is the latest edition.'],
  ['element (b1)', 'unsur', '/ˈelɪmənt/', 'Trust is a key element.'],
  ['eliminate (b1)', 'yoʻq qilmoq', '/ɪˈlɪmɪneɪt/', 'They eliminated the risk.'],
  ['emerge (b1)', 'paydo boʻlmoq', '/ɪˈmɜːdʒ/', 'A new leader emerged.'],
  ['emphasise', 'urgʻu bermoq', '/ˈemfəsaɪz/', 'She emphasised the deadline.'],
  ['enable', 'imkon bermoq', '/ɪˈneɪbəl/', 'The app enables fast booking.'],
  ['enquiry', 'soʻrov', '/ɪnˈkwaɪəri/', 'I made an enquiry online.'],
  ['enormous (b1)', 'ulkan', '/ɪˈnɔːməs/', 'It was an enormous building.'],
  ['enthusiasm', 'ishtiyoq', '/ɪnˈθjuːziæzəm/', 'She works with enthusiasm.'],
  ['entire', 'butun', '/ɪnˈtaɪər/', 'He read the entire book.'],
  ['equip', 'jihozlamoq', '/ɪˈkwɪp/', 'The lab is well equipped.'],
  ['equivalent (b1)', 'teng', '/ɪˈkwɪvələnt/', 'It is equivalent to a week’s pay.'],
  ['era', 'davr', '/ˈɪərə/', 'It was the start of a new era.'],
  ['establish (b1)', 'tashkil etmoq', '/ɪˈstæblɪʃ/', 'They established a charity.'],
  ['ethic', 'axloq', '/ˈeθɪk/', 'He has a strong work ethic.'],
  ['evaluate (b1)', 'baholamoq', '/ɪˈvæljueɪt/', 'Evaluate the options first.'],
  ['eventually', 'oxir-oqibat', '/ɪˈventʃuəli/', 'Eventually, they agreed.'],
  ['evident (b1)', 'aniq', '/ˈevɪdənt/', 'It was evident she was tired.'],
  ['evolve', 'rivojlanmoq', '/ɪˈvɒlv/', 'Languages evolve over time.'],
  ['exception', 'istisno', '/ɪkˈsepʃən/', 'There is one exception.'],
  ['exclude (b1)', 'chiqarib tashlamoq', '/ɪkˈskluːd/', 'They excluded him from the team.'],
  ['exhibit (b1)', 'koʻrgazma', '/ɪɡˈzɪbɪt/', 'The museum has a new exhibit.'],
  ['expansion', 'kengayish', '/ɪkˈspænʃən/', 'The expansion created jobs.'],
  ['expert', 'mutaxassis', '/ˈekspɜːt/', 'She is a health expert.'],
  ['explicit (b1)', 'aniq', '/ɪkˈsplɪsɪt/', 'He gave explicit instructions.'],
  ['exploit (b1)', 'foydalanmoq', '/ɪkˈsplɔɪt/', 'They exploit cheap labour.'],
  ['expose', 'fosh qilmoq', '/ɪkˈspəʊz/', 'The report exposed the fraud.'],
  ['extension', 'kengaytma', '/ɪkˈstenʃən/', 'I asked for an extension.'],
  ['extensive', 'keng', '/ɪkˈstensɪv/', 'They did extensive research.'],
  ['external', 'tashqi', '/ɪkˈstɜːnəl/', 'There are external factors.'],
  ['facility', 'qulaylik', '/fəˈsɪləti/', 'The gym has good facilities.'],
  ['factor (b1)', 'omil', '/ˈfæktər/', 'Price is the main factor.'],
  ['feature (b1)', 'xususiyat', '/ˈfiːtʃər/', 'The car has a safety feature.'],
  ['federal (b1)', 'federal', '/ˈfedərəl/', 'It is a federal matter.'],
  ['finance (b1)', 'moliyalashtirmoq', '/ˈfaɪnæns/', 'The bank financed the project.'],
  ['flexible (b1)', 'moslashuvchan', '/ˈfleksəbəl/', 'We need a flexible plan.'],
  ['formula', 'formula', '/ˈfɔːmjʊlə/', 'There is no magic formula.'],
  ['foundation', 'asos', '/faʊnˈdeɪʃən/', 'Trust is the foundation.'],
  ['framework (b1)', 'asos', '/ˈfreɪmwɜːk/', 'They built a legal framework.'],
  ['function (b1)', 'vazifa', '/ˈfʌŋkʃən/', 'Each tool has a function.'],
  ['fundamental (b1)', 'asosiy', '/ˌfʌndəˈmentl/', 'It is a fundamental right.'],
  ['gather', 'toʻplamoq', '/ˈɡæðər/', 'They gathered information.'],
  ['generate (b1)', 'hosil qilmoq', '/ˈdʒenəreɪt/', 'Solar panels generate power.'],
  ['globe', 'dunyo', '/ɡləʊb/', 'People travel around the globe.'],
  ['guarantee (b1)', 'kafolat', '/ˌɡærənˈtiː/', 'There is a one-year guarantee.'],
  ['guideline', 'koʻrsatma', '/ˈɡaɪdlaɪn/', 'Follow the safety guidelines.'],
  ['highlight', 'taʼkidlamoq', '/ˈhaɪlaɪt/', 'The report highlights the risks.'],
  ['hire (b1)', 'ijaraga olmoq', '/ˈhaɪər/', 'We hired a car for the trip.'],
  ['impose (b1)', 'joriy etmoq', '/ɪmˈpəʊz/', 'They imposed a fine.'],
  ['impressive', 'taʼsirli', '/ɪmˈpresɪv/', 'It was an impressive result.'],
  ['incident', 'voqea', '/ˈɪnsɪdənt/', 'The incident was reported.'],
  ['incorporate (b1)', 'qoʻshmoq', '/ɪnˈkɔːpəreɪt/', 'They incorporated feedback.'],
  ['index', 'koʻrsatkich', '/ˈɪndeks/', 'The price index rose.'],
  ['indicate (b1)', 'koʻrsatmoq', '/ˈɪndɪkeɪt/', 'The arrow indicates north.'],
  ['individual', 'shaxs', '/ˌɪndɪˈvɪdʒuəl/', 'Each individual is unique.'],
  ['initial', 'dastlabki', '/ɪˈnɪʃəl/', 'The initial plan failed.'],
  ['initiative', 'tashabbus', '/ɪˈnɪʃətɪv/', 'She showed great initiative.'],
  ['innovative (b1)', 'innovatsion', '/ˈɪnəvətɪv/', 'It is an innovative idea.'],
  ['insight (b1)', 'tushuncha', '/ˈɪnsaɪt/', 'The talk gave useful insight.'],
  ['inspect', 'tekshirmoq', '/ɪnˈspekt/', 'They inspect the cars.'],
  ['instance', 'misol', '/ˈɪnstəns/', 'For instance, take water.'],
  ['institute', 'institut', '/ˈɪnstɪtjuːt/', 'He studies at a research institute.'],
  ['instruct', 'koʻrsatma bermoq', '/ɪnˈstrʌkt/', 'She instructed the staff.'],
  ['integrate (b1)', 'birlashtirmoq', '/ˈɪntɪɡreɪt/', 'They integrate new tools.'],
  ['intense (b1)', 'kuchli', '/ɪnˈtens/', 'There was intense pressure.'],
  ['interpret (b1)', 'talqin qilmoq', '/ɪnˈtɜːprɪt/', 'How do we interpret this?'],
  ['investigate', 'tekshirmoq', '/ɪnˈvestɪɡeɪt/', 'Police investigate the case.'],
  ['involve (b1)', 'jalb qilmoq', '/ɪnˈvɒlv/', 'The plan involves risk.'],
  ['isolate', 'ajratmoq', '/ˈaɪsəleɪt/', 'They isolated the patient.'],
  ['justify (b1)', 'asoslamoq', '/ˈdʒʌstɪfaɪ/', 'Justify your answer.'],
  ['label', 'yorliq', '/ˈleɪbəl/', 'Read the label carefully.'],
  ['launch', 'ishga tushirmoq', '/lɔːntʃ/', 'They launched a new product.'],
  ['layer', 'qatlam', '/ˈleɪər/', 'There is a thin layer of dust.'],
  ['legal', 'qonuniy', '/ˈliːɡəl/', 'It is a legal document.'],
  ['legislation', 'qonunchilik', '/ˌledʒɪsˈleɪʃən/', 'New legislation was passed.'],
  ['liberal (b1)', 'erkin', '/ˈlɪbərəl/', 'He has liberal opinions.'],
  ['link (b1)', 'bogʻlanish', '/lɪŋk/', 'There is a clear link.'],
  ['locate (b1)', 'joylashmoq', '/ləʊˈkeɪt/', 'The shop is located here.'],
  ['logic', 'mantiq', '/ˈlɒdʒɪk/', 'Your logic is sound.'],
  ['maintain (b1)', 'taʼminlamoq', '/meɪnˈteɪn/', 'They maintain the roads.'],
  ['margin (b1)', 'chegara', '/ˈmɑːdʒɪn/', 'They won by a small margin.'],
  ['mature (b1)', 'yetilmoq', '/məˈtʃʊə/', 'The fruit matures in autumn.'],
  ['mechanism (b1)', 'mexanizm', '/ˈmekənɪzəm/', 'The locking mechanism failed.'],
  ['mental', 'aqliy', '/ˈmentl/', 'It is a mental challenge.'],
  ['minimum', 'eng kam', '/ˈmɪnɪməm/', 'You need the minimum score.'],
  ['ministry', 'vazirlik', '/ˈmɪnɪstri/', 'The ministry made a statement.'],
  ['modify (b1)', 'oʻzgartirmoq', '/ˈmɒdɪfaɪ/', 'They modified the rules.'],
  ['monitor', 'kuzatmoq', '/ˈmɒnɪtər/', 'Doctors monitor his health.'],
  ['motive', 'sabab', '/ˈməʊtɪv/', 'What was his motive?'],
  ['network (b1)', 'tarmoq', '/ˈnetwɜːk/', 'She has a wide network.'],
  ['neutral', 'betaraf', '/ˈnjuːtrəl/', 'He stayed neutral in the debate.'],
  ['nevertheless (b1)', 'shunga qaramay', '/ˌnevəðəˈles/', 'It was hard; nevertheless, we won.'],
  ['norm (b1)', 'meʼyor', '/nɔːm/', 'It is the social norm.'],
  ['objective (b1)', 'maqsad', '/əbˈdʒektɪv/', 'Our objective is clear.'],
  ['obtain (b1)', 'olmoq', '/əbˈteɪn/', 'You can obtain a permit here.'],
  ['obvious (b1)', 'ravshan', '/ˈɒbviəs/', 'The solution is obvious.'],
  ['occupy', 'egallamoq', '/ˈɒkjʊpaɪ/', 'The seat is occupied.'],
  ['option', 'variant', '/ˈɒpʃən/', 'You have two options.'],
  ['orientation (b1)', 'yoʻnalish', '/ˌɔːriənˈteɪʃən/', 'New staff get orientation.'],
  ['outcome (b1)', 'natija', '/ˈaʊtkʌm/', 'The outcome was good.'],
  ['overall', 'umumiy', '/ˌəʊvərˈɔːl/', 'Overall, it was a success.'],
  ['panel', 'hayʼat', '/ˈpænəl/', 'A panel judged the contest.'],
  ['participation', 'ishtirok', '/pɑːˌtɪsɪˈpeɪʃən/', 'Participation is required.'],
  ['perceive (b1)', 'idrok qilmoq', '/pəˈsiːv/', 'We perceive colours differently.'],
  ['percentage', 'foiz', '/pəˈsentɪdʒ/', 'A high percentage agreed.'],
  ['period (b1)', 'davr', '/ˈpɪəriəd/', 'It was a difficult period.'],
  ['phase (b1)', 'bosqich', '/feɪz/', 'We are in the first phase.'],
  ['phenomenon (b1)', 'hodisa', '/fəˈnɒmɪnən/', 'It is a strange phenomenon.'],
  ['philosophy', 'falsafa', '/fɪˈlɒsəfi/', 'He studies philosophy.'],
  ['policy (b1)', 'siyosat', '/ˈpɒləsi/', 'It is company policy.'],
  ['portion', 'qism', '/ˈpɔːʃən/', 'A portion of the money was lost.'],
  ['potential (b1)', 'imkoniyat', '/pəˈtenʃəl/', 'This idea has potential.'],
  ['precise (b1)', 'aniq', '/prɪˈsaɪs/', 'Give a precise figure.'],
  ['predict (b1)', 'bashorat qilmoq', '/prɪˈdɪkt/', 'No one can predict it.'],
  ['previous (b1)', 'oldingi', '/ˈpriːviəs/', 'See the previous example.'],
  ['principle (b1)', 'tamoyil', '/ˈprɪnsəpəl/', 'It is a basic principle.'],
  ['priority', 'ustuvorlik', '/praɪˈɒrəti/', 'Health is my priority.'],
  ['procedure', 'tartib', '/prəˈsiːdʒər/', 'Follow the safety procedure.'],
  ['proceed', 'davom etmoq', '/prəˈsiːd/', 'Please proceed to the gate.'],
  ['profile', 'profil', '/ˈprəʊfaɪl/', 'Update your online profile.'],
  ['project (verb)', 'bashorat qilmoq', '/prəˈdʒekt/', 'They project higher sales.'],
  ['promote (b1)', 'targʻib qilmoq', '/prəˈməʊt/', 'They promote recycling.'],
  ['proportion (b1)', 'nisbat', '/prəˈpɔːʃən/', 'A small proportion failed.'],
  ['prospect', 'istiqbol', '/ˈprɒspekt/', 'There are good job prospects.'],
  ['publication', 'nashr', '/ˌpʌblɪˈkeɪʃən/', 'It is a weekly publication.'],
  ['pursue', 'intilmoq', '/pəˈsjuː/', 'She pursued a career in law.'],
  ['quote', 'iqtibos keltirmoq', '/kwəʊt/', 'He quoted a famous writer.'],
  ['range (b1)', 'diapazon', '/reɪndʒ/', 'They sell a wide range.'],
  ['ratio', 'nisbat', '/ˈreɪʃiəʊ/', 'The ratio is two to one.'],
  ['recall', 'eslamoq', '/rɪˈkɔːl/', 'I cannot recall his name.'],
  ['recover (b1)', 'tiklanmoq', '/rɪˈkʌvər/', 'The economy recovered.'],
  ['regional', 'mintaqaviy', '/ˈriːdʒənəl/', 'It is a regional problem.'],
  ['register', 'roʻyxatdan oʻtmoq', '/ˈredʒɪstər/', 'Register before the event.'],
  ['regulate', 'tartibga solmoq', '/ˈreɡjʊleɪt/', 'They regulate the market.'],
  ['reinforce (b1)', 'kuchaytirmoq', '/ˌriːɪnˈfɔːs/', 'Practice reinforces learning.'],
  ['reject', 'rad etmoq', '/rɪˈdʒekt/', 'They rejected the offer.'],
  ['relevant (b1)', 'tegishli', '/ˈreləvənt/', 'Provide relevant details.'],
  ['reluctant (b1)', 'istamay', '/rɪˈlʌktənt/', 'She was reluctant to leave.'],
  ['remarkable (b1)', 'ajoyib', '/rɪˈmɑːkəbəl/', 'It was a remarkable story.'],
  ['render (b1)', 'koʻrsatmoq', '/ˈrendər/', 'They render free help.'],
  ['resolve', 'hal qilmoq', '/rɪˈzɒlv/', 'They resolved the dispute.'],
  ['restore', 'tiklamoq', '/rɪˈstɔː/', 'They restored the old building.'],
  ['restrict (b1)', 'cheklamoq', '/rɪˈstrɪkt/', 'They restrict entry.'],
  ['retain (b1)', 'saqlab qolmoq', '/rɪˈteɪn/', 'The firm retains its staff.'],
  ['reveal (b1)', 'oshkor qilmoq', '/rɪˈviːl/', 'The test revealed the cause.'],
  ['scheme', 'reja', '/skiːm/', 'They launched a savings scheme.'],
  ['scope (b1)', 'doira', '/skəʊp/', 'The scope is limited.'],
  ['secure', 'xavfsiz', '/sɪˈkjʊə/', 'The data is secure.'],
  ['sector', 'tarmoq', '/ˈsektər/', 'The public sector is large.'],
  ['seek (b1)', 'izlamoq', '/siːk/', 'They seek new markets.'],
  ['sequence', 'ketma-ketlik', '/ˈsiːkwəns/', 'Follow the correct sequence.'],
  ['shift (b1)', 'oʻzgarish', '/ʃɪft/', 'There was a shift in opinion.'],
  ['significance', 'ahamiyat', '/sɪɡˈnɪfɪkəns/', 'I see the significance now.'],
  ['so-called', 'deb atalmish', '/ˌsəʊ ˈkɔːld/', 'The so-called expert was wrong.'],
  ['sole', 'yagona', '/səʊl/', 'She is the sole owner.'],
  ['somewhat (b1)', 'birmuncha', '/ˈsʌmwɒt/', 'It was somewhat difficult.'],
  ['specify', 'aniq belgilamoq', '/ˈspesɪfaɪ/', 'Specify the exact date.'],
  ['sphere', 'soha', '/sfɪə/', 'It is outside my sphere.'],
  ['stable (b1)', 'barqaror', '/ˈsteɪbəl/', 'Prices remained stable.'],
  ['statistics', 'statistika', '/stəˈtɪstɪks/', 'The statistics are worrying.'],
  ['status (b1)', 'holat', '/ˈsteɪtəs/', 'Check your application status.'],
  ['straightforward', 'sodda', '/ˌstreɪtˈfɔːwəd/', 'The task is straightforward.'],
  ['strategy (b1)', 'strategiya', '/ˈstrætədʒi/', 'They changed their strategy.'],
  ['stress (b1)', 'taʼkidlamoq', '/stres/', 'She stressed the main point.'],
  ['structure (b1)', 'tuzilma', '/ˈstrʌktʃər/', 'The structure is solid.'],
  ['submit (b1)', 'topshirmoq', '/səbˈmɪt/', 'Submit the report today.'],
  ['subsequent (b1)', 'keyingi', '/ˈsʌbsɪkwənt/', 'Subsequent events proved it.'],
  ['substitute (b1)', 'oʻrnini bosmoq', '/ˈsʌbstɪtjuːt/', 'Use honey as a substitute.'],
  ['sufficient (b1)', 'yetarli', '/səˈfɪʃənt/', 'We have sufficient funds.'],
  ['summary', 'xulosa', '/ˈsʌməri/', 'Write a short summary.'],
  ['supplement (b1)', 'qoʻshimcha', '/ˈsʌplɪment/', 'It is a useful supplement.'],
  ['survey', 'soʻrov', '/ˈsɜːveɪ/', 'They conducted a survey.'],
  ['suspend', 'toʻxtatib turmoq', '/səˈspend/', 'They suspended the service.'],
  ['sustain (b1)', 'qoʻllab turmoq', '/səˈsteɪn/', 'They cannot sustain the pace.'],
  ['symbol', 'ramz', '/ˈsɪmbəl/', 'The dove is a symbol of peace.'],
  ['target', 'maqsad', '/ˈtɑːɡɪt/', 'We reached our sales target.'],
  ['technical', 'texnik', '/ˈteknɪkəl/', 'It is a technical problem.'],
  ['tense', 'tarang', '/tens/', 'The atmosphere was tense.'],
  ['terminate (b1)', 'tugatmoq', '/ˈtɜːmɪneɪt/', 'They terminated the contract.'],
  ['theme', 'mavzu', '/θiːm/', 'The theme of the book is hope.'],
  ['thereby (b1)', 'shu tariqa', '/ˌðeəˈbaɪ/', 'It cuts costs, thereby saving money.'],
  ['thesis (b1)', 'dissertatsiya', '/ˈθiːsɪs/', 'She wrote her thesis.'],
  ['transform', 'oʻzgartirmoq', '/trænsˈfɔːm/', 'The city was transformed.'],
  ['transition (b1)', 'oʻtish', '/trænˈzɪʃən/', 'The transition went well.'],
  ['transmit (b1)', 'uzatmoq', '/trænzˈmɪt/', 'The signal is transmitted live.'],
  ['transport (verb)', 'tashimoq', '/trænˈspɔːt/', 'They transport goods by sea.'],
  ['trigger', 'qoʻzgʻatmoq', '/ˈtrɪɡər/', 'Stress can trigger headaches.'],
  ['ultimate', 'pirovard', '/ˈʌltɪmət/', 'It is the ultimate goal.'],
  ['undergo', 'boshdan kechirmoq', '/ˌʌndəˈɡəʊ/', 'He underwent surgery.'],
  ['underlying (b1)', 'asosiy', '/ˌʌndəˈlaɪɪŋ/', 'Find the underlying reason.'],
  ['undertake (b1)', 'zimmasiga olmoq', '/ˌʌndəˈteɪk/', 'They undertook the project.'],
  ['utilise (b1)', 'foydalanmoq', '/ˈjuːtɪlaɪz/', 'They utilise free tools.'],
  ['valid (b1)', 'haqiqiy', '/ˈvælɪd/', 'The ticket is still valid.'],
  ['version (b1)', 'versiya', '/ˈvɜːʃən/', 'This is an older version.'],
  ['via', 'orqali', '/ˈvaɪə/', 'We flew via Dubai.'],
  ['violate', 'buzmoq', '/ˈvaɪəleɪt/', 'They violated the rules.'],
  ['virtually (b1)', 'deyarli', '/ˈvɜːtʃuəli/', 'It is virtually free.'],
  ['visible', 'koʻrinadigan', '/ˈvɪzəbəl/', 'The stars are visible tonight.'],
  ['vision', 'tasavvur', '/ˈvɪʒən/', 'She has a clear vision.'],
  ['voluntary', 'ixtiyoriy', '/ˈvɒləntəri/', 'It is voluntary work.'],
  ['welfare', 'farovonlik', '/ˈwelfeə/', 'They care about staff welfare.'],
  ['whereas (b1)', 'holbuki', '/weərˈæz/', 'He likes tea, whereas I like coffee.'],
  ['widespread (b1)', 'keng tarqalgan', '/ˈwaɪdspred/', 'There was widespread damage.'],
]

