# -*- coding: utf-8 -*-
"""
Add interleaved practice to all A2 and B2 daily lessons.
Generates exercises programmatically to avoid string escaping issues.
"""
import re, json

# ═══════════════════════════════════════════════════════════════════════════
# Exercise templates per lesson
# ═══════════════════════════════════════════════════════════════════════════

def make_exercises(lesson_id, start_id):
    """Generate 5 interleaved exercises for a lesson. Returns exercise text."""
    
    # Template-based exercise generator
    templates = {
        # ── A2 Part 1 ──
        'modalVerbs': [
            ('multiple-choice', 
             'Modal verbs vs Present Simple (ability vs habit):',
             'I _____ swim very well. I _____ in the pool every weekend.',
             ['can / swim', 'could / am swimming', 'must / swam', 'might / will swim'],
             'can / swim',
             '"Can swim" = ability (modal). "Swim every weekend" = habit (Present Simple).'),
            ('fill-blank', 
             'Must (obligation) vs can (permission):',
             'You _____ wear a uniform at school. You _____ wear casual clothes on Fridays.',
             ['must', 'can'],
             '"Must" = obligation. "Can" = permission. Bir xil kontekst, turli modal features.'),
            ('error-correction',
             'Can vs To be able to (present vs future):',
             'I can to speak English. I will can help you tomorrow.',
             'can to',
             'I can speak English. I will be able to help you tomorrow.',
             '"Can" + V1 (no to). Future = "will be able to", not "will can".'),
            ('fill-blank',
             'Can (ability) vs Present Continuous (now):',
             'I _____ (speak) three languages. Right now, I _____ (speak) English.',
             ['can speak', 'am speaking'],
             '"Can speak" = general ability. "Am speaking" = right now.'),
            ('transformation',
             'Present Simple -> Modal bilan ifodalang:',
             'It is necessary for you to finish this today. (use: must)',
             'You must finish this today.',
             '"It is necessary" -> "must". Modal feel bilan qisqa va aniq ifoda.'),
        ],
        'articles': [
            ('multiple-choice',
             'A/an vs The (first mention vs specific):',
             'I saw _____ dog in the park. _____ dog was very friendly.',
             ['a / The', 'the / A', 'an / The', 'the / The'],
             'a / The',
             '"A dog" = first mention. "The dog" = second mention.'),
            ('fill-blank',
             'A/an vs No article (general vs specific):',
             'I love _____ music. I bought _____ new guitar yesterday.',
             ['-', 'a'],
             '"Music" = general (no article). "A guitar" = one specific item.'),
            ('error-correction',
             'The vs zero article (general statement):',
             'The dogs are loyal animals. The life is beautiful.',
             'The dogs',
             'Dogs are loyal animals. Life is beautiful.',
             'General statements = no article (Dogs, Life).'),
            ('fill-blank',
             'Article + Adjective + Noun combination:',
             'She is _____ honest woman. She has _____ very kind heart.',
             ['an', 'a'],
             '"Honest" starts with vowel sound -> "an". "Very kind heart" -> "a".'),
            ('transformation',
             'Add articles to the sentence:',
             'I want to buy car and house. (add: a/an/the where needed)',
             'I want to buy a car and a house.',
             'First mention of countable nouns -> "a".'),
        ],
        'prepositions': [
            ('multiple-choice',
             'In/On/At (time) vs In/On/At (place):',
             'I was born _____ 1999. I live _____ Tashkent. See you _____ Monday.',
             ['in / in / on', 'on / at / in', 'at / in / on', 'in / at / at'],
             'in / in / on',
             '"In 1999" (year), "in Tashkent" (city), "on Monday" (day).'),
            ('fill-blank',
             'Prepositions after verbs (depend on vs wait for):',
             'It depends _____ the weather. I am waiting _____ my friend.',
             ['on', 'for'],
             '"Depend on" = boliq. "Wait for" = kutmoq.'),
            ('error-correction',
             'Preposition at the end of question:',
             'Who are you waiting for? Where do you come from?',
             'come from',
             'Where are you from? (fixed phrase).'),
            ('fill-blank',
             'Prepositions of movement (to/into/onto):',
             'She walked _____ the room. He jumped _____ the table.',
             ['into', 'onto'],
             '"Into" = ichiga. "Onto" = ustiga.'),
            ('transformation',
             'Change prepositions to change meaning:',
             'He ran in the park. (change to: He entered the park)',
             'He ran into the park.',
             '"In" = location. "Into" = movement.'),
        ],
        'questionsLesson': [
            ('multiple-choice',
             'Yes/No vs Wh- questions:',
             '_____ you like coffee? _____ do you like?',
             ['Do / What', 'Are / What', 'Do / Who', 'Is / Where'],
             'Do / What',
             '"Do you like" = Yes/No. "What do you like" = Wh-question.'),
            ('fill-blank',
             'Subject vs Object questions:',
             '_____ lives here? (subject) _____ does she live? (object)',
             ['Who', 'Where'],
             'Subject: no auxiliary. Object: auxiliary + subject.'),
            ('error-correction',
             'Question word order error:',
             'What you want? Where is the station?',
             'What you want',
             'Wh-question needs auxiliary: What DO you want.'),
            ('fill-blank',
             'Present Simple vs Past Simple questions:',
             '_____ you like the film? _____ you go yesterday?',
             ['Do', 'Did'],
             'Present -> Do/Does. Past -> Did.'),
            ('transformation',
             'Statement -> Question:',
             'She lives in Tashkent. (make a question)',
             'Where does she live?',
             'Statement (She lives) -> Question (Where does she live).'),
        ],
        'countableUncountable': [
            ('multiple-choice',
             'Much vs Many vs A lot of:',
             'I don\'t have _____ money. She has _____ friends. There are _____ people here.',
             ['much / many / a lot of', 'many / much / a lot of', 'a lot of / many / much', 'much / a lot of / many'],
             'much / many / a lot of',
             '"Money" (uncountable) -> much. "Friends" (count) -> many. "People" (plural) -> a lot of.'),
            ('fill-blank',
             'Some vs Any vs No:',
             'I have _____ questions. Do you have _____ free time? There is _____ milk left.',
             ['some', 'any', 'no'],
             'Positive -> some. Question/negative -> any. Zero -> no.'),
            ('error-correction',
             'Countable/Uncountable noun error:',
             'I need informations. She gave me an advice.',
             'informations',
             'Information and advice are uncountable. No plural -s.'),
            ('fill-blank',
             'Quantifier + noun agreement:',
             'There are _____ (a few / a little) apples. There is _____ (a few / a little) water.',
             ['a few', 'a little'],
             '"Apples" (countable) -> a few. "Water" (uncountable) -> a little.'),
            ('transformation',
             'Change quantifier to change meaning:',
             'There is some milk. (change to: zero milk)',
             'There is no milk.',
             '"Some" -> "no". Quantifier changes meaning entirely.'),
        ],

        # ── A2 Part 2 ──
        'adjectiveAdverb': [
            ('multiple-choice',
             'Adjective vs Adverb (describe noun vs verb):',
             'She is a _____ singer. She sings _____.',
             ['good / well', 'well / good', 'good / good', 'well / well'],
             'good / well',
             '"Good singer" = adj + noun. "Sings well" = verb + adverb.'),
            ('fill-blank',
             'Adjective after linking verb vs adverb after action verb:',
             'You look _____ (beautiful/beautifully) today. She speaks _____ (soft/softly).',
             ['beautiful', 'softly'],
             '"Look" = linking verb + adjective. "Speaks" = action verb + adverb.'),
            ('error-correction',
             'Adjective/Adverb confusion:',
             'He drives careful. She sings beautiful.',
             'careful',
             'Action verbs take adverbs (-ly). "Carefully" not "careful".'),
            ('fill-blank',
             'Comparative adjectives vs Adverbs:',
             'He is _____ (taller/more tall) than me. He runs _____ (faster/more fast) than me.',
             ['taller', 'faster'],
             'Short adjectives/adverbs: -er.'),
            ('transformation',
             'Adjective -> Adverb:',
             'She is a quiet student. (change: describes how she studies)',
             'She studies quietly.',
             '"Quiet student" (adj + noun) -> "studies quietly" (verb + adv).'),
        ],
        'gerundsInfinitives': [
            ('multiple-choice',
             'Verb + -ing vs Verb + to-infinitive:',
             'I enjoy _____ books. I want _____ a writer.',
             ['reading / to become', 'to read / becoming', 'read / become', 'reading / becoming'],
             'reading / to become',
             '"Enjoy + -ing", "Want + to-infinitive".'),
            ('fill-blank',
             'Remember + -ing vs Remember + to:',
             'I remember _____ (meet) her before. Please remember _____ (lock) the door.',
             ['meeting', 'to lock'],
             '"Remember meeting" = past memory. "Remember to lock" = future task.'),
            ('error-correction',
             'Stop + -ing vs Stop + to:',
             'I stopped to smoke because it is bad for health.',
             'to smoke',
             'I stopped smoking because it is bad for health.',
             '"Stop smoking" = quit. "Stop to rest" = pause for purpose.'),
            ('fill-blank',
             'Like + -ing (enjoy) vs Would like + to (want):',
             'I like _____ (swim). I would like _____ (swim) now.',
             ['swimming', 'to swim'],
             '"Like swimming" = general. "Would like to swim" = specific desire now.'),
            ('transformation',
             '-ing -> to-infinitive (meaning change):',
             'He stopped talking. (change to: He stopped in order to talk)',
             'He stopped to talk.',
             '"Stopped talking" = ceased. "Stopped to talk" = paused.'),
        ],
        'passiveVoice': [
            ('multiple-choice',
             'Active vs Passive voice:',
             'The chef _____ the meal. The meal _____ by the chef.',
             ['cooked / was cooked', 'was cooked / cooked', 'cooks / is cook', 'is cooking / was cooking'],
             'cooked / was cooked',
             'Active (chef cooked) vs Passive (meal was cooked).'),
            ('fill-blank',
             'Present Simple vs Past Simple passive:',
             'English _____ (speak) all over the world. This bridge _____ (build) in 1990.',
             ['is spoken', 'was built'],
             'Present passive: is/are + V3. Past passive: was/were + V3.'),
            ('error-correction',
             'Passive with by + agent:',
             'The window was broke by the boy. The cake was made my mother.',
             'broke',
             'The window was broken by the boy. The cake was made by my mother.',
             'Passive = be + V3 (was broken). Agent -> "by".'),
            ('fill-blank',
             'Active -> Passive (change subject/object):',
             'Someone stole my phone. (passive) My phone _____ _____.',
             ['was stolen'],
             'Active object -> Passive subject.'),
            ('transformation',
             'Active -> Passive voice:',
             'Shakespeare wrote Hamlet. (change to passive)',
             'Hamlet was written by Shakespeare.',
             'Active (Shakespeare wrote) -> Passive (was written by).'),
        ],
        'reportedSpeech': [
            ('multiple-choice',
             'Direct vs Reported speech:',
             'She said: "I like coffee." She said that she _____ coffee.',
             ['liked', 'likes', 'is liking', 'has liked'],
             'liked',
             'Direct (like) -> Reported (liked). Backshift.'),
            ('fill-blank',
             'Reported speech: verb tense backshift:',
             'He said: "I will come." He said that he _____ come. "I am tired" -> He said he _____ tired.',
             ['would', 'was'],
             '"Will" -> "would". "Am" -> "was".'),
            ('error-correction',
             'Reported question word order:',
             'She asked where do I live. He asked what is my name.',
             'where do I live',
             'She asked where I lived. He asked what my name was.',
             'Reported questions = statement order.'),
            ('fill-blank',
             'Reported commands (tell + to-infinitive):',
             'He said: "Sit down!" He told me _____ _____.',
             ['to sit down'],
             'Direct command -> told me to + V1.'),
            ('transformation',
             'Direct -> Reported speech:',
             '"I have finished my homework," she said.',
             'She said that she had finished her homework.',
             '"Have finished" -> "had finished". Backshift.'),
        ],
        'firstConditional': [
            ('multiple-choice',
             'Zero vs First conditional:',
             'If you _____ water, it boils. If it _____ tomorrow, we will cancel.',
             ['heat / rains', 'will heat / will rain', 'heated / rained', 'are heating / is raining'],
             'heat / rains',
             'Zero = general truth. First = real future.'),
            ('fill-blank',
             'First conditional vs Time clause (when):',
             'If it _____ (rain), I will stay home. When I _____ (get) home, I will call you.',
             ['rains', 'get'],
             'Both use Present Simple in if/when clause.'),
            ('error-correction',
             'Future tense in if-clause (wrong):',
             'If it will rain tomorrow, I will stay home.',
             'will rain',
             'If it rains tomorrow, I will stay home.',
             'If/when clauses: Present Simple, NOT will.'),
            ('fill-blank',
             'Unless = If + not:',
             'I will go, if it doesn\'t rain. = I will go _____ it _____.',
             ['unless it rains'],
             '"If not" -> "unless". Same meaning.'),
            ('transformation',
             'First -> Second conditional (change meaning):',
             'If it rains, I will stay home. (change to: unreal/impossible)',
             'If it rained, I would stay home.',
             'First (real) -> Second (unreal).'),
        ],

        # ── A2 Part 3 ──
        'verbPatterns': [
            ('multiple-choice',
             'Verb + infinitive vs Verb + -ing:',
             'I decided _____ a new job. I avoid _____ fast food.',
             ['to take / eating', 'taking / to eat', 'to take / to eat', 'take / eat'],
             'to take / eating',
             '"Decide + to", "Avoid + -ing".'),
            ('fill-blank',
             'Verb + preposition + -ing:',
             'I am interested _____ (learn) English. She is good _____ (play) tennis.',
             ['in learning', 'at playing'],
             '"Interested in + -ing", "Good at + -ing".'),
            ('error-correction',
             'Verb + to vs Verb + -ing pattern:',
             'I enjoy to play football. She suggested to go there.',
             'to play',
             'I enjoy playing football. She suggested going there.',
             '"Enjoy + -ing", "Suggest + -ing".'),
            ('fill-blank',
             'Let vs Make (causative patterns):',
             'My parents let me _____ (stay) up late. My teacher made me _____ (do) the homework again.',
             ['stay', 'do'],
             '"Let + V1", "Make + V1". Both without to.'),
            ('transformation',
             'Verb pattern change (same meaning):',
             'He started to work here. (change to: -ing form)',
             'He started working here.',
             '"Started to work" = "started working".'),
        ],
        'timePrepositions': [
            ('multiple-choice',
             'In/On/At (time) vs In/On/At (place):',
             'The meeting is _____ 3 PM. It is _____ Monday. We are _____ room 5.',
             ['at / on / in', 'in / at / on', 'on / in / at', 'at / in / on'],
             'at / on / in',
             '"At 3 PM" (time), "On Monday" (day), "In room 5" (place).'),
            ('fill-blank',
             'For vs Since (duration vs starting point):',
             'I have lived here _____ 5 years. I have lived here _____ 2020.',
             ['for', 'since'],
             '"For + duration", "Since + starting point".'),
            ('error-correction',
             'During vs For vs While:',
             'I slept during three hours. I fell asleep for the movie.',
             'during three hours',
             'I slept for three hours. I fell asleep during the movie.',
             '"For + duration", "During + event".'),
            ('fill-blank',
             'Until vs By (deadline vs continuous):',
             'I will wait _____ you arrive. Please finish _____ 5 PM.',
             ['until', 'by'],
             '"Until" = continuous. "By" = deadline.'),
            ('transformation',
             'Change time preposition to change meaning:',
             'I will be there in 5 minutes. (change to: I need any time before 5 min)',
             'I will be there within 5 minutes.',
             '"In 5 min" = after. "Within 5 min" = before.'),
        ],
        'thereIsThereAre': [
            ('multiple-choice',
             'There is vs There are (singular vs plural):',
             '_____ a book on the table. _____ many students in the class.',
             ['There is / There are', 'There are / There is', 'It is / They are', 'This is / Those are'],
             'There is / There are',
             '"There is + singular", "There are + plural".'),
            ('fill-blank',
             'There is/are vs It is (existential vs specific):',
             '_____ a big park in the city. _____ very beautiful.',
             ['There is', 'It is'],
             '"There is" = existence. "It is" = describing.'),
            ('error-correction',
             'There is vs There are (agreement):',
             'There is many problems. There are a book on the shelf.',
             'There is many',
             'There are many problems. There is a book on the shelf.',
             'Subject-verb agreement with there is/are.'),
            ('fill-blank',
             'There was/were (past) vs There is/are (present):',
             'Last year, there _____ a festival. Now, there _____ more people.',
             ['was', 'are'],
             '"Last year" (past) -> there was.'),
            ('transformation',
             'There is/are -> There was/were (change time):',
             'There are many people here now. (change to: last year)',
             'Last year, there were many people here.',
             'Present -> Past.'),
        ],
        'possessives': [
            ('multiple-choice',
             'Possessive adjective vs possessive pronoun:',
             'This is _____ book. The book is _____.',
             ['my / mine', 'mine / my', 'me / my', 'I / mine'],
             'my / mine',
             '"My" = adj + noun. "Mine" = pronoun (no noun).'),
            ('fill-blank',
             'Possessive vs Plural -s:',
             'The _____ (students/student\'s) books are on the table. The _____ (students/student\'s) are studying.',
             ['students\'', 'students'],
             '"Students\' books" = possession. "Students are studying" = plural.'),
            ('error-correction',
             'Its vs It\'s (possessive vs contraction):',
             'The dog wagged it\'s tail. Its a beautiful day.',
             'it\'s tail',
             'The dog wagged its tail. It\'s a beautiful day.',
             '"Its" = possessive. "It\'s" = it is.'),
            ('fill-blank',
             'Whose vs Who\'s (possessive vs contraction):',
             '_____ book is this? _____ your teacher?',
             ['Whose', 'Who\'s'],
             '"Whose" = possession. "Who\'s" = who is.'),
            ('transformation',
             'Possessive adjective -> Possessive pronoun:',
             'This is my phone. (change using: mine)',
             'This phone is mine.',
             '"My phone" (adj + noun) -> "is mine" (pronoun).'),
        ],
        'someAnyNoEvery': [
            ('multiple-choice',
             'Some vs Any (positive vs negative):',
             'I have _____ money. I don\'t have _____ time.',
             ['some / any', 'any / some', 'no / some', 'some / no'],
             'some / any',
             'Positive -> some. Negative -> any.'),
            ('fill-blank',
             'Something vs Anything vs Nothing:',
             'I heard _____ but I\'m not sure. I heard _____ at all.',
             ['something', 'nothing'],
             '"Something" = exists. "Nothing" = zero.'),
            ('error-correction',
             'Double negative error:',
             'I didn\'t see nobody. She doesn\'t want nothing.',
             'nobody',
             'I didn\'t see anybody. She doesn\'t want anything.',
             'English does NOT use double negatives.'),
            ('fill-blank',
             'Everybody vs Everything vs Everywhere:',
             '_____ in the room was happy. _____ was clean.',
             ['Everybody', 'Everything'],
             '"Everybody" = people. "Everything" = things.'),
            ('transformation',
             'Some/any -> No compound (change meaning):',
             'There is somebody in the room. (change to: nobody)',
             'There is nobody in the room.',
             '"Somebody" -> "nobody". Opposite meaning.'),
        ],

        # ── A2 Part 4 ──
        'presentContinuousFuture': [
            ('multiple-choice',
             'Present Continuous (now) vs Present Continuous (future):',
             'I _____ a movie right now. I _____ a movie tomorrow evening.',
             ['am watching / am watching', 'watch / am watching', 'am watching / watch', 'watch / watch'],
             'am watching / am watching',
             'Same form, different time. Context matters.'),
            ('fill-blank',
             'Present Continuous (future) vs Be going to:',
             'I _____ (meet) my friends tonight (arrangement). It _____ (rain) (prediction).',
             ['am meeting', 'is going to rain'],
             '"Am meeting" = arrangement. "Is going to rain" = prediction.'),
            ('error-correction',
             'Future time expression with wrong tense:',
             'I am going to the cinema yesterday.',
             'yesterday',
             'I am going to the cinema tomorrow.',
             'Future arrangement + future time marker.'),
            ('fill-blank',
             'Present Continuous (arrangement) vs Will (decision now):',
             'I _____ (meet) her at 6 (planned). OK, I _____ (help) you (spontaneous).',
             ['am meeting', 'will help'],
             '"Am meeting" = planned. "Will help" = decision now.'),
            ('transformation',
             'Present (now) -> Present (future) meaning:',
             'I am cooking dinner. (change to: arrangement for tomorrow)',
             'I am cooking dinner tomorrow night.',
             'Same form + future marker = future meaning.'),
        ],
        'quantifiers': [
            ('multiple-choice',
             'Some/Any vs Much/Many:',
             'I have _____ friends. I don\'t have _____ money. How _____ time do we have?',
             ['some / any / much', 'any / some / many', 'much / many / some', 'many / much / any'],
             'some / any / much',
             '"Friends" (pos) -> some. "Money" (neg) -> any. "Time" (uncountable question) -> much.'),
            ('fill-blank',
             'A few vs A little vs A lot of:',
             'I have _____ (a few/a little) close friends. There is _____ (a few/a little) milk left.',
             ['a few', 'a little'],
             '"Friends" (countable) -> a few. "Milk" (uncountable) -> a little.'),
            ('error-correction',
             'Much in positive statements:',
             'She has a lot of books. There is much water on the floor.',
             'much water',
             'There is a lot of water on the floor.',
             '"A lot of" in positive. "Much" for questions/negatives.'),
            ('fill-blank',
             'Each vs Every (individual vs general):',
             '_____ student received a certificate. _____ child needs love.',
             ['Each', 'Every'],
             '"Each" = individual focus. "Every" = general group.'),
            ('transformation',
             'Change quantifier to change meaning:',
             'I have some apples. (change to: fewer quantity)',
             'I have a few apples.',
             '"Some" -> "a few". Different nuance.'),
        ],
        'tooEnough': [
            ('multiple-choice',
             'Too + adjective vs Not + adjective + enough:',
             'This coffee is _____ hot to drink (excessive). This coffee is not cool _____ to drink.',
             ['too / enough', 'enough / too', 'very / too', 'so / enough'],
             'too / enough',
             '"Too hot" = excessive. "Cool enough" = sufficient.'),
            ('fill-blank',
             'Too vs Very (negative vs neutral):',
             'This box is _____ heavy for me to lift (cannot lift). This box is _____ heavy (describing).',
             ['too', 'very'],
             '"Too" = negative result. "Very" = neutral description.'),
            ('error-correction',
             'Position of enough (adjective vs noun):',
             'I have enough money. The water is enough hot.',
             'enough hot',
             'The water is hot enough.',
             '"Enough + noun", "Adjective + enough".'),
            ('fill-blank',
             'Too/Enough + to-infinitive:',
             'She is too tired _____ (go) out. He is smart enough _____ (pass) the test.',
             ['to go', 'to pass'],
             'Too + adj + to + V1. Adj + enough + to + V1.'),
            ('transformation',
             'Too -> Enough (opposite meaning):',
             'The water is too cold to swim. (change to: not warm enough)',
             'The water is not warm enough to swim.',
             '"Too cold" -> "not warm enough". Same negative result.'),
        ],
        'soSuch': [
            ('multiple-choice',
             'So + adjective vs Such + noun phrase:',
             'She is _____ kind. She is _____ a kind person.',
             ['so / such', 'such / so', 'very / so', 'so / very'],
             'so / such',
             '"So + adjective", "Such + noun phrase".'),
            ('fill-blank',
             'So vs Such (with/without noun):',
             'The music was _____ loud. It was _____ loud music.',
             ['so', 'such'],
             '"So loud" (no noun). "Such loud music" (with noun).'),
            ('error-correction',
             'So/Such + that (result clause):',
             'It was so hot that we stayed inside. It was such beautiful weather that we went out.',
             'such beautiful weather that',
             'Both are correct! Different patterns.'),
            ('fill-blank',
             'So many/much vs Such a lot of:',
             'There were _____ many people! There was _____ much food!',
             ['so', 'so'],
             '"So many/much + noun".'),
            ('transformation',
             'So -> Such:',
             'The book was so interesting that I couldn\'t stop. (use: such)',
             'It was such an interesting book that I couldn\'t stop.',
             '"So interesting" -> "such an interesting book".'),
        ],
        'a2Review2': [
            ('multiple-choice',
             'Review: Various grammar topics combined:',
             'I _____ (go) to Tashkent next week. I _____ (visit) my family there.',
             ['am going / will visit', 'go / visit', 'will go / am visiting', 'went / visited'],
             'am going / will visit',
             '"Am going" = arrangement. "Will visit" = plan.'),
            ('fill-blank',
             'Review: Mixing tenses in context:',
             'I _____ (study) English for 2 years. Before that, I _____ (study) French at school.',
             ['have studied', 'studied'],
             '"For 2 years" = Present Perfect. "Before that" = Past Simple.'),
            ('error-correction',
             'Review: Article + tense + preposition:',
             'I have been to the USA in 2019. I am interesting in learn English.',
             'in 2019',
             'I went to the USA in 2019. I am interested in learning English.',
             'Specific past -> Past Simple.'),
            ('fill-blank',
             'Review: Conditional + wish + modal:',
             'If I _____ (have) time, I will call. I wish I _____ (be) richer.',
             ['have', 'were'],
             'First conditional (have). Wish (were subjunctive).'),
            ('transformation',
             'Review: Rewrite using different structures:',
             'I don\'t have a car, so I take the bus. (use: If)',
             'If I had a car, I wouldn\'t take the bus.',
             'Fact -> Second conditional. Hypothetical.'),
        ],

        # ── B2 Part 1 ──
        'unrealPastB2': [
            ('multiple-choice',
             'Third conditional vs Past modals of regret:',
             'If I _____ about the traffic, I _____ earlier. I _____ (should) left earlier.',
             ['had known / would have left / should have', 'knew / would leave / should', 'have known / will leave / should', 'would know / left / should'],
             'had known / would have left / should have',
             'Third conditional (had known/would have left) and "should have" for regret.'),
            ('fill-blank',
             'Wish (regret) vs Third conditional:',
             'I wish I _____ (study) harder. If I _____ (study) harder, I _____ (pass).',
             ['had studied', 'had studied', 'would have passed'],
             '"I wish + had studied" (regret) = Third conditional structure.'),
            ('error-correction',
             'Unreal past tense mixture error:',
             'If I would have known, I would come earlier. I wish I was there yesterday.',
             'would have known',
             'If I had known, I would have come earlier.',
             'Third conditional: if + had + V3... would have + V3.'),
            ('fill-blank',
             'Unreal past vs Past Simple (fact vs hypothetical):',
             'I didn\'t go to the party. If I _____ (go), I _____ (meet) her.',
             ['had gone', 'would have met'],
             'Fact (didn\'t go) -> Hypothetical (had gone/would have met).'),
            ('transformation',
             'Fact -> Unreal past:',
             'I didn\'t save money, so I couldn\'t buy a house. (use: If)',
             'If I had saved money, I could have bought a house.',
             'Fact -> Third conditional.'),
        ],
        'advancedConditionalsB2': [
            ('multiple-choice',
             'Mixed conditional (past + present):',
             'If I _____ (study) medicine, I _____ a doctor now. But I studied art.',
             ['had studied / would be', 'studied / would be', 'have studied / will be', 'would study / would have been'],
             'had studied / would be',
             'Mixed: if + past perfect + would + V1 (past condition, present result).'),
            ('fill-blank',
             'Inverted conditionals (should/were/had):',
             '_____ it rain, we will cancel. _____ I you, I would accept. _____ I known, I\'d have come.',
             ['Should', 'Were', 'Had'],
             'Inversion: Should (first), Were (second), Had (third). More formal.'),
            ('error-correction',
             'Mixed conditional wrong tense:',
             'If I had studied, I would pass the exam yesterday.',
             'would pass the exam yesterday',
             'If I had studied, I would have passed the exam yesterday.',
             'Past result -> would have + V3.'),
            ('fill-blank',
             'Unless/Provided that vs If:',
             'I\'ll go _____ it rains (= if not). You can pass _____ you study (= if).',
             ['unless', 'provided that'],
             '"Unless" = if not. "Provided that" = on condition.'),
            ('transformation',
             'Standard -> Inverted conditional:',
             'If I had known, I would have come. (invert: remove if)',
             'Had I known, I would have come.',
             'Standard -> Inverted (Had + subject).'),
        ],
        'nominalizationB2': [
            ('multiple-choice',
             'Nominalization (noun phrase vs verb clause):',
             '_____ is important for success. _____ you work hard is also important.',
             ['Hard work / That', 'Working hard / What', 'Hard working / Which', 'Work hard / That'],
             'Hard work / That',
             '"Hard work" = noun. "That you work hard" = noun clause.'),
            ('fill-blank',
             'Verb -> Noun (with -tion/-ment):',
             'The _____ (decide) was difficult. The _____ (develop) of the city was rapid.',
             ['decision', 'development'],
             'Verb -> Noun. -tion and -ment suffixes.'),
            ('error-correction',
             'Gerund vs Infinitive as subject:',
             'To swim is good exercise. Swimming is good exercise.',
             'To swim',
             'Both acceptable, but gerund is more natural for general statements.'),
            ('fill-blank',
             'Nominalization with What/That/It:',
             '_____ I need is a vacation. _____ she passed surprised everyone. _____ is clear that we must act.',
             ['What', 'That', 'It'],
             '"What" = the thing. "That" = the fact. "It" = dummy subject.'),
            ('transformation',
             'Verb clause -> Noun phrase (formal):',
             'The company decided to expand. (use: decision)',
             'The decision to expand was made by the company.',
             'Verb (decided) -> Noun (decision). More formal.'),
        ],
        'subjunctiveB2': [
            ('multiple-choice',
             'Subjunctive vs Indicative (demand/suggestion):',
             'I suggest that he _____ early. It is important that she _____ present.',
             ['leave / be', 'leaves / is', 'left / was', 'will leave / will be'],
             'leave / be',
             'Subjunctive = base form (no -s, no tense).'),
            ('fill-blank',
             'Subjunctive vs Should + infinitive:',
             'I recommend that he _____ (see) a doctor. It is vital that she _____ (be) told.',
             ['see', 'be'],
             'Subjunctive uses base V1 (see, be).'),
            ('error-correction',
             'Subjunctive third person -s (wrong):',
             'I insist that he arrives on time. It is essential that she is told.',
             'arrives',
             'I insist that he arrive on time. It is essential that she be told.',
             'Subjunctive: no -s for third person.'),
            ('fill-blank',
             'Subjunctive vs Modal (should/must):',
             'I suggest that he _____ (go). = I suggest that he should _____ (go).',
             ['go', 'go'],
             'Subjunctive (go) = Should + V1.'),
            ('transformation',
             'Indicative -> Subjunctive (formal):',
             'It is important that she is informed. (formal subjunctive)',
             'It is important that she be informed.',
             'Indicative -> Subjunctive. Formal usage.'),
        ],
        'hedgingB2': [
            ('multiple-choice',
             'Hedging vs Strong claim:',
             'This _____ the best solution. (100% sure) This _____ the best solution. (not sure)',
             ['is / might be', 'might be / is', 'must be / is', 'could be / must be'],
             'is / might be',
             '"Is" = strong. "Might be" = hedged.'),
            ('fill-blank',
             'Hedging with It seems vs It is clear:',
             '_____ that the economy is improving (strong). _____ that the economy might improve (hedged).',
             ['It is clear', 'It seems'],
             '"It is clear" = strong. "It seems" = hedged.'),
            ('error-correction',
             'Hedging double hedge:',
             'It might possibly perhaps be somewhat likely that the results could maybe show improvement.',
             'possibly perhaps',
             'It might be that the results show improvement.',
             'One hedge per claim is enough.'),
            ('fill-blank',
             'Hedging vs Fact:',
             '_____ that water boils at 100C (fact). _____ that global temperatures are rising (hedged).',
             ['It is known', 'There is evidence'],
             'Facts = no hedge. Interpretations = hedged.'),
            ('transformation',
             'Strong claim -> Hedged claim:',
             'This proves our theory is correct. (hedge: suggest)',
             'This suggests that our theory might be correct.',
             'Strong (proves) -> Hedged (suggests...might be).'),
        ],
        'complexPrepositionsB2': [
            ('multiple-choice',
             'Complex vs Simple prepositions:',
             '_____ the weather, we will go. (despite) _____ the delay, we arrived on time. (because of)',
             ['In spite of / Due to', 'Because / Although', 'Despite of / Owing', 'Regardless / Thanks'],
             'In spite of / Due to',
             '"In spite of" = despite. "Due to" = because of.'),
            ('fill-blank',
             'In terms of / With regard to / As for:',
             '_____ cost, this is better. _____ your question, I will answer later. _____ me, I am fine.',
             ['In terms of', 'With regard to', 'As for'],
             'Different complex prepositions for different contexts.'),
            ('error-correction',
             'Complex preposition word order:',
             'Due to of the rain, we stayed in. In spite the weather, we went out.',
             'Due to of',
             'Due to the rain... In spite of the weather...',
             '"Due to" (not "due to of"). "In spite of" (not "in spite").'),
            ('fill-blank',
             'Preposition + -ing patterns:',
             'We succeeded _____ solving the problem. I look forward _____ hearing from you.',
             ['in', 'to'],
             '"Succeed in + -ing", "Look forward to + -ing".'),
            ('transformation',
             'Simple -> Complex preposition (formal):',
             'We didn\'t go because of the rain. (use: on account of)',
             'We didn\'t go on account of the rain.',
             '"Because of" -> "on account of". More formal.'),
        ],
        'cohesionB2': [
            ('multiple-choice',
             'Cohesive devices (however/therefore/moreover):',
             'It was raining. _____, we went out. She is smart; _____, she works hard.',
             ['However / moreover', 'Therefore / however', 'Moreover / therefore', 'Nevertheless / in addition'],
             'However / moreover',
             'Contrast (however), addition (moreover).'),
            ('fill-blank',
             'Cohesion: Reference words (this/that/these):',
             'We need to reduce costs. _____ is a priority. We must take _____ steps immediately.',
             ['This', 'these'],
             '"This" = singular. "These" = plural.'),
            ('error-correction',
             'Wrong connector:',
             'She studied hard, however she failed. I like tea, moreover my sister likes coffee.',
             'however she failed',
             'She studied hard; however, she failed. I like tea, whereas my sister likes coffee.',
             '"However" needs semicolon.'),
            ('fill-blank',
             'Cohesive vs Relative clause:',
             'The company increased profits. _____, it hired more staff. The company, _____ increased profits, hired more.',
             ['Moreover', 'which'],
             '"Moreover" = separate sentence. "Which" = relative clause.'),
            ('transformation',
             'Two sentences -> One cohesive sentence:',
             'The project was difficult. We finished it on time. (use: despite)',
             'We finished the project on time despite its difficulty.',
             'Two sentences -> one with "despite".'),
        ],
        'registerB2': [
            ('multiple-choice',
             'Formal vs Informal register:',
             'Informal: The company _____ a lot of money. Formal: The organization _____ significant profits.',
             ['made / generated', 'got / made', 'did / achieved', 'had / got'],
             'made / generated',
             '"Made" (informal) vs "generated" (formal).'),
            ('fill-blank',
             'Phrasal verb vs Single verb (formal/informal):',
             'We need to _____ (look into/investigate) the issue (formal).',
             ['investigate'],
             'Formal -> single verb (investigate).'),
            ('error-correction',
             'Register mismatch:',
             'The CEO was like, we gotta increase profits.',
             'was like',
             'The CEO stated that the company must increase profits.',
             'Business context -> formal register.'),
            ('fill-blank',
             'Contractions vs Full forms (formal/informal):',
             'The results _____ (don\'t/do not) support our hypothesis (formal).',
             ['do not'],
             'Formal writing -> no contractions.'),
            ('transformation',
             'Informal -> Formal register:',
             'The company went bust because they messed up. (make formal)',
             'The company failed due to operational errors.',
             '"Went bust" -> "failed". "Messed up" -> "operational errors".'),
        ],

        # ── B2 Part 2 ──
        'complexSentencesB2': [
            ('multiple-choice',
             'Compound vs Complex sentence:',
             'I went home, _____ I was tired (compound). I went home _____ I was tired (complex).',
             ['and / because', 'because / and', 'so / but', 'although / yet'],
             'and / because',
             'Compound (and), Complex (because).'),
            ('fill-blank',
             'Relative clause vs Adverbial clause:',
             'The man _____ lives next door is kind. (relative) _____ he lives next door, I see him daily. (adverbial)',
             ['who', 'Because'],
             'Relative (who = describes noun). Adverbial (Because = reason).'),
            ('error-correction',
             'Run-on sentence:',
             'I went to the store I bought milk I came home.',
             'I went to the store I bought milk',
             'I went to the store, bought milk, and came home.',
             'Run-on -> correct complex sentence.'),
            ('fill-blank',
             'Reduced clause vs Full clause:',
             '_____ (When walking / When I was walking) home, I met a friend.',
             ['When walking'],
             'Full clause -> Reduced clause. Same meaning.'),
            ('transformation',
             'Two simple -> One complex sentence:',
             'I arrived late. The meeting had started. (use: after)',
             'After I arrived, the meeting had already started.',
             'Two sentences -> one complex sentence.'),
        ],
        'advancedModalsB2': [
            ('multiple-choice',
             'Modals of deduction (present vs past):',
             'He _____ at home (Im sure now). He _____ at home (Im sure then).',
             ['must be / must have been', 'might be / might be', 'can\'t be / must be', 'should be / should have been'],
             'must be / must have been',
             'Present (must be) vs Past (must have been).'),
            ('fill-blank',
             'Needn\'t have vs Didn\'t need to:',
             'I _____ (needn\'t have/didn\'t need to) bought it (unnecessary but I did).',
             ['needn\'t have'],
             '"Needn\'t have done" = unnecessary action that happened.'),
            ('error-correction',
             'Modal + have + V3 structure:',
             'He must had left early. She could of told me.',
             'must had',
             'He must have left early. She could have told me.',
             'Modal + have + V3 (past participle).'),
            ('fill-blank',
             'Can\'t (present) vs Couldn\'t have (past):',
             'He _____ be at home (present). He _____ have taken it (past).',
             ['can\'t', 'couldn\'t'],
             'Present: can\'t + V1. Past: couldn\'t have + V3.'),
            ('transformation',
             'Present -> Past deduction:',
             'He might be at home. (change to past)',
             'He might have been at home.',
             'Present (might be) -> Past (might have been).'),
        ],
        'contrastiveStructuresB2': [
            ('multiple-choice',
             'Although/Despite/In spite of:',
             '_____ it was raining, we went out. _____ the rain, we went out.',
             ['Although / Despite', 'Despite / Although', 'Even though / Although', 'Though / Despite of'],
             'Although / Despite',
             '"Although + clause", "Despite + noun".'),
            ('fill-blank',
             'Whereas vs However:',
             'My sister likes tea, _____ I prefer coffee (same sentence). My sister likes tea. _____, I prefer coffee (new sentence).',
             ['whereas', 'However'],
             '"Whereas" = one sentence. "However" = new sentence.'),
            ('error-correction',
             'Despite + clause (wrong):',
             'Despite it was raining, we went out.',
             'Despite it was raining',
             'Despite the rain, we went out.',
             '"Despite" + noun, not clause.'),
            ('fill-blank',
             'Contrast + reason combined:',
             '_____ the cost was high, we bought it (contrast). We bought it _____ it was useful (reason).',
             ['Although', 'because'],
             '"Although" = contrast. "Because" = reason.'),
            ('transformation',
             'Two contrastive sentences -> One:',
             'He is rich. He is not happy. (use: in spite of)',
             'In spite of being rich, he is not happy.',
             'Two sentences -> one contrastive sentence.'),
        ],
        'punctuationB2': [
            ('multiple-choice',
             'Comma vs Semicolon vs Colon:',
             'I bought apples, bananas _____ oranges (list). I studied hard _____ I passed (two clauses).',
             [', / ;', '; / :', ': / ;', ', / :'],
             ', / ;',
             'Comma = list. Semicolon = two clauses.'),
            ('fill-blank',
             'Comma splice vs Correct punctuation:',
             'I was tired _____ I went to bed. (comma is WRONG: comma splice)',
             [','],
             'Comma alone = comma splice. Use semicolon.'),
            ('error-correction',
             'Apostrophe errors:',
             'The student\'s are in the class. Its a beautiful day.',
             'student\'s are',
             'The students are in the class. It\'s a beautiful day.',
             '"Student\'s" = possessive, not plural. "It\'s" = it is.'),
            ('fill-blank',
             'Quotation marks in US vs UK:',
             'She said _____I am tired_____ (US: double quotes).',
             ['"'],
             'US -> double quotes. UK -> single quotes.'),
            ('transformation',
             'Run-on -> Correctly punctuated:',
             'I woke up I ate breakfast I went to work (add punctuation)',
             'I woke up, ate breakfast, and went to work.',
             'Run-on -> correct with commas and conjunction.'),
        ],
        'academicCollocationsB2': [
            ('multiple-choice',
             'Verb + noun collocations:',
             'We need to _____ a decision. She _____ a conclusion. They _____ research.',
             ['make / drew / conduct', 'do / made / do', 'take / took / make', 'have / gave / perform'],
             'make / drew / conduct',
             '"Make a decision", "Draw a conclusion", "Conduct research".'),
            ('fill-blank',
             'Adjective + noun collocations:',
             'We had a _____ (strong/high) chance of winning. It was a _____ (hard/difficult) decision.',
             ['high', 'difficult'],
             '"High chance", "Difficult decision". Fixed pairs.'),
            ('error-correction',
             'Wrong collocation:',
             'I did a mistake. She made a research.',
             'did a mistake',
             'I made a mistake. She conducted research.',
             '"Make a mistake", "Conduct research".'),
            ('fill-blank',
             'Adverb + adjective collocations:',
             'It is _____ (highly/strongly) recommended. We are _____ (bitterly/deeply) disappointed.',
             ['highly', 'deeply'],
             '"Highly recommended", "Deeply disappointed".'),
            ('transformation',
             'Replace with correct collocation:',
             'We had a strong chance of success. (fix the collocation)',
             'We had a high chance of success.',
             '"Strong chance" -> "high chance".'),
        ],
        'criticalThinkingB2': [
            ('multiple-choice',
             'Fact vs Opinion vs Inference:',
             'The Earth orbits the Sun (_____). Coffee is delicious (_____). She looks tired (_____).',
             ['fact / opinion / inference', 'opinion / fact / inference', 'inference / opinion / fact', 'fact / inference / opinion'],
             'fact / opinion / inference',
             'Fact = verifiable. Opinion = personal. Inference = reasoning.'),
            ('fill-blank',
             'Strong evidence vs Weak evidence:',
             'A randomized trial provides _____ evidence. One person\'s story provides _____ evidence.',
             ['strong', 'weak'],
             'Scientific studies = strong. Anecdotes = weak.'),
            ('error-correction',
             'Hasty generalization:',
             'I met one rude person from that city, so everyone from there is rude.',
             'one rude person',
             'It would be unfair to generalize about everyone from there.',
             'Hasty generalization = too little evidence.'),
            ('fill-blank',
             'Counter-argument structure:',
             '_____ some people believe X, the evidence suggests Y. Critics _____ that Z is flawed.',
             ['Although', 'argue'],
             'Counter-argument: acknowledge, then refute.'),
            ('transformation',
             'Opinion -> Evidence-based claim:',
             'I think this medicine works. (add evidence)',
             'Studies have shown that this medicine is effective.',
             'Opinion (I think) -> Evidence (studies show).'),
        ],
        'b2Review': [
            ('multiple-choice',
             'Review: Mixed grammar topics:',
             'If I _____ harder, I would have passed. I wish I _____ (study).',
             ['had studied / had studied', 'studied / studied', 'would study / have studied', 'have studied / study'],
             'had studied / had studied',
             'Third conditional + wish + past perfect.'),
            ('fill-blank',
             'Review: Academic collocations:',
             'The study _____ (draws/makes) an important conclusion.',
             ['draws'],
             '"Draw a conclusion". Academic collocation.'),
            ('error-correction',
             'Review: Complex structure errors:',
             'Despite the fact that he was tired, but he continued working.',
             'but he continued',
             'Despite being tired, he continued working.',
             'Double conjunction (despite + but) = redundant.'),
            ('fill-blank',
             'Review: Hedging + subjunctive:',
             'The data _____ (suggests/suggest) that the theory is correct.',
             ['suggest'],
             '"Data" = plural -> suggest.'),
            ('transformation',
             'Review: Informal -> Formal academic:',
             'The company got better results because they tried hard. (make formal)',
             'The company achieved improved results due to increased effort.',
             'Informal -> Formal.'),
        ],

        # ── B2 Part 3 ──
        'argumentStructureB2': [
            ('multiple-choice',
             'Claim vs Evidence vs Warrant:',
             'We should invest in solar energy (_____). Solar power is becoming cheaper (_____).',
             ['claim / evidence', 'evidence / claim', 'warrant / evidence', 'claim / warrant'],
             'claim / evidence',
             'Claim = main argument. Evidence = supporting data.'),
            ('fill-blank',
             'Thesis statement vs Topic sentence:',
             '_____ states the main argument of the whole essay. _____ states the main point of one paragraph.',
             ['Thesis statement', 'Topic sentence'],
             'Thesis = entire essay. Topic sentence = one paragraph.'),
            ('error-correction',
             'Circular reasoning:',
             'This book is good because it is well-written.',
             'because it is well-written',
             'This book is good because it develops complex characters.',
             'Circular reasoning = repeating the claim.'),
            ('fill-blank',
             'Concession + Refutation:',
             '_____ some argue that X is true, _____ the evidence strongly suggests Y.',
             ['While', 'however/'],
             'Concession (While) + Refutation (however).'),
            ('transformation',
             'Opinion -> Structured argument:',
             'I think social media is bad. (create: claim + evidence)',
             'Social media is harmful because studies show it increases anxiety.',
             'Opinion -> Claim + Evidence + Warrant.'),
        ],
        'stanceMarkersB2': [
            ('multiple-choice',
             'Strong vs Weak stance:',
             'This _____ the best solution (strong). This _____ be the best solution (weak).',
             ['is undoubtedly / could', 'might / is definitely', 'perhaps / is clearly', 'is possibly / must'],
             'is undoubtedly / could',
             '"Is undoubtedly" = strong. "Could" = weak.'),
            ('fill-blank',
             'Stance markers in academic writing:',
             '_____ (Clearly/Perhaps), this approach is superior. (strong stance)',
             ['Clearly'],
             'Strong stance: Clearly, Undoubtedly, Certainly.'),
            ('error-correction',
             'Stance mismatch with evidence:',
             'Clearly, the results might suggest a trend.',
             'Clearly...might',
             'The results might suggest a trend.',
             '"Clearly" (strong) + "might" (weak) = contradictory.'),
            ('fill-blank',
             'Boosting vs Hedging stance:',
             'This _____ proves the theory (boost). This _____ suggests the theory (hedge).',
             ['undoubtedly', 'tentatively'],
             'Boosters strengthen. Hedges weaken.'),
            ('transformation',
             'Hedged -> Strong stance:',
             'This might suggest a connection. (change to: strong evidence)',
             'This clearly demonstrates a connection.',
             '"Might suggest" -> "clearly demonstrates".'),
        ],
        'paraphrasingB2': [
            ('multiple-choice',
             'Synonym substitution vs Structure change:',
             'Original: The results were significant. Best paraphrase strategy:',
             ['Use synonyms + change structure', 'Just change one word', 'Keep same structure', 'Only change word order'],
             'Use synonyms + change structure',
             'Best paraphrase = multiple changes.'),
            ('fill-blank',
             'Active -> Passive (paraphrase technique):',
             'The researchers conducted the study. (passive) The study _____ _____ by the researchers.',
             ['was conducted'],
             'Active -> Passive = paraphrase technique.'),
            ('error-correction',
             'Too close to original (plagiarism risk):',
             'Original: "The economy grew rapidly." Student: "The economy grew fast."',
             'The economy grew',
             '"There was rapid growth in the economy."',
             'Just changing one word = too close.'),
            ('fill-blank',
             'Combining paraphrase techniques:',
             'Original: Many people believe the policy is effective. (It + passive) _____ _____ that the policy is effective.',
             ['It is widely believed'],
             'Passive + synonym = effective paraphrase.'),
            ('transformation',
             'Paraphrase using multiple techniques:',
             'The government introduced new regulations to reduce pollution.',
             'New regulations were introduced by the government to decrease pollution.',
             'Active -> Passive + synonym (reduce -> decrease).'),
        ],
        'advancedVerbPatternsB2': [
            ('multiple-choice',
             'Verb + object + infinitive vs Verb + -ing:',
             'I advised him _____ early. I suggested _____ early.',
             ['to leave / leaving', 'leaving / to leave', 'leave / leave', 'to leave / to leave'],
             'to leave / leaving',
             '"Advise + object + to", "Suggest + -ing".'),
            ('fill-blank',
             'Verb + that clause vs Verb + to-infinitive:',
             'She agreed _____ (help). She agreed _____ she would help.',
             ['to help', 'that'],
             'Agree + to. Agree + that clause.'),
            ('error-correction',
             'Missing preposition with verb:',
             'She prevented him to go. He insisted to come.',
             'to go',
             'She prevented him from going. He insisted on coming.',
             '"Prevent + from + -ing". "Insist + on + -ing".'),
            ('fill-blank',
             'Causative verbs (have/get/make/let):',
             'I had my assistant _____ (print) the report. I got him _____ (print) it.',
             ['print', 'to print'],
             '"Have + V1", "Get + to + V1".'),
            ('transformation',
             'Active -> Passive infinitive:',
             'People believe that he is rich. (use: He is believed)',
             'He is believed to be rich.',
             '"Believe that + clause" -> "be believed to + V1".'),
        ],
        'b2ComprehensiveReview': [
            ('multiple-choice',
             'Review: All B2 grammar combined:',
             '_____ the evidence, the theory is flawed. If the data _____ reliable, we would accept it.',
             ['Given / were', 'Despite / was', 'With / is', 'Because of / are'],
             'Given / were',
             'Complex prep (Given), second conditional (were).'),
            ('fill-blank',
             'Review: Nominalization + stance:',
             'The _____ (implement) of the policy was successful.',
             ['implementation'],
             'Verb (implement) -> Noun (implementation).'),
            ('error-correction',
             'Review: Multiple advanced errors:',
             'The data suggests that he is the best candidate. I recommend that he is hired.',
             'data suggests',
             'The data suggest... I recommend that he be hired.',
             '"Data" = plural. Subjunctive: "that he be hired".'),
            ('fill-blank',
             'Review: Cohesion + argument:',
             '_____ (Nevertheless/Moreover), the results are promising.',
             ['Nevertheless'],
             'Nevertheless = concession/contrast.'),
            ('transformation',
             'Review: All skills combined:',
             'They think social media causes anxiety. (paraphrase: passive)',
             'It is believed that social media causes anxiety.',
             'Active -> Passive. Formal paraphrase.'),
        ],
    }
    
    lesson_data = templates.get(lesson_id)
    if not lesson_data:
        return None
    
    lines = []
    for i, ex in enumerate(lesson_data):
        ex_id = start_id + i
        ex_type = ex[0]
        instruction = ex[1]
        question = ex[2]
        
        if ex_type == 'multiple-choice':
            options = ex[3]
            correct = ex[4]
            explanation = ex[5]
            lines.append(f'    {{ id: {ex_id}, type: \'multiple-choice\', instruction: "{instruction}",')
            lines.append(f'      question: "{question}",')
            lines.append(f'      options: {json.dumps(options, ensure_ascii=False)},')
            lines.append(f'      correct: {json.dumps(correct, ensure_ascii=False)},')
            lines.append(f'      explanation: "{explanation}" }},')
        elif ex_type == 'fill-blank':
            blanks = ex[3]
            explanation = ex[4]
            lines.append(f'    {{ id: {ex_id}, type: \'fill-blank\', instruction: "{instruction}",')
            lines.append(f'      question: "{question}",')
            lines.append(f'      blanks: {json.dumps(blanks, ensure_ascii=False)},')
            lines.append(f'      explanation: "{explanation}" }},')
        elif ex_type == 'error-correction':
            question_text = ex[2] if len(ex) > 2 else ''
            error_part = ex[3] if len(ex) > 3 else ''
            correct_text = ex[4] if len(ex) > 4 else ''
            explanation = ex[5] if len(ex) > 5 else ''
            # Fix: ensure we use the right indexing
            # Template structure: ('error-correction', instruction, question, errorPart, correct, explanation)
            # So ex[2]=question, ex[3]=errorPart, ex[4]=correct, ex[5]=explanation
            lines.append(f'    {{ id: {ex_id}, type: \'error-correction\', instruction: "{instruction}",')
            lines.append(f'      question: "{question_text}",')
            lines.append(f'      errorPart: {json.dumps(error_part, ensure_ascii=False)},')
            lines.append(f'      correct: "{correct_text}",')
            lines.append(f'      explanation: "{explanation}" }},')
        elif ex_type == 'transformation':
            question_text = ex[3]
            correct_text = ex[4]
            explanation = ex[5]
            lines.append(f'    {{ id: {ex_id}, type: \'transformation\', instruction: "{instruction}",')
            lines.append(f'      question: "{question_text}",')
            lines.append(f'      hint: "Hint...",')
            lines.append(f'      correct: "{correct_text}",')
            lines.append(f'      explanation: "{explanation}" }},')
    
    return '\n'.join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# Lesson list
# ═══════════════════════════════════════════════════════════════════════════

A2_1 = 'src/data/daily/a2Part1.ts'
A2_2 = 'src/data/daily/a2Part2.ts'
A2_3 = 'src/data/daily/a2Part3.ts'
A2_4 = 'src/data/daily/a2Part4.ts'
B2_1 = 'src/data/daily/b2Part1.ts'
B2_2 = 'src/data/daily/b2Part2.ts'
B2_3 = 'src/data/daily/b2Part3.ts'

lesson_defs = [
    # (file, lesson_id, start_id)
    # A2 Part 1
    (A2_1, 'modalVerbs', 20000),
    (A2_1, 'articles', 20005),
    (A2_1, 'prepositions', 20010),
    (A2_1, 'questionsLesson', 20015),
    (A2_1, 'countableUncountable', 20020),
    # A2 Part 2
    (A2_2, 'adjectiveAdverb', 20025),
    (A2_2, 'gerundsInfinitives', 20030),
    (A2_2, 'passiveVoice', 20035),
    (A2_2, 'reportedSpeech', 20040),
    (A2_2, 'firstConditional', 20045),
    # A2 Part 3
    (A2_3, 'verbPatterns', 20050),
    (A2_3, 'timePrepositions', 20055),
    (A2_3, 'thereIsThereAre', 20060),
    (A2_3, 'possessives', 20065),
    (A2_3, 'someAnyNoEvery', 20070),
    # A2 Part 4
    (A2_4, 'presentContinuousFuture', 20075),
    (A2_4, 'quantifiers', 20080),
    (A2_4, 'tooEnough', 20085),
    (A2_4, 'soSuch', 20090),
    (A2_4, 'a2Review2', 20095),
    # B2 Part 1
    (B2_1, 'unrealPastB2', 70000),
    (B2_1, 'advancedConditionalsB2', 70005),
    (B2_1, 'nominalizationB2', 70010),
    (B2_1, 'subjunctiveB2', 70015),
    (B2_1, 'hedgingB2', 70020),
    (B2_1, 'complexPrepositionsB2', 70025),
    (B2_1, 'cohesionB2', 70030),
    (B2_1, 'registerB2', 70035),
    # B2 Part 2
    (B2_2, 'complexSentencesB2', 70040),
    (B2_2, 'advancedModalsB2', 70045),
    (B2_2, 'contrastiveStructuresB2', 70050),
    (B2_2, 'punctuationB2', 70055),
    (B2_2, 'academicCollocationsB2', 70060),
    (B2_2, 'criticalThinkingB2', 70065),
    (B2_2, 'b2Review', 70070),
    # B2 Part 3
    (B2_3, 'argumentStructureB2', 70075),
    (B2_3, 'stanceMarkersB2', 70080),
    (B2_3, 'paraphrasingB2', 70085),
    (B2_3, 'advancedVerbPatternsB2', 70090),
    (B2_3, 'b2ComprehensiveReview', 70095),
]

# ═══════════════════════════════════════════════════════════════════════════
# Main logic
# ═══════════════════════════════════════════════════════════════════════════

files_processed = {}

for file_path, lesson_id, start_id in lesson_defs:
    if file_path not in files_processed:
        with open(file_path, 'r', encoding='utf-8') as f:
            files_processed[file_path] = f.read()

    content = files_processed[file_path]

    # Find lesson
    marker = f"export const {lesson_id}: DailyLesson"
    idx = content.find(marker)
    if idx == -1:
        print(f"\u274c {file_path}: {lesson_id} not found")
        continue

    # Check if already has interleaved
    lesson_block = content[idx:idx+80000]
    if '\u2500\u2500 Interleaved Practice:' in lesson_block:
        print(f"\u23ed  {lesson_id}: Already has interleaved practice")
        continue

    # Generate exercise text
    exercise_text = make_exercises(lesson_id, start_id)
    if exercise_text is None:
        print(f"\u274c {lesson_id}: No template found")
        continue

    # Add comment header
    comment_line = f"    // \u2500\u2500 Interleaved Practice: {lesson_id} + other grammar topics (F2-2) \u2500\u2500"
    exercise_block = comment_line + '\n' + exercise_text

    # Find exerciseSections closing
    es_idx = lesson_block.find('exerciseSections:')
    if es_idx == -1:
        print(f"\u274c {lesson_id}: exerciseSections not found")
        continue

    search_from = idx + es_idx
    es_end = content.find('\n  ],', search_from)
    if es_end == -1:
        print(f"\u274c {lesson_id}: Could not find exerciseSections closing")
        continue

    # Add Aralash section
    ids_str = ', '.join(str(start_id + i) for i in range(5))
    section_insert = f'    {{ title: "Aralash", desc: "Interleaved Practice \u2014 {lesson_id} ni boshqa grammar topics bilan aralashtirish", color: \'bg-fuchsia-500\', icon: \'\U0001f504\', ids: [{ids_str}] }},\n  ]'

    content = content[:es_end] + ',\n    ' + section_insert + content[es_end+4:]

    # Find exercises closing and add exercises
    idx2 = content.find(marker)
    lesson_block2 = content[idx2:idx2+80000]
    ex_end = lesson_block2.find('\n  ],\n  exerciseSections:')
    if ex_end == -1:
        print(f"\u274c {lesson_id}: Could not find exercises array ending")
        continue

    insert_point = idx2 + ex_end
    content = content[:insert_point] + '\n\n' + exercise_block + content[insert_point:]

    files_processed[file_path] = content
    print(f"\u2705 {lesson_id}: Added 5 interleaved exercises ({start_id}-{start_id+4}) + Aralash section")

# Save all files
print(f"\n{'='*50}")
for file_path, content in files_processed.items():
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"\u2705 Saved: {file_path}")

print(f"\n\u2705 Done! Modified {len(lesson_defs)} lessons across {len(files_processed)} files.")
