# -*- coding: utf-8 -*-
"""
Add interleaved practice to all A2 and B2 daily lessons.
Each lesson gets 5 interleaved exercises + an 'Aralash' section.
"""

import re

# ═══════════════════════════════════════════════════════════════════════════
# Lesson definitions: (file, lesson_id, start_id, interleaved_exercises_text)
# ═══════════════════════════════════════════════════════════════════════════

LESSONS = []

# ── A2 Part 1: a2Part1.ts ─────────────────────────────────────────────────
A2_1 = 'src/data/daily/a2Part1.ts'

LESSONS.append((A2_1, 'modalVerbs', 20000,
  '    { id: 20000, type: \'multiple-choice\', instruction: "Modal verbs vs Present Simple (ability vs habit):",'
  '\n      question: "I _____ swim very well. I _____ in the pool every weekend.",'
  '\n      options: [\'can / swim\', \'could / am swimming\', \'must / swam\', \'might / will swim\'],'
  '\n      correct: \'can / swim\','
  '\n      explanation: "\'Can swim\' = ability (modal). \'Swim every weekend\' = habit (Present Simple). Bir gapda ikki xil tuzilma." },'
  '\n    { id: 20001, type: \'fill-blank\', instruction: "Must (obligation) vs can (permission):",'
  '\n      question: "You _____ wear a uniform at school. You _____ wear casual clothes on Fridays.",'
  '\n      blanks: [\'must\', \'can\'],'
  '\n      explanation: "\'Must\' = obligation (majburiy). \'Can\' = permission (ruxsat). Bir xil kontekst, turli modal fe\'llar." },'
  '\n    { id: 20002, type: \'error-correction\', instruction: "Can vs To be able to (present vs future):",'
  '\n      question: "I can to speak English. I will can help you tomorrow.",'
  '\n      errorPart: \'can to\','
  '\n      correct: "I can speak English. I will be able to help you tomorrow.",'
  '\n      explanation: "\'Can\' + V1 (no to). Future \u2192 \'will be able to\', not \'will can\'." },'
  '\n    { id: 20003, type: \'fill-blank\', instruction: "Can (ability) vs Present Continuous (now):",'
  '\n      question: "I _____ (speak) three languages. Right now, I _____ (speak) English.",'
  '\n      blanks: [\'can speak\', \'am speaking\'],'
  '\n      explanation: "\'Can speak\' = general ability. \'Am speaking\' = right now. Ability vs current action." },'
  '\n    { id: 20004, type: \'transformation\', instruction: "Present Simple \u2192 Modal bilan ifodalang:",'
  '\n      question: "It is necessary for you to finish this today. (use: must)",'
  '\n      hint: \'You ...\','
  '\n      correct: \'You must finish this today.\','
  '\n      explanation: "\'It is necessary\' \u2192 \'must\'. Modal fe\'l bilan qisqa va aniq ifoda." },'
))

LESSONS.append((A2_1, 'articles', 20005,
  '    { id: 20005, type: \'multiple-choice\', instruction: "A/an vs The (first mention vs specific):",'
  '\n      question: "I saw _____ dog in the park. _____ dog was very friendly.",'
  '\n      options: [\'a / The\', \'the / A\', \'an / The\', \'the / The\'],'
  '\n      correct: \'a / The\','
  '\n      explanation: "\'A dog\' = first mention (umumiy). \'The dog\' = second mention (aniq). Bir hikoyada artikl ishlatish." },'
  '\n    { id: 20006, type: \'fill-blank\', instruction: "A/an vs No article (general vs specific):",'
  '\n      question: "I love _____ music. I bought _____ new guitar yesterday.",'
  '\n      blanks: [\'-\', \'a\'],'
  '\n      explanation: "\'Music\' = general (no article). \'A guitar\' = one specific item." },'
  '\n    { id: 20007, type: \'error-correction\', instruction: "The vs zero article (general statement):",'
  '\n      question: "The dogs are loyal animals. The life is beautiful.",'
  '\n      errorPart: \'The dogs\','
  '\n      correct: "Dogs are loyal animals. Life is beautiful.",'
  '\n      explanation: "General statements \u2192 no article (Dogs, Life). \'The\' faqat aniq narsalar uchun." },'
  '\n    { id: 20008, type: \'fill-blank\', instruction: "Article + Adjective + Noun combination:",'
  '\n      question: "She is _____ honest woman. She has _____ very kind heart.",'
  '\n      blanks: [\'an\', \'a\'],'
  '\n      explanation: "\'Honest\' starts with vowel sound \u2192 \'an\'. \'Very kind heart\' = adjective + noun \u2192 \'a\'." },'
  '\n    { id: 20009, type: \'transformation\', instruction: "Add articles to the sentence:",'
  '\n      question: "I want to buy car and house. (add: a/an/the where needed)",'
  '\n      hint: \'I want ...\','
  '\n      correct: \'I want to buy a car and a house.\','
  '\n      explanation: "First mention of countable nouns \u2192 \'a\'. Artikl qo\'shish orqali gap aniq bo\'ladi." },'
))

LESSONS.append((A2_1, 'prepositions', 20010,
  '    { id: 20010, type: \'multiple-choice\', instruction: "In/On/At (time) vs In/On/At (place):",'
  '\n      question: "I was born _____ 1999. I live _____ Tashkent. See you _____ Monday.",'
  '\n      options: [\'in / in / on\', \'on / at / in\', \'at / in / on\', \'in / at / at\'],'
  '\n      correct: \'in / in / on\','
  '\n      explanation: "\'In 1999\' (year), \'in Tashkent\' (city), \'on Monday\' (day). Bir gapda uch xil preposition." },'
  '\n    { id: 20011, type: \'fill-blank\', instruction: "Prepositions after verbs (depend on vs wait for):",'
  '\n      question: "It depends _____ the weather. I am waiting _____ my friend.",'
  '\n      blanks: [\'on\', \'for\'],'
  '\n      explanation: "\'Depend on\' = bog\'liq. \'Wait for\' = kutmoq. Turli verb + preposition combinations." },'
  '\n    { id: 20012, type: \'error-correction\', instruction: "Preposition at the end of question:",'
  '\n      question: "Who are you waiting for? Where do you come from?",'
  '\n      errorPart: \'come from\','
  '\n      correct: "Who are you waiting for? Where are you from?",'
  '\n      explanation: "\'Come from\' is correct in present tense. \'Where are you from\' = fixed phrase. Question word + preposition." },'
  '\n    { id: 20013, type: \'fill-blank\', instruction: "Prepositions of movement (to/into/onto):",'
  '\n      question: "She walked _____ the room. He jumped _____ the table.",'
  '\n      blanks: [\'into\', \'onto\'],'
  '\n      explanation: "\'Into\' = ichiga. \'Onto\' = ustiga. Prepositions of movement show direction." },'
  '\n    { id: 20014, type: \'transformation\', instruction: "Change prepositions to change meaning:",'
  '\n      question: "He ran in the park. (change to: He entered the park)",'
  '\n      hint: \'He ran ...\','
  '\n      correct: \'He ran into the park.\','
  '\n      explanation: "\'In\' = ichida (location). \'Into\' = ichiga (movement). Preposition changes the meaning entirely." },'
))

LESSONS.append((A2_1, 'questionsLesson', 20015,
  '    { id: 20015, type: \'multiple-choice\', instruction: "Yes/No vs Wh- questions:",'
  '\n      question: "_____ you like coffee? _____ do you like?",'
  '\n      options: [\'Do / What\', \'Are / What\', \'Do / Who\', \'Is / Where\'],'
  '\n      correct: \'Do / What\','
  '\n      explanation: "\'Do you like\' = Yes/No question. \'What do you like\' = Wh-question. Ikki xil savol turi." },'
  '\n    { id: 20016, type: \'fill-blank\', instruction: "Subject vs Object questions:",'
  '\n      question: "_____ lives here? (subject) _____ does she live? (object)",'
  '\n      blanks: [\'Who\', \'Where\'],'
  '\n      explanation: "Subject question: no auxiliary (Who lives). Object question: auxiliary + subject (Where does she live)." },'
  '\n    { id: 20017, type: \'error-correction\', instruction: "Question word order error:",'
  '\n      question: "What you want? Where is the station?",'
  '\n      errorPart: \'What you want\','
  '\n      correct: "What do you want? Where is the station?",'
  '\n      explanation: "Wh-question needs auxiliary: What DO you want. Second question is correct (Where is)." },'
  '\n    { id: 20018, type: \'fill-blank\', instruction: "Present Simple vs Past Simple questions:",'
  '\n      question: "_____ you like the film? _____ you go yesterday?",'
  '\n      blanks: [\'Do\', \'Did\'],'
  '\n      explanation: "Present \u2192 Do/Does + V1. Past \u2192 Did + V1. Bir xil tuzilma, turli zamon." },'
  '\n    { id: 20019, type: \'transformation\', instruction: "Statement \u2192 Question ga o\'zgartiring:",'
  '\n      question: "She lives in Tashkent. (make a question)",'
  '\n      hint: \'Where ...\','
  '\n      correct: \'Where does she live?\''
  '\n      explanation: "Statement (She lives) \u2192 Question (Where does she live). Inversion + auxiliary." },'
))

LESSONS.append((A2_1, 'countableUncountable', 20020,
  '    { id: 20020, type: \'multiple-choice\', instruction: "Much vs Many vs A lot of:",'
  '\n      question: "I don\'t have _____ money. She has _____ friends. There are _____ people here.",'
  '\n      options: [\'much / many / a lot of\', \'many / much / a lot of\', \'a lot of / many / much\', \'much / a lot of / many\'],'
  '\n      correct: \'much / many / a lot of\','
  '\n      explanation: "\'Money\' (uncountable) \u2192 much. \'Friends\' (countable) \u2192 many. \'People\' (plural) \u2192 a lot of." },'
  '\n    { id: 20021, type: \'fill-blank\', instruction: "Some vs Any vs No:",'
  '\n      question: "I have _____ questions. Do you have _____ free time? There is _____ milk left.",'
  '\n      blanks: [\'some\', \'any\', \'no\'],'
  '\n      explanation: "Positive \u2192 some. Question/negative \u2192 any. Zero \u2192 no. Turli kontekstlarda ishlatish." },'
  '\n    { id: 20022, type: \'error-correction\', instruction: "Countable/Uncountable noun error:",'
  '\n      question: "I need informations. She gave me an advice.",'
  '\n      errorPart: \'informations\','
  '\n      correct: "I need information. She gave me some advice.",'
  '\n      explanation: "\'Information\' and \'advice\' are uncountable. No plural -s. Use \'some\' or \'a piece of\'." },'
  '\n    { id: 20023, type: \'fill-blank\', instruction: "Quantifier + noun agreement:",'
  '\n      question: "There are _____ (a few / a little) apples. There is _____ (a few / a little) water.",'
  '\n      blanks: [\'a few\', \'a little\'],'
  '\n      explanation: "\'Apples\' (countable) \u2192 a few. \'Water\' (uncountable) \u2192 a little. Countability determines quantifier." },'
  '\n    { id: 20024, type: \'transformation\', instruction: "Change quantifier to change meaning:",'
  '\n      question: "There is some milk. (change to: zero milk)",'
  '\n      hint: \'There ...\','
  '\n      correct: \'There is no milk.\','
  '\n      explanation: "\'Some\' (positive) \u2192 \'no\' (zero). Quantifier o\'zgarishi bilan ma\'no butunlay o\'zgaradi." },'
))

# ── A2 Part 2: a2Part2.ts ─────────────────────────────────────────────────
A2_2 = 'src/data/daily/a2Part2.ts'

LESSONS.append((A2_2, 'adjectiveAdverb', 20025,
  '    { id: 20025, type: \'multiple-choice\', instruction: "Adjective vs Adverb (describe noun vs verb):",'
  '\n      question: "She is a _____ singer. She sings _____.",'
  '\n      options: [\'good / well\', \'well / good\', \'good / good\', \'well / well\'],'
  '\n      correct: \'good / well\','
  '\n      explanation: "\'Good singer\' = adjective + noun. \'Sings well\' = verb + adverb. Bir gapda adjective va adverb." },'
  '\n    { id: 20026, type: \'fill-blank\', instruction: "Adjective vs Adverb (look/sound/feel):",'
  '\n      question: "You look _____ (beautiful/beautifully) today. She speaks _____ (soft/softly).",'
  '\n      blanks: [\'beautiful\', \'softly\'],'
  '\n      explanation: "\'Look\' = linking verb + adjective. \'Speaks\' = action verb + adverb. Turli verb turlari, turli qo\'shimchalar." },'
  '\n    { id: 20027, type: \'error-correction\', instruction: "Adjective/Adverb confusion:",'
  '\n      question: "He drives careful. She sings beautiful.",'
  '\n      errorPart: \'careful\','
  '\n      correct: "He drives carefully. She sings beautifully.",'
  '\n      explanation: "Action verbs (drives, sings) take adverbs (-ly). \'Careful\' is adjective, \'carefully\' is adverb." },'
  '\n    { id: 20028, type: \'fill-blank\', instruction: "Comparative adjectives vs Adverbs:",'
  '\n      question: "He is _____ (taller/more tall) than me. He runs _____ (faster/more fast) than me.",'
  '\n      blanks: [\'taller\', \'faster\'],'
  '\n      explanation: "Short adjectives: -er (taller). Short adverbs: -er (faster). Bir xil qoida, turli so\'z turkumlari." },'
  '\n    { id: 20029, type: \'transformation\', instruction: "Adjective \u2192 Adverb ga o\'zgartiring:",'
  '\n      question: "She is a quiet student. (change: describes how she studies)",'
  '\n      hint: \'She studies ...\','
  '\n      correct: \'She studies quietly.\','
  '\n      explanation: "\'Quiet student\' (adjective + noun) \u2192 \'studies quietly\' (verb + adverb). Bir sifat, ikki vazifa." },'
))

LESSONS.append((A2_2, 'gerundsInfinitives', 20030,
  '    { id: 20030, type: \'multiple-choice\', instruction: "Verb + -ing vs Verb + to-infinitive:",'
  '\n      question: "I enjoy _____ books. I want _____ a writer.",'
  '\n      options: [\'reading / to become\', \'to read / becoming\', \'read / become\', \'reading / becoming\'],'
  '\n      correct: \'reading / to become\','
  '\n      explanation: "\'Enjoy + -ing\' (reading). \'Want + to-infinitive\' (to become). Bir gapda ikki xil pattern." },'
  '\n    { id: 20031, type: \'fill-blank\', instruction: "Remember + -ing vs Remember + to:",'
  '\n      question: "I remember _____ (meet) her before. Please remember _____ (lock) the door.",'
  '\n      blanks: [\'meeting\', \'to lock\'],'
  '\n      explanation: "\'Remember meeting\' = o\'tmish esdalik. \'Remember to lock\' = kelajak vazifa. Bir xil verb, turli ma\'no." },'
  '\n    { id: 20032, type: \'error-correction\', instruction: "Stop + -ing vs Stop + to:",'
  '\n      question: "I stopped to smoke because it is bad for health. I stopped smoking to rest.",'
  '\n      errorPart: \'to smoke\','
  '\n      correct: "I stopped smoking because it is bad for health. I stopped to rest after working.",'
  '\n      explanation: "\'Stop smoking\' = tashladim (action stops). \'Stop to rest\' = to\'xtab dam oldim (purpose). Butunlay farqli ma\'no." },'
  '\n    { id: 20033, type: \'fill-blank\', instruction: "Like + -ing (enjoy) vs Would like + to (want):",'
  '\n      question: "I like _____ (swim). I would like _____ (swim) now.",'
  '\n      blanks: [\'swimming\', \'to swim\'],'
  '\n      explanation: "\'Like swimming\' = general enjoyment. \'Would like to swim\' = specific desire now." },'
  '\n    { id: 20034, type: \'transformation\', instruction: "-ing \u2192 to-infinitive ga o\'zgartiring (meaning change):",'
  '\n      question: "He stopped talking. (change to: He stopped in order to talk)",'
  '\n      hint: \'He stopped ...\','
  '\n      correct: \'He stopped to talk.\','
  '\n      explanation: "\'Stopped talking\' = to\'xtadi. \'Stopped to talk\' = to\'xtab gaplashdi. Kichik o\'zgarish, katta ma\'no farqi." },'
))

LESSONS.append((A2_2, 'passiveVoice', 20035,
  '    { id: 20035, type: \'multiple-choice\', instruction: "Active vs Passive voice:",'
  '\n      question: "The chef _____ the meal. The meal _____ by the chef.",'
  '\n      options: [\'cooked / was cooked\', \'was cooked / cooked\', \'cooks / is cook\', \'is cooking / was cooking\'],'
  '\n      correct: \'cooked / was cooked\','
  '\n      explanation: "Active (chef cooked) vs Passive (meal was cooked). Bir gap, ikki xil perspektiv." },'
  '\n    { id: 20036, type: \'fill-blank\', instruction: "Present Simple vs Past Simple passive:",'
  '\n      question: "English _____ (speak) all over the world. This bridge _____ (build) in 1990.",'
  '\n      blanks: [\'is spoken\', \'was built\'],'
  '\n      explanation: "Present passive: is/are + V3. Past passive: was/were + V3. Zamon o\'zgarishi bilan be verb o\'zgaradi." },'
  '\n    { id: 20037, type: \'error-correction\', instruction: "Passive with by + agent:",'
  '\n      question: "The window was broke by the boy. The cake was made my mother.",'
  '\n      errorPart: \'broke\','
  '\n      correct: "The window was broken by the boy. The cake was made by my mother.",'
  '\n      explanation: "Passive = be + V3 (was broken). Agent \u2192 \'by\' (by my mother). Not \'by\' omission is wrong." },'
  '\n    { id: 20038, type: \'fill-blank\', instruction: "Active \u2192 Passive (change subject/object):",'
  '\n      question: "Someone stole my phone. (passive) My phone _____ _____.",'
  '\n      blanks: [\'was stolen\'],'
  '\n      explanation: "Active object (my phone) \u2192 Passive subject. Change is/was/were + V3." },'
  '\n    { id: 20039, type: \'transformation\', instruction: "Active \u2192 Passive voice ga o\'zgartiring:",'
  '\n      question: "Shakespeare wrote Hamlet. (change to passive)",'
  '\n      hint: \'Hamlet ...\','
  '\n      correct: \'Hamlet was written by Shakespeare.\','
  '\n      explanation: "Active (Shakespeare wrote) \u2192 Passive (was written by). Focus shifts from doer to action." },'
))

LESSONS.append((A2_2, 'reportedSpeech', 20040,
  '    { id: 20040, type: \'multiple-choice\', instruction: "Direct vs Reported speech (present \u2192 past):",'
  '\n      question: "She said: \'I like coffee.\' She said that she _____ coffee.",'
  '\n      options: [\'liked\', \'likes\', \'is liking\', \'has liked\'],'
  '\n      correct: \'liked\','
  '\n      explanation: "Direct (like) \u2192 Reported (liked). Present \u2192 Past karra backshift." },'
  '\n    { id: 20041, type: \'fill-blank\', instruction: "Reported speech: verb tense backshift:",'
  '\n      question: "He said: \'I will come.\' He said that he _____ come. \'I am tired\' \u2192 He said he _____ tired.",'
  '\n      blanks: [\'would\', \'was\'],'
  '\n      explanation: "\'Will\' \u2192 \'would\'. \'Am\' \u2192 \'was\'. Reporting verb o\'tganda zamon o\'tgan bo\'ladi." },'
  '\n    { id: 20042, type: \'error-correction\', instruction: "Reported question word order:",'
  '\n      question: "She asked where do I live. He asked what is my name.",'
  '\n      errorPart: \'where do I live\','
  '\n      correct: "She asked where I lived. He asked what my name was.",'
  '\n      explanation: "Reported questions = statement order (no inversion). Also backshift tenses: live \u2192 lived, is \u2192 was." },'
  '\n    { id: 20043, type: \'fill-blank\', instruction: "Reported commands (tell + to-infinitive):",'
  '\n      question: "He said: \'Sit down!\' He told me _____ _____. \'Don\'t talk!\' \u2192 He told me _____ _____.",'
  '\n      blanks: [\'to sit down\', \'not to talk\'],'
  '\n      explanation: "Direct command (Sit!) \u2192 Reported (told me to sit). Negative: told me not to." },'
  '\n    { id: 20044, type: \'transformation\', instruction: "Direct \u2192 Reported speech ga o\'zgartiring:",'
  '\n      question: "\'I have finished my homework,\' she said.",'
  '\n      hint: \'She said that ...\','
  '\n      correct: \'She said that she had finished her homework.\','
  '\n      explanation: "\'Have finished\' (present perfect) \u2192 \'had finished\' (past perfect). Backshift in reported speech." },'
))

LESSONS.append((A2_2, 'firstConditional', 20045,
  '    { id: 20045, type: \'multiple-choice\', instruction: "Zero vs First conditional:",'
  '\n      question: "If you _____ water, it boils. If it _____ tomorrow, we will cancel.",'
  '\n      options: [\'heat / rains\', \'will heat / will rain\', \'heated / rained\', \'are heating / is raining\'],'
  '\n      correct: \'heat / rains\','
  '\n      explanation: "Zero = general truth (if + present, present). First = real future (if + present, will + V1). Ikki xil conditional." },'
  '\n    { id: 20046, type: \'fill-blank\', instruction: "First conditional vs Time clause (when):",'
  '\n      question: "If it _____ (rain), I will stay home. When I _____ (get) home, I will call you.",'
  '\n      blanks: [\'rains\', \'get\'],'
  '\n      explanation: "Both use Present Simple in if/when clause + will in main clause. Bir xil qoida, turli connector." },'
  '\n    { id: 20047, type: \'error-correction\', instruction: "Future tense in if-clause (wrong):",'
  '\n      question: "If it will rain tomorrow, I will stay home. When I will arrive, I will call.",'
  '\n      errorPart: \'will rain\','
  '\n      correct: "If it rains tomorrow, I will stay home. When I arrive, I will call.",'
  '\n      explanation: "If/when clauses: Present Simple, NOT Future Simple. Will is only in the main clause." },'
  '\n    { id: 20048, type: \'fill-blank\', instruction: "Unless = If + not:",'
  '\n      question: "I will go, if it doesn\'t rain. = I will go _____ it _____.",'
  '\n      blanks: [\'unless it rains\'],'
  '\n      explanation: "\'If not\' \u2192 \'unless\'. Bir xil ma\'no, ikki xil ifoda. Conditional + negative." },'
  '\n    { id: 20049, type: \'transformation\', instruction: "First conditional \u2192 Second conditional (change meaning):",'
  '\n      question: "If it rains, I will stay home. (change to: unreal/impossible)",'
  '\n      hint: \'If it rained ...\','
  '\n      correct: \'If it rained, I would stay home.\','
  '\n      explanation: "First (real) \u2192 Second (unreal). Present tense \u2192 Past tense. Will \u2192 Would. Ehtimollik darajasi o\'zgaradi." },'
))

# ── A2 Part 3: a2Part3.ts ─────────────────────────────────────────────────
A2_3 = 'src/data/daily/a2Part3.ts'

LESSONS.append((A2_3, 'verbPatterns', 20050,
  '    { id: 20050, type: \'multiple-choice\', instruction: "Verb + infinitive vs Verb + -ing:",'
  '\n      question: "I decided _____ a new job. I avoid _____ fast food.",'
  '\n      options: [\'to take / eating\', \'taking / to eat\', \'to take / to eat\', \'take / eat\'],'
  '\n      correct: \'to take / eating\','
  '\n      explanation: "Decide + to (take). Avoid + -ing (eating). Turli verb patterns, turli qo\'shimchalar." },'
  '\n    { id: 20051, type: \'fill-blank\', instruction: "Verb + preposition + -ing:",'
  '\n      question: "I am interested _____ (learn) English. She is good _____ (play) tennis.",'
  '\n      blanks: [\'in learning\', \'at playing\'],'
  '\n      explanation: "\'Interested in + -ing\'. \'Good at + -ing\'. Prepositiondan keyin doim -ing." },'
  '\n    { id: 20052, type: \'error-correction\', instruction: "Verb + to vs Verb + -ing pattern:",'
  '\n      question: "I enjoy to play football. She suggested to go there.",'
  '\n      errorPart: \'to play\','
  '\n      correct: "I enjoy playing football. She suggested going there.",'
  '\n      explanation: "Enjoy + -ing (not to). Suggest + -ing (not to). Ba\'zi verblar faqat -ing oladi." },'
  '\n    { id: 20053, type: \'fill-blank\', instruction: "Let vs Make (causative patterns):",'
  '\n      question: "My parents let me _____ (stay) up late. My teacher made me _____ (do) the homework again.",'
  '\n      blanks: [\'stay\', \'do\'],'
  '\n      explanation: "Let + V1 (allow). Make + V1 (force). Both without to. Kichik verb, katta ma\'no farqi." },'
  '\n    { id: 20054, type: \'transformation\', instruction: "Verb pattern \u2192 Different pattern (same meaning):",'
  '\n      question: "He started to work here. (change to: -ing form)",'
  '\n      hint: \'He started ...\','
  '\n      correct: \'He started working here.\','
  '\n      explanation: "\'Started to work\' = \'started working\'. Ba\'zi verblar ikkala pattern bilan bir xil ma\'no beradi." },'
))

LESSONS.append((A2_3, 'timePrepositions', 20055,
  '    { id: 20055, type: \'multiple-choice\', instruction: "In/On/At (time) vs In/On/At (place):",'
  '\n      question: "The meeting is _____ 3 PM. It is _____ Monday. We are _____ room 5.",'
  '\n      options: [\'at / on / in\', \'in / at / on\', \'on / in / at\', \'at / in / on\'],'
  '\n      correct: \'at / on / in\','
  '\n      explanation: "\'At 3 PM\' (specific time). \'On Monday\' (day). \'In room 5\' (place). Bir gapda uch xil preposition." },'
  '\n    { id: 20056, type: \'fill-blank\', instruction: "For vs Since (duration vs starting point):",'
  '\n      question: "I have lived here _____ 5 years. I have lived here _____ 2020.",'
  '\n      blanks: [\'for\', \'since\'],'
  '\n      explanation: "\'For + duration\' (5 years). \'Since + starting point\' (2020). Bir xil zamon, turli vaqt ifodalari." },'
  '\n    { id: 20057, type: \'error-correction\', instruction: "During vs For vs While:",'
  '\n      question: "I slept during three hours. I fell asleep for the movie.",'
  '\n      errorPart: \'during three hours\','
  '\n      correct: "I slept for three hours. I fell asleep during the movie.",'
  '\n      explanation: "\'For + duration\' (for 3 hours). \'During + event\' (during the movie). Do not mix them." },'
  '\n    { id: 20058, type: \'fill-blank\', instruction: "Until vs By (deadline vs continuous):",'
  '\n      question: "I will wait _____ you arrive. Please finish _____ 5 PM.",'
  '\n      blanks: [\'until\', \'by\'],'
  '\n      explanation: "\'Until\' = continuous up to a point. \'By\' = deadline/completion before a point." },'
  '\n    { id: 20059, type: \'transformation\', instruction: "Change time preposition to change meaning:",'
  '\n      question: "I will be there in 5 minutes. (change to: I need 5 minutes)",'
  '\n      hint: \'I will be there ...\','
  '\n      correct: \'I will be there within 5 minutes.\','
  '\n      explanation: "\'In 5 minutes\' = after 5 min. \'Within 5 minutes\' = any time before 5 min. Preposition ma\'noni o\'zgartiradi." },'
))

LESSONS.append((A2_3, 'thereIsThereAre', 20060,
  '    { id: 20060, type: \'multiple-choice\', instruction: "There is vs There are (singular vs plural):',"
  '\n      question: "_____ a book on the table. _____ many students in the class.",'
  '\n      options: [\'There is / There are\', \'There are / There is\', \'It is / They are\', \'This is / Those are\'],'
  '\n      correct: \'There is / There are\','
  '\n      explanation: "\'There is + singular\' (a book). \'There are + plural\' (many students). Mavjudlikni ifodalash." },'
  '\n    { id: 20061, type: \'fill-blank\', instruction: "There is/are vs It is (existential vs specific):",'
  '\n      question: "_____ a big park in the city. _____ very beautiful.",'
  '\n      blanks: [\'There is\', \'It is\'],'
  '\n      explanation: "\'There is\' = existence (mavjud). \'It is\' = describing the specific thing (tavsif). Ikki xil tuzilma." },'
  '\n    { id: 20062, type: \'error-correction\', instruction: "There is vs There are (agreement):",'
  '\n      question: "There is many problems. There are a book on the shelf.",'
  '\n      errorPart: \'There is many\','
  '\n      correct: "There are many problems. There is a book on the shelf.",'
  '\n      explanation: "\'Many problems\' (plural) \u2192 There are. \'A book\' (singular) \u2192 There is. Subject-verb agreement." },'
  '\n    { id: 20063, type: \'fill-blank\', instruction: "There was/were (past) vs There is/are (present):",'
  '\n      question: "Last year, there _____ a festival. Now, there _____ more people.",'
  '\n      blanks: [\'was\', \'are\'],'
  '\n      explanation: "\'Last year\' (past) \u2192 there was. \'Now\' (present) \u2192 there are. Zamon o\'zgarishi bilan verb o\'zgaradi." },'
  '\n    { id: 20064, type: \'transformation\', instruction: "There is/are \u2192 There was/were (change time):",'
  '\n      question: "There are many people here now. (change to: last year)",'
  '\n      hint: \'Last year, there ...\','
  '\n      correct: \'Last year, there were many people here.\','
  '\n      explanation: "Present (there are) \u2192 Past (there were). Time reference o\'zgarganda verb shakli ham o\'zgaradi." },'
))

LESSONS.append((A2_3, 'possessives', 20065,
  '    { id: 20065, type: \'multiple-choice\', instruction: "Possessive \'s vs Possessive adjective:",'
  '\n      question: "This is _____ book. The book is _____.",'
  '\n      options: [\'my / mine\', \'mine / my\', \'me / my\', \'I / mine\'],'
  '\n      correct: \'my / mine\','
  '\n      explanation: "\'My\' = possessive adjective + noun (my book). \'Mine\' = possessive pronoun (no noun). Bir gapda ikki xil." },'
  '\n    { id: 20066, type: \'fill-blank\', instruction: "Possessive \'s vs Plural -s:",'
  '\n      question: "The _____ (students/student\'s) books are on the table. The _____ (students/student\'s) are studying.",'
  '\n      blanks: [\'students\'\', \'students\'],'
  '\n      explanation: "\'Students\' books\' = possession (books of students). \'Students are studying\' = plural (no apostrophe). Farqli ma\'no." },'
  '\n    { id: 20067, type: \'error-correction\', instruction: "Its vs It\'s (possessive vs contraction):",'
  '\n      question: "The dog wagged it\'s tail. Its a beautiful day.",'
  '\n      errorPart: \'it\'s tail\','
  '\n      correct: "The dog wagged its tail. It\'s a beautiful day.",'
  '\n      explanation: "\'Its\' = possessive (uning). \'It\'s\' = it is (bu). Apostrophe o\'rniga qarab ma\'no o\'zgaradi." },'
  '\n    { id: 20068, type: \'fill-blank\', instruction: "Whose vs Who\'s (possessive vs contraction):",'
  '\n      question: "_____ book is this? _____ your teacher?",'
  '\n      blanks: [\'Whose\', \'Who\'s\'],'
  '\n      explanation: "\'Whose\' = possession (kimning). \'Who\'s\' = who is (kim). Bir xil talaffuz, turli ma\'no." },'
  '\n    { id: 20069, type: \'transformation\', instruction: "Possessive adjective \u2192 Possessive pronoun:",'
  '\n      question: "This is my phone. (change using: mine)",'
  '\n      hint: \'This phone ...\','
  '\n      correct: \'This phone is mine.\','
  '\n      explanation: "\'My phone\' (adj + noun) \u2192 \'is mine\' (pronoun). Possessive pronoun noun o\'rnida ishlatiladi." },'
))

LESSONS.append((A2_3, 'someAnyNoEvery', 20070,
  '    { id: 20070, type: \'multiple-choice\', instruction: "Some vs Any (positive vs negative):",'
  '\n      question: "I have _____ money. I don\'t have _____ time.",'
  '\n      options: [\'some / any\', \'any / some\', \'no / some\', \'some / no\'],'
  '\n      correct: \'some / any\','
  '\n      explanation: "Positive \u2192 some. Negative \u2192 any. Bir gapda ikki xil compound." },'
  '\n    { id: 20071, type: \'fill-blank\', instruction: "Something vs Anything vs Nothing:",'
  '\n      question: "I heard _____ (something/anything) but I\'m not sure. I heard _____ (nothing/anything) at all.",'
  '\n      blanks: [\'something\', \'nothing\'],'
  '\n      explanation: "\'Something\' = something exists. \'Nothing\' = zero. Bir xil kontekst, qarama-qarshi ma\'no." },'
  '\n    { id: 20072, type: \'error-correction\', instruction: "Double negative error:",'
  '\n      question: "I didn\'t see nobody. She doesn\'t want nothing.",'
  '\n      errorPart: \'nobody\','
  '\n      correct: "I didn\'t see anybody. She doesn\'t want anything.",'
  '\n      explanation: "English does NOT use double negatives. \'Didn\'t see nobody\' \u2192 \'didn\'t see anybody\'." },'
  '\n    { id: 20073, type: \'fill-blank\', instruction: "Everybody vs Everything vs Everywhere:",'
  '\n      question: "_____ (everybody/everything) in the room was happy. _____ (everybody/everything) was clean.",'
  '\n      blanks: [\'Everybody\', \'Everything\'],'
  '\n      explanation: "\'Everybody\' = people. \'Everything\' = things. Every-compounds refer to specific categories." },'
  '\n    { id: 20074, type: \'transformation\', instruction: "Some/any \u2192 No compound (change meaning):",'
  '\n      question: "There is somebody in the room. (change to: nobody)",'
  '\n      hint: \'There is ...\','
  '\n      correct: \'There is nobody in the room.\','
  '\n      explanation: "\'Somebody\' (someone exists) \u2192 \'nobody\' (no one). Bir compoundni qarama-qarshisiga o\'zgartirish." },'
))

# ── A2 Part 4: a2Part4.ts ─────────────────────────────────────────────────
A2_4 = 'src/data/daily/a2Part4.ts'

LESSONS.append((A2_4, 'presentContinuousFuture', 20075,
  '    { id: 20075, type: \'multiple-choice\', instruction: "Present Continuous (now) vs Present Continuous (future):",'
  '\n      question: "I _____ a movie right now. I _____ a movie tomorrow evening.",'
  '\n      options: [\'am watching / am watching\', \'watch / am watching\', \'am watching / watch\', \'watch / watch\'],'
  '\n      correct: \'am watching / am watching\','
  '\n      explanation: "Same form (am watching), different time (now vs tomorrow). Context determines meaning." },'
  '\n    { id: 20076, type: \'fill-blank\', instruction: "Present Continuous (future) vs Be going to:",'
  '\n      question: "I _____ (meet) my friends tonight (arrangement). It _____ (rain) (prediction based on clouds).",'
  '\n      blanks: [\'am meeting\', \'is going to rain\'],'
  '\n      explanation: "\'Am meeting\' = arrangement (Present Continuous). \'Is going to rain\' = prediction (be going to). Turli future forms." },'
  '\n    { id: 20077, type: \'error-correction\', instruction: "Future time expression with Present Simple (wrong):",'
  '\n      question: "I am going to the cinema yesterday. She is visiting him next month last week.",'
  '\n      errorPart: \'yesterday\','
  '\n      correct: "I am going to the cinema tomorrow. She is visiting him next month.",'
  '\n      explanation: "Present Continuous for future \u2192 future time markers (tomorrow, next week). Not past markers." },'
  '\n    { id: 20078, type: \'fill-blank\', instruction: "Present Continuous (arrangement) vs Will (decision now):",'
  '\n      question: "I _____ (meet) her at 6 (planned). OK, I _____ (help) you (spontaneous decision).",'
  '\n      blanks: [\'am meeting\', \'will help\'],'
  '\n      explanation: "\'Am meeting\' = planned arrangement. \'Will help\' = decision made at moment of speaking." },'
  '\n    { id: 20079, type: \'transformation\', instruction: "Present (now) \u2192 Present (future) meaning:",'
  '\n      question: "I am cooking dinner. (change to: an arrangement for tomorrow)",'
  '\n      hint: \'I am cooking ...\','
  '\n      correct: \'I am cooking dinner tomorrow night.\','
  '\n      explanation: "Same form + future time marker = future meaning. Context (now vs tomorrow) changes interpretation." },'
))

LESSONS.append((A2_4, 'quantifiers', 20080,
  '    { id: 20080, type: \'multiple-choice\', instruction: "Some/Any vs Much/Many:",'
  '\n      question: "I have _____ friends. I don\'t have _____ money. How _____ time do we have?",'
  '\n      options: [\'some / any / much\', \'any / some / many\', \'much / many / some\', \'many / much / any\'],'
  '\n      correct: \'some / any / much\','
  '\n      explanation: "\'Friends\' (pos) \u2192 some. \'Money\' (neg) \u2192 any. \'Time\' (uncountable question) \u2192 much." },'
  '\n    { id: 20081, type: \'fill-blank\', instruction: "A few vs A little vs A lot of:",'
  '\n      question: "I have _____ (a few/a little) close friends. There is _____ (a few/a little) milk left. I read _____ (a lot of/little) books.",'
  '\n      blanks: [\'a few\', \'a little\', \'a lot of\'],'
  '\n      explanation: "\'Friends\' (countable) \u2192 a few. \'Milk\' (uncountable) \u2192 a little. \'Books\' (plural) \u2192 a lot of." },'
  '\n    { id: 20082, type: \'error-correction\', instruction: "A lot vs Many (positive statements):",'
  '\n      question: "She has a lot of books. There is much water on the floor.",'
  '\n      errorPart: \'much water\','
  '\n      correct: "She has a lot of books. There is a lot of water on the floor.",'
  '\n      explanation: "\'A lot of\' is used in positive statements. \'Much\' is typically for questions/negatives." },'
  '\n    { id: 20083, type: \'fill-blank\', instruction: "Each vs Every (individual vs general):",'
  '\n      question: "_____ (each/every) student received a certificate. _____ (each/every) child needs love.",'
  '\n      blanks: [\'Each\', \'Every\'],'
  '\n      explanation: "\'Each\' = individual focus (har biri). \'Every\' = general group (hamma). Subtle difference in meaning." },'
  '\n    { id: 20084, type: \'transformation\', instruction: "Change quantifier to change meaning:",'
  '\n      question: "I have some apples. (change to: fewer quantity)",'
  '\n      hint: \'I have ...\','
  '\n      correct: \'I have a few apples.\','
  '\n      explanation: "\'Some\' \u2192 \'a few\'. Small change in quantifier = different nuance of quantity." },'
))

LESSONS.append((A2_4, 'tooEnough', 20085,
  '    { id: 20085, type: \'multiple-choice\', instruction: "Too + adjective vs Not + adjective + enough:",'
  '\n      question: "This coffee is _____ hot to drink (excessive). This coffee is not cool _____ to drink.",'
  '\n      options: [\'too / enough\', \'enough / too\', \'very / too\', \'so / enough\'],'
  '\n      correct: \'too / enough\','
  '\n      explanation: "\'Too hot\' = too much (excessive). \'Cool enough\' = sufficient. Bir gapda ikki xil pattern." },'
  '\n    { id: 20086, type: \'fill-blank\', instruction: "Too vs Very (negative vs neutral):",'
  '\n      question: "This box is _____ heavy for me to lift (cannot lift). This box is _____ heavy (just describing).",'
  '\n      blanks: [\'too\', \'very\'],'
  '\n      explanation: "\'Too\' = negative result (cannot lift). \'Very\' = just describing (no result). Farqli ma\'no." },'
  '\n    { id: 20087, type: \'error-correction\', instruction: "Position of enough (adjective vs noun):",'
  '\n      question: "I have enough money. The water is enough hot.",'
  '\n      errorPart: \'enough hot\','
  '\n      correct: "I have enough money. The water is hot enough.",'
  '\n      explanation: "\'Enough + noun\' (enough money). \'Adjective + enough\' (hot enough). Position changes with word type." },'
  '\n    { id: 20088, type: \'fill-blank\', instruction: "Too/Enough + to-infinitive:",'
  '\n      question: "She is too tired _____ (go) out. He is smart enough _____ (pass) the test.",'
  '\n      blanks: [\'to go\', \'to pass\'],'
  '\n      explanation: "Too + adj + to + V1 (excessive = cannot). Adj + enough + to + V1 (sufficient = can)." },'
  '\n    { id: 20089, type: \'transformation\', instruction: "Too \u2192 Enough (opposite meaning):",'
  '\n      question: "The water is too cold to swim. (change to: it is warm enough)",'
  '\n      hint: \'The water is ...\','
  '\n      correct: \'The water is not warm enough to swim.\','
  '\n      explanation: "\'Too cold\' (cannot) \u2192 \'not warm enough\' (also cannot). Opposite structure, same negative result." },'
))

LESSONS.append((A2_4, 'soSuch', 20090,
  '    { id: 20090, type: \'multiple-choice\', instruction: "So + adjective vs Such + noun phrase:",'
  '\n      question: "She is _____ kind. She is _____ a kind person.",'
  '\n      options: [\'so / such\', \'such / so\', \'very / so\', \'so / very\'],'
  '\n      correct: \'so / such\','
  '\n      explanation: "\'So + adjective\' (so kind). \'Such + noun phrase\' (such a kind person). Bir gapda ikki xil intensifier." },'
  '\n    { id: 20091, type: \'fill-blank\', instruction: "So vs Such (with/without noun):",'
  '\n      question: "The music was _____ loud. It was _____ loud music.",'
  '\n      blanks: [\'so\', \'such\'],'
  '\n      explanation: "\'So loud\' = so + adj (no noun). \'Such loud music\' = such + adj + noun (with noun)." },'
  '\n    { id: 20092, type: \'error-correction\', instruction: "So/Such + that (result clause):",'
  '\n      question: "It was so hot that we stayed inside. It was such beautiful weather that we went out.",'
  '\n      errorPart: \'such beautiful weather that\','
  '\n      correct: "It was so hot that we stayed inside. It was such beautiful weather that we went out.",'
  '\n      explanation: "Both are correct! \'So + adj + that\' and \'Such + noun + that\' both show result. Different patterns." },'
  '\n    { id: 20093, type: \'fill-blank\', instruction: "So many/much vs Such a lot of:",'
  '\n      question: "There were _____ many people! There was _____ much food! It was _____ a big event!",'
  '\n      blanks: [\'so\', \'so\', \'such\'],'
  '\n      explanation: "\'So many/much + noun\'. \'Such a + adj + noun\'. Turli quantifierlar bilan ishlatish." },'
  '\n    { id: 20094, type: \'transformation\', instruction: "So \u2192 Such ga o\'zgartiring:",'
  '\n      question: "The book was so interesting that I couldn\'t stop. (change: use such)",'
  '\n      hint: \'It was ...\','
  '\n      correct: \'It was such an interesting book that I couldn\'t stop.\','
  '\n      explanation: "\'So interesting\' (so + adj) \u2192 \'such an interesting book\' (such + noun phrase). Struktura o\'zgaradi." },'
))

LESSONS.append((A2_4, 'a2Review2', 20095,
  '    { id: 20095, type: \'multiple-choice\', instruction: "Review: Various grammar topics combined:",'
  '\n      question: "I _____ (go) to Tashkent next week. I _____ (visit) my family there.",'
  '\n      options: [\'am going / will visit\', \'go / visit\', \'will go / am visiting\', \'went / visited\'],'
  '\n      correct: \'am going / will visit\','
  '\n      explanation: "\'Am going\' = arrangement (PC for future). \'Will visit\' = plan (Future Simple). Bir gapda ikki xil future." },'
  '\n    { id: 20096, type: \'fill-blank\', instruction: "Review: Mixing tenses in context:",'
  '\n      question: "I _____ (study) English for 2 years. Before that, I _____ (study) French at school.",'
  '\n      blanks: [\'have studied\', \'studied\'],'
  '\n      explanation: "\'For 2 years\' = Present Perfect (up to now). \'Before that\' = Past Simple (completed past)." },'
  '\n    { id: 20097, type: \'error-correction\', instruction: "Review: Article + tense + preposition:",'
  '\n      question: "I have been to the USA in 2019. I am interesting in learn English.",'
  '\n      errorPart: \'in 2019\','
  '\n      correct: "I went to the USA in 2019. I am interested in learning English.",'
  '\n      explanation: "\'In 2019\' (specific past) \u2192 Past Simple. \'Interested in + -ing\'. Bir gapda uch xil xato." },'
  '\n    { id: 20098, type: \'fill-blank\', instruction: "Review: Conditional + wish + modal:",'
  '\n      question: "If I _____ (have) time, I will call. I wish I _____ (be) richer. You _____ (must) try this!",'
  '\n      blanks: [\'have\', \'were\', \'must\'],'
  '\n      explanation: "First conditional (have), wish (were subjunctive), modal (must). Bir gapda uch xil tuzilma." },'
  '\n    { id: 20099, type: \'transformation\', instruction: "Review: Rewrite using different structures:",'
  '\n      question: "I don\'t have a car, so I take the bus. (use: If)",'
  '\n      hint: \'If I ...\','
  '\n      correct: \'If I had a car, I wouldn\'t take the bus.\','
  '\n      explanation: "Fact (don\'t have \u2192 take bus) \u2192 Second conditional (if had, wouldn\'t take). Hypothetical." },'
))

# ── B2 Part 1: b2Part1.ts ─────────────────────────────────────────────────
B2_1 = 'src/data/daily/b2Part1.ts'

LESSONS.append((B2_1, 'unrealPastB2', 70000,
  '    { id: 70000, type: \'multiple-choice\', instruction: "Third conditional vs Past modals of regret:",'
  '\n      question: "If I _____ about the traffic, I _____ earlier. I _____ (should) left earlier.",'
  '\n      options: [\'had known / would have left / should have\', \'knew / would leave / should\', \'have known / will leave / should\', \'would know / left / should\'],'
  '\n      correct: \'had known / would have left / should have\','
  '\n      explanation: "Third conditional (had known/would have left) and \'should have\' for regret. Bir xil ma\'no, turli tuzilmalar." },'
  '\n    { id: 70001, type: \'fill-blank\', instruction: "Wish (regret) vs Third conditional:",'
  '\n      question: "I wish I _____ (study) harder. If I _____ (study) harder, I _____ (pass).",'
  '\n      blanks: [\'had studied\', \'had studied\', \'would have passed\'],'
  '\n      explanation: "\'I wish + had studied\' (regret). Third conditional (If + had studied, would have passed). Bir xil ma\'no." },'
  '\n    { id: 70002, type: \'error-correction\', instruction: "Unreal past \u2014 tense mixture error:",'
  '\n      question: "If I would have known, I would come earlier. I wish I was there yesterday.",'
  '\n      errorPart: \'would have known\','
  '\n      correct: "If I had known, I would have come earlier. I wish I had been there yesterday.",'
  '\n      explanation: "Third conditional: if + had + V3... would have + V3. Wish + past perfect for past regrets." },'
  '\n    { id: 70003, type: \'fill-blank\', instruction: "Unreal past vs Past Simple (fact vs hypothetical):",'
  '\n      question: "I didn\'t go to the party. If I _____ (go), I _____ (meet) her. I wish I _____ (go).",'
  '\n      blanks: [\'had gone\', \'would have met\', \'had gone\'],'
  '\n      explanation: "Fact (didn\'t go) \u2192 Hypothetical (had gone / would have met / wish + had gone). Reality vs imagination." },'
  '\n    { id: 70004, type: \'transformation\', instruction: "Fact \u2192 Unreal past: If only / wish / conditional:",'
  '\n      question: "I didn\'t save money, so I couldn\'t buy a house. (express: regret + third conditional)",'
  '\n      hint: \'If I had ...\','
  '\n      correct: \'If I had saved money, I could have bought a house.\','
  '\n      explanation: "Fact (didn\'t save) \u2192 Third conditional (had saved, could have bought). Past reality \u2192 hypothetical." },'
))

LESSONS.append((B2_1, 'advancedConditionalsB2', 70005,
  '    { id: 70005, type: \'multiple-choice\', instruction: "Mixed conditional (past + present):",'
  '\n      question: "If I _____ (study) medicine, I _____ a doctor now. But I studied art.",'
  '\n      options: [\'had studied / would be\', \'studied / would be\', \'have studied / will be\', \'would study / would have been\'],'
  '\n      correct: \'had studied / would be\','
  '\n      explanation: "Mixed: if + past perfect (past condition) + would + V1 (present result). Past \u2192 Present." },'
  '\n    { id: 70006, type: \'fill-blank\', instruction: "Inverted conditionals (should/were/had):",'
  '\n      question: "_____ it rain, we will cancel. _____ I you, I would accept. _____ I known, I\'d have come.",'
  '\n      blanks: [\'Should\', \'Were\', \'Had\'],'
  '\n      explanation: "Inversion: Should (first), Were (second), Had (third). Removes \'if\', more formal. Interleaved practice." },'
  '\n    { id: 70007, type: \'error-correction\', instruction: "Mixed conditional \u2014 wrong tense combination:",'
  '\n      question: "If I took that job, I would be rich now. If I had studied, I would pass the exam yesterday.",'
  '\n      errorPart: \'would pass the exam yesterday\','
  '\n      correct: "If I had studied, I would have passed the exam yesterday. If I had taken that job, I would be rich now.",'
  '\n      explanation: "Past result (yesterday) \u2192 would have + V3. Present result (now) \u2192 would + V1. Correct tense matching." },'
  '\n    { id: 70008, type: \'fill-blank\', instruction: "Unless/Provided that vs If:",'
  '\n      question: "I\'ll go _____ it rains (= if not). You can pass _____ you study (= if).",'
  '\n      blanks: [\'unless\', \'provided that\'],'
  '\n      explanation: "\'Unless\' = if not. \'Provided that\' = if/on condition. Bir xil conditional, turli connectors." },'
  '\n    { id: 70009, type: \'transformation\', instruction: "Standard conditional \u2192 Inverted conditional:",'
  '\n      question: "If I had known, I would have come. (invert: remove \'if\')",'
  '\n      hint: \'Had I ...\','
  '\n      correct: \'Had I known, I would have come.\','
  '\n      explanation: "Standard (If + had) \u2192 Inverted (Had + subject). More formal and concise." },'
))

# Keep going with the remaining B2 lessons...

# B2 lessons: advancedConditionalsB2 (DONE), nominalizationB2 (next), subjunctiveB2, hedgingB2, complexPrepositionsB2, cohesionB2, registerB2

LESSONS.append((B2_1, 'nominalizationB2', 70010,
  '    { id: 70010, type: \'multiple-choice\', instruction: "Nominalization (noun phrase vs verb clause):",'
  '\n      question: "_____ is important for success. _____ you work hard is also important.",'
  '\n      options: [\'Hard work / That\', \'Working hard / What\', \'Hard working / Which\', \'Work hard / That\'],'
  '\n      correct: \'Hard work / That\','
  '\n      explanation: "\'Hard work\' = nominalization (noun). \'That you work hard\' = noun clause. Bir xil ma\'no, turli tuzilmalar." },'
  '\n    { id: 70011, type: \'fill-blank\', instruction: "Verb \u2192 Noun (nominalization with -tion/-ment):",'
  '\n      question: "The _____ (decide) was difficult. The _____ (develop) of the city was rapid.",'
  '\n      blanks: [\'decision\', \'development\'],'
  '\n      explanation: "Verb (decide/develop) \u2192 Noun (decision/development). -tion and -ment suffixes. Academic vocabulary." },'
  '\n    { id: 70012, type: \'error-correction\', instruction: "Gerund vs Infinitive as subject:",'
  '\n      question: "To swim is good exercise. Swimming is good exercise.",'
  '\n      errorPart: \'To swim\','
  '\n      correct: "Swimming is good exercise. (Both are acceptable, but gerund is more common for general statements)",'
  '\n      explanation: "Both gerund and infinitive can be subjects, but gerund (Swimming) is more natural for general truths." },'
  '\n    { id: 70013, type: \'fill-blank\', instruction: "Nominalization with What/That/It:",'
  '\n      question: "_____ I need is a vacation. _____ she passed surprised everyone. _____ is clear that we must act.",'
  '\n      blanks: [\'What\', \'That\', \'It\'],'
  '\n      explanation: "\'What\' = the thing that. \'That\' = the fact that. \'It\' = dummy subject. Nominalization patterns." },'
  '\n    { id: 70014, type: \'transformation\', instruction: "Verb clause \u2192 Noun phrase (formal writing):",'
  '\n      question: "The company decided to expand. (formal: use decision/noun)",'
  '\n      hint: \'The decision ...\','
  '\n      correct: \'The decision to expand was made by the company.\','
  '\n      explanation: "Verb (decided) \u2192 Noun (decision). Verb clause \u2192 Nominalization. More formal academic style." },'
))

LESSONS.append((B2_1, 'subjunctiveB2', 70015,
  '    { id: 70015, type: \'multiple-choice\', instruction: "Subjunctive vs Indicative (demand/suggestion that):",'
  '\n      question: "I suggest that he _____ early. It is important that she _____ present.",'
  '\n      options: [\'leave / be\', \'leaves / is\', \'left / was\', \'will leave / will be\'],'
  '\n      correct: \'leave / be\','
  '\n      explanation: "Subjunctive = base form (no -s, no tense). Suggest/ask/insist + that + V1. Formal structure." },'
  '\n    { id: 70016, type: \'fill-blank\', instruction: "Subjunctive vs Should + infinitive:",'
  '\n      question: "I recommend that he _____ (see) a doctor. It is vital that she _____ (be) told.",'
  '\n      blanks: [\'see\', \'be\'],'
  '\n      explanation: "Subjunctive uses base V1 (see, be). No \'should\', no tense marking. Formal English." },'
  '\n    { id: 70017, type: \'error-correction\', instruction: "Subjunctive \u2014 third person -s (wrong):",'
  '\n      question: "I insist that he arrives on time. It is essential that she is told.",'
  '\n      errorPart: \'arrives\','
  '\n      correct: "I insist that he arrive on time. It is essential that she be told.",'
  '\n      explanation: "Subjunctive: no -s for third person. No is/are/was. Base form only: arrive, be, tell." },'
  '\n    { id: 70018, type: \'fill-blank\', instruction: "Subjunctive vs Modal (should/must):",'
  '\n      question: "I suggest that he _____ (go). = I suggest that he _____ (should) go.",'
  '\n      blanks: [\'go\', \'should\'],'
  '\n      explanation: "Subjunctive (go) = Should + V1 (should go). Same meaning, different formality levels." },'
  '\n    { id: 70019, type: \'transformation\', instruction: "Indicative \u2192 Subjunctive (formal):",'
  '\n      question: "It is important that she is informed. (formal subjunctive)",'
  '\n      hint: \'It is important that she ...\','
  '\n      correct: \'It is important that she be informed.\','
  '\n      explanation: "Indicative (is informed) \u2192 Subjunctive (be informed). Formal/academic subjunctive usage." },'
))

LESSONS.append((B2_1, 'hedgingB2', 70020,
  '    { id: 70020, type: \'multiple-choice\', instruction: "Hedging vs Strong claim (certainty vs caution):",'
  '\n      question: "This _____ the best solution. (100% sure) This _____ the best solution. (not sure)",'
  '\n      options: [\'is / might be\', \'might be / is\', \'must be / is\', \'could be / must be\'],'
  '\n      correct: \'is / might be\','
  '\n      explanation: "\'Is\' = strong claim. \'Might be\' = hedged/uncertain. Turli darajadagi ishonch." },'
  '\n    { id: 70021, type: \'fill-blank\', instruction: "Hedging with It seems/It appears vs It is clear:",'
  '\n      question: "_____ that the economy is improving (strong). _____ that the economy might improve (hedged).",'
  '\n      blanks: [\'It is clear\', \'It seems\'],'
  '\n      explanation: "\'It is clear\' = strong claim. \'It seems\' = hedged/less certain." },'
  '\n    { id: 70022, type: \'error-correction\', instruction: "Hedging \u2014 double hedge (over-hedging):",'
  '\n      question: "It might possibly perhaps be somewhat likely that the results could maybe show improvement.",'
  '\n      errorPart: \'possibly perhaps\','
  '\n      correct: "It might be that the results show improvement.",'
  '\n      explanation: "Multiple hedges = weak writing. One hedge per claim is enough. Academic writing balance." },'
  '\n    { id: 70023, type: \'fill-blank\', instruction: "Hedging vs Fact (academic writing):",'
  '\n      question: "_____ that water boils at 100C (fact). _____ that global temperatures are rising (hedged claim).",'
  '\n      blanks: [\'It is known\', \'There is evidence\'],'
  '\n      explanation: "Facts = no hedge. Interpretations = hedged (evidence suggests, appears, seems)." },'
  '\n    { id: 70024, type: \'transformation\', instruction: "Strong claim \u2192 Hedged claim:",'
  '\n      question: "This proves our theory is correct. (hedge: suggest)",'
  '\n      hint: \'This ...\','
  '\n      correct: \'This suggests that our theory might be correct.\','
  '\n      explanation: "Strong (proves) \u2192 Hedged (suggests...might be). Adding uncertainty to academic claims." },'
))

# Declare remaining B2 lessons
# complexPrepositionsB2 (70025), cohesionB2 (70030), registerB2 (70035)

LESSONS.append((B2_1, 'complexPrepositionsB2', 70025,
  '    { id: 70025, type: \'multiple-choice\', instruction: "Complex prepositions vs Simple prepositions:",'
  '\n      question: "_____ the weather, we will go. (despite) _____ the delay, we arrived on time. (because of)",'
  '\n      options: [\'In spite of / Due to\', \'Because / Although\', \'Despite of / Owing\', \'Regardless / Thanks\'],'
  '\n      correct: \'In spite of / Due to\','
  '\n      explanation: "\'In spite of\' = despite. \'Due to\' = because of. Complex prepositions = 2+ words. Formal." },'
  '\n    { id: 70026, type: \'fill-blank\', instruction: "In terms of / With regard to / As for:",'
  '\n      question: "_____ cost, this is better. _____ your question, I will answer later. _____ me, I am fine.",'
  '\n      blanks: [\'In terms of\', \'With regard to\', \'As for\'],'
  '\n      explanation: "\'In terms of\' = regarding a specific aspect. \'With regard to\' = concerning. \'As for\' = transitioning topics." },'
  '\n    { id: 70027, type: \'error-correction\', instruction: "Complex preposition word order:",'
  '\n      question: "Due to of the rain, we stayed in. In spite the weather, we went out. According to me, it\'s fine.",'
  '\n      errorPart: \'Due to of\','
  '\n      correct: "Due to the rain, we stayed in. In spite of the weather, we went out. In my opinion, it\'s fine.",'
  '\n      explanation: "\'Due to\' (not \'due to of\'). \'In spite of\' (not \'in spite\'). \'According to\' can\'t be used with me." },'
  '\n    { id: 70028, type: \'fill-blank\', instruction: "Preposition + -ing vs Preposition + noun:",'
  '\n      question: "We succeeded _____ solving the problem. I look forward _____ hearing from you.",'
  '\n      blanks: [\'in\', \'to\'],'
  '\n      explanation: "\'Succeed in + -ing\'. \'Look forward to + -ing\'. Complex preposition patterns with gerunds." },'
  '\n    { id: 70029, type: \'transformation\', instruction: "Simple \u2192 Complex preposition (formal style):",'
  '\n      question: "We didn\'t go because of the rain. (use: on account of)",'
  '\n      hint: \'We didn\'t go ...\','
  '\n      correct: \'We didn\'t go on account of the rain.\','
  '\n      explanation: "\'Because of\' (simple) \u2192 \'on account of\' (complex). More formal academic register." },'
))

LESSONS.append((B2_1, 'cohesionB2', 70030,
  '    { id: 70030, type: \'multiple-choice\', instruction: "Cohesive devices (however/therefore/moreover):",'
  '\n      question: "It was raining. _____, we went out. She is smart; _____, she works hard. He is kind; _____, he helps everyone.",'
  '\n      options: [\'However / moreover / furthermore\', \'Therefore / however / moreover\', \'Moreover / therefore / however\', \'Nevertheless / in addition / meanwhile\'],'
  '\n      correct: \'However / moreover / furthermore\','
  '\n      explanation: "Contrast (however), addition (moreover), emphasis (furthermore). Turli cohesive functions." },'
  '\n    { id: 70031, type: \'fill-blank\', instruction: "Cohesion: Reference words (this/that/these/those):",'
  '\n      question: "We need to reduce costs. _____ is a priority. We must take _____ steps immediately.",'
  '\n      blanks: [\'This\', \'these\'],'
  '\n      explanation: "\'This\' = singular reference. \'These\' = plural reference. Connecting sentences with reference words." },'
  '\n    { id: 70032, type: \'error-correction\', instruction: "Cohesion \u2014 wrong connector:",'
  '\n      question: "She studied hard, however she failed. I like tea, moreover my sister likes coffee.",'
  '\n      errorPart: \'however she failed\','
  '\n      correct: "She studied hard; however, she failed. I like tea, whereas my sister likes coffee.",'
  '\n      explanation: "\'However\' = contrast (needs semicolon or comma). \'Moreover\' = addition (not contrast). Use \'whereas\' for contrast." },'
  '\n    { id: 70033, type: \'fill-blank\', instruction: "Cohesive vs Relative clause:",'
  '\n      question: "The company increased profits. _____, it hired more staff. The company, _____ increased profits, hired more staff.",'
  '\n      blanks: [\'Moreover\', \'which\'],'
  '\n      explanation: "\'Moreover\' = cohesive device (separate sentence). \'Which\' = relative pronoun (same sentence). Turli connection methods." },'
  '\n    { id: 70034, type: \'transformation\', instruction: "Two sentences \u2192 One cohesive sentence:",'
  '\n      question: "The project was difficult. We finished it on time. (combine: despite)",'
  '\n      hint: \'We finished ...\','
  '\n      correct: \'We finished the project on time despite its difficulty.\','
  '\n      explanation: "Two sentences \u2192 one cohesive sentence with \'despite\'. Cohesion = smooth flow of ideas." },'
))

LESSONS.append((B2_1, 'registerB2', 70035,
  '    { id: 70035, type: \'multiple-choice\', instruction: "Formal vs Informal register:",'
  '\n      question: "Informal: The company _____ a lot of money. Formal: The organization _____ significant profits.",'
  '\n      options: [\'made / generated\', \'got / made\', \'did / achieved\', \'had / got\'],'
  '\n      correct: \'made / generated\','
  '\n      explanation: "\'Made\' (informal) vs \'generated\' (formal). Same meaning, different register." },'
  '\n    { id: 70036, type: \'fill-blank\', instruction: "Phrasal verb (informal) vs Single verb (formal):",'
  '\n      question: "We need to _____ (look into/investigate) the issue (formal). I will _____ (check out/examine) the new restaurant (informal).",'
  '\n      blanks: [\'investigate\', \'check out\'],'
  '\n      explanation: "Formal \u2192 single verb (investigate). Informal \u2192 phrasal verb (check out). Choose by context." },'
  '\n    { id: 70037, type: \'error-correction\', instruction: "Register mismatch:",'
  '\n      question: "The CEO was like, we gotta increase profits. The participants were chill with the proposal.",'
  '\n      errorPart: \'was like\','
  '\n      correct: "The CEO stated that the company must increase profits. The participants accepted the proposal.",'
  '\n      explanation: "Business context \u2192 formal register. \'Was like\' and \'chill\' are too informal for professional writing." },'
  '\n    { id: 70038, type: \'fill-blank\', instruction: "Contractions (informal) vs Full forms (formal):",'
  '\n      question: "The results _____ (don\'t/do not) support our hypothesis (formal). I _____ (can\'t/cannot) believe it (informal).",'
  '\n      blanks: [\'do not\', \'can\'t\'],'
  '\n      explanation: "Formal writing \u2192 no contractions (do not). Informal \u2192 contractions (can\'t). Register awareness." },'
  '\n    { id: 70039, type: \'transformation\', instruction: "Informal \u2192 Formal register:",'
  '\n      question: "The company went bust because they messed up. (make formal)",'
  '\n      hint: \'The company ...\','
  '\n      correct: \'The company failed due to operational errors.\','
  '\n      explanation: "\'Went bust\' \u2192 \'failed\'. \'Messed up\' \u2192 \'operational errors\'. Informal \u2192 formal vocabulary." },'
))

# ── B2 Part 2: b2Part2.ts ─────────────────────────────────────────────────
B2_2 = 'src/data/daily/b2Part2.ts'

LESSONS.append((B2_2, 'complexSentencesB2', 70040,
  '    { id: 70040, type: \'multiple-choice\', instruction: "Compound vs Complex sentence:",'
  '\n      question: "I went home, _____ I was tired (compound). I went home _____ I was tired (complex).",'
  '\n      options: [\'and / because\', \'because / and\', \'so / but\', \'although / yet\'],'
  '\n      correct: \'and / because\','
  '\n      explanation: "Compound (two independent clauses + and). Complex (dependent clause + because). Turli sentence types." },'
  '\n    { id: 70041, type: \'fill-blank\', instruction: "Relative clause vs Adverbial clause:",'
  '\n      question: "The man _____ lives next door is kind. (relative) _____ he lives next door, I see him daily. (adverbial)",'
  '\n      blanks: [\'who\', \'Because\'],'
  '\n      explanation: "Relative clause (who = describes noun). Adverbial clause (because = gives reason). Turli clause types." },'
  '\n    { id: 70042, type: \'error-correction\', instruction: "Run-on sentence vs Correct complex sentence:",'
  '\n      question: "I went to the store I bought milk I came home. I went to the store and bought milk, then came home.",'
  '\n      errorPart: \'I went to the store I bought milk\','
  '\n      correct: "I went to the store, bought milk, and came home.",'
  '\n      explanation: "Run-on = no connectors. Correct = conjunctions (and) + punctuation (commas). Complex sentence structure." },'
  '\n    { id: 70043, type: \'fill-blank\', instruction: "Reduced clause vs Full clause:",'
  '\n      question: "_____ (When/When walking) home, I met a friend. _____ (While/While I was) waiting, I read a book.",'
  '\n      blanks: [\'When walking\', \'While waiting\'],'
  '\n      explanation: "Full clause (When I was walking) \u2192 Reduced clause (When walking). Same meaning, shorter form." },'
  '\n    { id: 70044, type: \'transformation\', instruction: "Simple sentence \u2192 Complex sentence:",'
  '\n      question: "I arrived late. The meeting had started. (combine: after)",'
  '\n      hint: \'After I ...\','
  '\n      correct: \'After I arrived late, the meeting had already started.\','
  '\n      explanation: "Two simple sentences \u2192 one complex sentence with subordinating conjunction (after)." },'
))

LESSONS.append((B2_2, 'advancedModalsB2', 70045,
  '    { id: 70045, type: \'multiple-choice\', instruction: "Modals of deduction (present vs past):",'
  '\n      question: "He _____ at home (I\'m sure now). He _____ at home (I\'m sure then \u2014 past).",'
  '\n      options: [\'must be / must have been\', \'might be / might be\', \'can\'t be / must be\', \'should be / should have been\'],'
  '\n      correct: \'must be / must have been\','
  '\n      explanation: "Present ded. (must be) vs Past ded. (must have been). Zamon o\'zgarishi bilan modal structure o\'zgaradi." },'
  '\n    { id: 70046, type: \'fill-blank\', instruction: "Needn\'t have vs Didn\'t need to:",'
  '\n      question: "I _____ (needn\'t have/didn\'t need to) bought it \u2014 it was unnecessary (but I did). I _____ (needn\'t have/didn\'t need to) buy it \u2014 it was unnecessary (and I knew).",'
  '\n      blanks: [\'needn\'t have\', \'didn\'t need to\'],'
  '\n      explanation: "\'Needn\'t have done\' = unnecessary action that happened. \'Didn\'t need to\' = action not done. Subtle difference." },'
  '\n    { id: 70047, type: \'error-correction\', instruction: "Modal + have + V3 structure:",'
  '\n      question: "He must had left early. She could of told me. They should have came earlier.",'
  '\n      errorPart: \'must had\','
  '\n      correct: "He must have left early. She could have told me. They should have come earlier.",'
  '\n      explanation: "Modal + have + V3 (past participle). NOT \'had\', NOT \'of\', NOT past tense." },'
  '\n    { id: 70048, type: \'fill-blank\', instruction: "Can\'t (impossible present) vs Couldn\'t have (impossible past):",'
  '\n      question: "He _____ be at home \u2014 I see his car (present). He _____ have taken it \u2014 he was with me (past).",'
  '\n      blanks: [\'can\'t\', \'couldn\'t\'],'
  '\n      explanation: "Present deduction: can\'t + V1. Past deduction: couldn\'t have + V3. Bir xil mantiq, turli zamon." },'
  '\n    { id: 70049, type: \'transformation\', instruction: "Present deduction \u2192 Past deduction:",'
  '\n      question: "He might be at home. (change to past: maybe he was at home)",'
  '\n      hint: \'He might ...\','
  '\n      correct: \'He might have been at home.\','
  '\n      explanation: "Present (might be) \u2192 Past (might have been). Changing time reference with modals + perfect infinitive." },'
))

# Continue with remaining lessons
LESSONS.append((B2_2, 'contrastiveStructuresB2', 70050,
  '    { id: 70050, type: \'multiple-choice\', instruction: "Although/Despite/In spite of:",'
  '\n      question: "_____ it was raining, we went out. _____ the rain, we went out. _____ raining, we went out.",'
  '\n      options: [\'Although / Despite / In spite of\', \'Despite / Although / In spite of\', \'Even though / Although / Despite\', \'Though / Even though / Yet\'],'
  '\n      correct: \'Although / Despite / In spite of\','
  '\n      explanation: "\'Although + clause\', \'Despite + noun\', \'In spite of + -ing\'. Bir xil contrast, turli grammatik tuzilmalar." },'
  '\n    { id: 70051, type: \'fill-blank\', instruction: "Whereas/While vs However:",'
  '\n      question: "My sister likes tea, _____ I prefer coffee (same sentence). My sister likes tea. _____, I prefer coffee (new sentence).",'
  '\n      blanks: [\'whereas\', \'However\'],'
  '\n      explanation: "\'Whereas\' connects within one sentence. \'However\' starts a new sentence. Turli punctuation." },'
  '\n    { id: 70052, type: \'error-correction\', instruction: "Despite + clause (wrong) vs Despite + noun:",'
  '\n      question: "Despite it was raining, we went out. In spite of the weather was bad, we enjoyed it.",'
  '\n      errorPart: \'Despite it was raining\','
  '\n      correct: "Despite the rain, we went out. In spite of the bad weather, we enjoyed it.",'
  '\n      explanation: "\'Despite\' + noun/-ing (not clause). For clauses, use \'although/even though + subject + verb\'." },'
  '\n    { id: 70053, type: \'fill-blank\', instruction: "Contrast + reason combined:",'
  '\n      question: "_____ the cost was high, we bought it (contrast). We bought it _____ it was useful (reason).",'
  '\n      blanks: [\'Although\', \'because\'],'
  '\n      explanation: "\'Although\' = contrast. \'Because\' = reason. Bir gapda turli logical relationships." },'
  '\n    { id: 70054, type: \'transformation\', instruction: "Two contrastive sentences \u2192 One sentence:",'
  '\n      question: "He is rich. He is not happy. (combine: in spite of)",'
  '\n      hint: \'In spite of ...\','
  '\n      correct: \'In spite of being rich, he is not happy.\','
  '\n      explanation: "Two separate sentences \u2192 one contrastive sentence using \'in spite of + -ing\'." },'
))

LESSONS.append((B2_2, 'punctuationB2', 70055,
  '    { id: 70055, type: \'multiple-choice\', instruction: "Comma vs Semicolon vs Colon:",'
  '\n      question: "I bought apples, bananas _____ oranges (list). I studied hard _____ I passed (two clauses). I need one thing _____ sleep (explanation).",'
  '\n      options: [\', / ; / :\', \'; / : / ,\', \': / ; / ,\', \', / : / ;\'],'
  '\n      correct: \', / ; / :\','
  '\n      explanation: "Comma = list separator. Semicolon = two related clauses. Colon = explanation follows. Turli punctuation functions." },'
  '\n    { id: 70056, type: \'fill-blank\', instruction: "Comma splice vs Correct punctuation:",'
  '\n      question: "I was tired _____ I went to bed. (comma is WRONG here) I was tired _____ I went to bed. (correct: semicolon)",'
  '\n      blanks: [\',\', \';\'],'
  '\n      explanation: "Comma alone between two independent clauses = comma splice (wrong). Semicolon = correct." },'
  '\n    { id: 70057, type: \'error-correction\', instruction: "Apostrophe errors:",'
  '\n      question: "The student\'s are in the class. Its a beautiful day. The childrens toys are here.",'
  '\n      errorPart: \'student\'s are\','
  '\n      correct: "The students are in the class. It\'s a beautiful day. The children\'s toys are here.",'
  '\n      explanation: "\'Student\'s\' = possessive, not plural. \'Its\' = possessive, \'It\'s\' = it is. \'Children\'s\' = irregular possessive." },'
  '\n    { id: 70058, type: \'fill-blank\', instruction: "Quotation marks with other punctuation:",'
  '\n      question: "She said _____I am tired_____ (US: double quotes). He asked _____Are you OK?_____ (UK: single quotes).",'
  '\n      blanks: [\'"\', \'\\\'\'],'
  '\n      explanation: "US English \u2192 double quotes. UK English \u2192 single quotes. Punctuation style varies by region." },'
  '\n    { id: 70059, type: \'transformation\', instruction: "Run-on \u2192 Correctly punctuated:",'
  '\n      question: "I woke up I ate breakfast I went to work (add punctuation)",'
  '\n      hint: \'I ...\','
  '\n      correct: \'I woke up, ate breakfast, and went to work.\','
  '\n      explanation: "Run-on (no punctuation) \u2192 Correct (commas + conjunction). Punctuation creates clarity." },'
))

LESSONS.append((B2_2, 'academicCollocationsB2', 70060,
  '    { id: 70060, type: \'multiple-choice\', instruction: "Verb + noun collocations:",'
  '\n      question: "We need to _____ a decision. She _____ a conclusion. They _____ research.",'
  '\n      options: [\'make / drew / conduct\', \'do / made / do\', \'take / took / make\', \'have / gave / perform\'],'
  '\n      correct: \'make / drew / conduct\','
  '\n      explanation: "\'Make a decision\', \'draw a conclusion\', \'conduct research\'. Fixed verb + noun combinations." },'
  '\n    { id: 70061, type: \'fill-blank\', instruction: "Adjective + noun collocations:",'
  '\n      question: "We had a _____ (strong/high) chance of winning. It was a _____ (hard/difficult) decision.",'
  '\n      blanks: [\'high\', \'difficult\'],'
  '\n      explanation: "\'High chance\' (not strong). \'Difficult decision\' (not hard in formal contexts). Fixed adjective + noun pairs." },'
  '\n    { id: 70062, type: \'error-correction\', instruction: "Wrong collocation:",'
  '\n      question: "I did a mistake. She made a research. He took a photo.",'
  '\n      errorPart: \'did a mistake\','
  '\n      correct: "I made a mistake. She conducted research. He took a photo.",'
  '\n      explanation: "\'Make a mistake\' (not do). \'Conduct research\' (not make). \'Take a photo\' is correct." },'
  '\n    { id: 70063, type: \'fill-blank\', instruction: "Adverb + adjective collocations:",'
  '\n      question: "It is _____ (highly/strongly) recommended. We are _____ (bitterly/deeply) disappointed.",'
  '\n      blanks: [\'highly\', \'deeply\'],'
  '\n      explanation: "\'Highly recommended\', \'deeply disappointed\'. Fixed adverb + adjective pairs in academic English." },'
  '\n    { id: 70064, type: \'transformation\', instruction: "Replace with correct collocation:",'
  '\n      question: "We had a strong chance of success. (fix the collocation)",'
  '\n      hint: \'We had ...\','
  '\n      correct: \'We had a high chance of success.\','
  '\n      explanation: "\'Strong chance\' \u2192 \'high chance\'. Correct collocations make language sound natural." },'
))

LESSONS.append((B2_2, 'criticalThinkingB2', 70065,
  '    { id: 70065, type: \'multiple-choice\', instruction: "Fact vs Opinion vs Inference:",'
  '\n      question: "The Earth orbits the Sun (_____). Coffee is delicious (_____). She looks tired (_____).",'
  '\n      options: [\'fact / opinion / inference\', \'opinion / fact / inference\', \'inference / opinion / fact\', \'fact / inference / opinion\'],'
  '\n      correct: \'fact / opinion / inference\','
  '\n      explanation: "Fact = verifiable. Opinion = personal view. Inference = reasoning from evidence. Turli claim types." },'
  '\n    { id: 70066, type: \'fill-blank\', instruction: "Strong evidence vs Weak evidence:",'
  '\n      question: "A randomized trial provides _____ evidence. One person\'s story provides _____ evidence.",'
  '\n      blanks: [\'strong\', \'weak\'],'
  '\n      explanation: "Scientific studies = strong evidence. Anecdotes = weak evidence. Evaluating evidence quality." },'
  '\n    { id: 70067, type: \'error-correction\', instruction: "Logical fallacy \u2014 hasty generalization:",'
  '\n      question: "I met one rude person from that city, so everyone from there is rude.",'
  '\n      errorPart: \'one rude person\','
  '\n      correct: "I met one rude person from that city, but it would be unfair to generalize about everyone from there.",'
  '\n      explanation: "Hasty generalization = making broad claim from too little evidence. Critical thinking = recognizing this." },'
  '\n    { id: 70068, type: \'fill-blank\', instruction: "Counter-argument structure:",'
  '\n      question: "_____ some people believe X, the evidence suggests Y. Critics _____ that Z is flawed.",'
  '\n      blanks: [\'Although\', \'argue\'],'
  '\n      explanation: "Counter-argument = acknowledge opposing view (Although...), then refute it. Academic debate structure." },'
  '\n    { id: 70069, type: \'transformation\', instruction: "Opinion \u2192 Evidence-based claim:",'
  '\n      question: "I think this medicine works. (add evidence to make it credible)",'
  '\n      hint: \'Studies ...\','
  '\n      correct: \'Studies have shown that this medicine is effective.\','
  '\n      explanation: "Opinion (I think) \u2192 Evidence (studies have shown). Moving from subjective to objective claim." },'
))

LESSONS.append((B2_2, 'b2Review', 70070,
  '    { id: 70070, type: \'multiple-choice\', instruction: "Review: Mixed grammar topics:",'
  '\n      question: "If I _____ harder, I would have passed. I wish I _____ (study). She _____ (must) have left.",'
  '\n      options: [\'had studied / had studied / must\', \'studied / studied / might\', \'would study / have studied / had to\', \'have studied / study / must\'],'
  '\n      correct: \'had studied / had studied / must\','
  '\n      explanation: "Third conditional (had studied), wish + past perfect (had studied), modal deduction (must have). Bir gapda turli tuzilmalar." },'
  '\n    { id: 70071, type: \'fill-blank\', instruction: "Review: Academic register + collocations:",'
  '\n      question: "The study _____ (draws/makes) an important conclusion. It _____ (does/conducts) a thorough analysis.",'
  '\n      blanks: [\'draws\', \'conducts\'],'
  '\n      explanation: "\'Draw a conclusion\', \'conduct an analysis\'. Academic collocations in formal register." },'
  '\n    { id: 70072, type: \'error-correction\', instruction: "Review: Complex structure errors:",'
  '\n      question: "Despite the fact that he was tired, but he continued working. Having said that, however the results were good.",'
  '\n      errorPart: \'but he continued\','
  '\n      correct: "Despite being tired, he continued working. Having said that, the results were good.",'
  '\n      explanation: "\'Despite + clause\' + \'but\' = double conjunction (redundant). Remove either \'despite\' or \'but\'." },'
  '\n    { id: 70073, type: \'fill-blank\', instruction: "Review: Hedging + subjunctive + cohesion:",'
  '\n      question: "The data _____ (suggests/suggest) that the theory is correct. I suggest that he _____ (is/be) informed immediately.",'
  '\n      blanks: [\'suggest\', \'be\'],'
  '\n      explanation: "\'Data suggest\' (plural). \'Suggest that he be\' (subjunctive). Academic grammar precision." },'
  '\n    { id: 70074, type: \'transformation\', instruction: "Review: Informal \u2192 Formal academic:",'
  '\n      question: "The company got better results because they tried hard. (make formal)",'
  '\n      hint: \'The company ...\','
  '\n      correct: \'The company achieved improved results due to increased effort.\','
  '\n      explanation: "Informal (got better, tried hard) \u2192 Formal (achieved improved results, increased effort). Register upgrade." },'
))

# ── B2 Part 3: b2Part3.ts ─────────────────────────────────────────────────
B2_3 = 'src/data/daily/b2Part3.ts'

LESSONS.append((B2_3, 'argumentStructureB2', 70075,
  '    { id: 70075, type: \'multiple-choice\', instruction: "Claim vs Evidence vs Warrant:",'
  '\n      question: "We should invest in solar energy (_____). Solar power is becoming cheaper (_____). If it\'s cheaper, it makes economic sense (_____).",'
  '\n      options: [\'claim / evidence / warrant\', \'evidence / claim / warrant\', \'warrant / evidence / claim\', \'claim / warrant / evidence\'],'
  '\n      correct: \'claim / evidence / warrant\','
  '\n      explanation: "Claim (main argument), Evidence (supporting data), Warrant (logical connection). Argument structure elements." },'
  '\n    { id: 70076, type: \'fill-blank\', instruction: "Thesis statement vs Topic sentence:",'
  '\n      question: "_____ states the main argument of the whole essay. _____ states the main point of one paragraph.",'
  '\n      blanks: [\'Thesis statement\', \'Topic sentence\'],'
  '\n      explanation: "Thesis = entire essay\u2019s main argument. Topic sentence = one paragraph\u2019s main point. Different scope." },'
  '\n    { id: 70077, type: \'error-correction\', instruction: "Weak argument \u2014 circular reasoning:",'
  '\n      question: "This book is good because it is well-written. The author is talented because she writes well.",'
  '\n      errorPart: \'because it is well-written\','
  '\n      correct: "This book is good because it develops complex characters and has an engaging plot.",'
  '\n      explanation: "Circular reasoning = repeating the claim. Strong argument = specific evidence + reasoning." },'
  '\n    { id: 70078, type: \'fill-blank\', instruction: "Concession + Refutation structure:",'
  '\n      question: "_____ some argue that X is true, _____ the evidence strongly suggests Y.",'
  '\n      blanks: [\'While\', \'however\'],'
  '\n      explanation: "Concession (While some argue) + Refutation (evidence suggests Y). Academic argument structure." },'
  '\n    { id: 70079, type: \'transformation\', instruction: "Simple opinion \u2192 Structured argument:",'
  '\n      question: "I think social media is bad. (create a claim + evidence + warrant structure)",'
  '\n      hint: \'Social media is harmful because studies show it increases anxiety. If anxiety increases, mental health declines.\','
  '\n      correct: \'Social media is harmful because studies show it increases anxiety, and increased anxiety leads to declining mental health.\','
  '\n      explanation: "Opinion \u2192 Claim + Evidence (studies show) + Warrant (if...then logic). Structured academic argument." },'
))

LESSONS.append((B2_3, 'stanceMarkersB2', 70080,
  '    { id: 70080, type: \'multiple-choice\', instruction: "Strong vs Weak stance:",'
  '\n      question: "This _____ the best solution (strong). This _____ be the best solution (weak).",'
  '\n      options: [\'is undoubtedly / could\', \'might / is definitely\', \'perhaps / is clearly\', \'is possibly / must\'],'
  '\n      correct: \'is undoubtedly / could\','
  '\n      explanation: "\'Is undoubtedly\' = strong stance. \'Could\' = weak/hedged stance. Stance marker degree." },'
  '\n    { id: 70081, type: \'fill-blank\', instruction: "Stance markers in academic writing:",'
  '\n      question: "_____ (Clearly/Perhaps), this approach is superior. ____ (Undoubtedly/Might), this is the answer.",'
  '\n      blanks: [\'Clearly\', \'Undoubtedly\'],'
  '\n      explanation: "Strong stance markers: Clearly, Undoubtedly, Certainly. Used in confident academic claims." },'
  '\n    { id: 70082, type: \'error-correction\', instruction: "Stance mismatch with evidence:",'
  '\n      question: "Clearly, the results might suggest a trend. This is definitely perhaps the best approach.",'
  '\n      errorPart: \'Clearly...might\','
  '\n      correct: "The results might suggest a trend. This could be the best approach.",'
  '\n      explanation: "\'Clearly\' (strong) + \'might\' (weak) = contradictory stance. Use consistent stance level." },'
  '\n    { id: 70083, type: \'fill-blank\', instruction: "Boosting vs Hedging stance:",'
  '\n      question: "This _____ proves the theory (boost). This _____ suggests the theory (hedge).",'
  '\n      blanks: [\'undoubtedly\', \'tentatively\'],'
  '\n      explanation: "Boosters (undoubtedly) strengthen claim. Hedges (tentatively) weaken claim. Strategic stance choice." },'
  '\n    { id: 70084, type: \'transformation\', instruction: "Hedged \u2192 Strong stance (if evidence allows):",'
  '\n      question: "This might suggest a connection. (change to: strong evidence)",'
  '\n      hint: \'This ...\','
  '\n      correct: \'This clearly demonstrates a connection.\','
  '\n      explanation: "Hedged (might suggest) \u2192 Strong (clearly demonstrates). Stance matches evidence strength." },'
))

LESSONS.append((B2_3, 'paraphrasingB2', 70085,
  '    { id: 70085, type: \'multiple-choice\', instruction: "Synonym substitution vs Structure change:",'
  '\n      question: "Original: The results were significant. Paraphrase 1: _____ Paraphrase 2: _____",'
  '\n      options: [\'The findings were significant / The results were important (synonym)\', \'The results were big / The outcomes were big\', \'Results big / Findings significant\', \'The findings were important / Significant were the results\'],'
  '\n      correct: \'The findings were significant / The results were important (synonym)\','
  '\n      explanation: "Good paraphrase = either synonym substitution OR structure change. Both techniques together = best." },'
  '\n    { id: 70086, type: \'fill-blank\', instruction: "Active \u2192 Passive (paraphrase technique):",'
  '\n      question: "The researchers conducted the study. (paraphrase: passive) The study _____ _____ by the researchers.",'
  '\n      blanks: [\'was conducted\'],'
  '\n      explanation: "Active (researchers conducted) \u2192 Passive (was conducted by researchers). Voice change = paraphrase technique." },'
  '\n    { id: 70087, type: \'error-correction\', instruction: "Too close to original (plagiarism risk):",'
  '\n      question: "Original: \'The economy grew rapidly.\' Student: \'The economy grew fast.\'",'
  '\n      errorPart: \'The economy grew\','
  '\n      correct: "Student: \'There was rapid growth in the economy.\'",'
  '\n      explanation: "Just changing one word (rapidly \u2192 fast) = too close. Restructure the whole sentence for real paraphrase." },'
  '\n    { id: 70088, type: \'fill-blank\', instruction: "Combining paraphrase techniques:",'
  '\n      question: "Original: Many people believe the policy is effective. (paraphrase: It + passive + synonym) _____ _____ that the policy is effective.",'
  '\n      blanks: [\'It is widely believed\'],'
  '\n      explanation: "\'Many people believe\' \u2192 \'It is widely believed\'. Passive + synonym (believe \u2192 widely believed) + structure change." },'
  '\n    { id: 70089, type: \'transformation\', instruction: "Paraphrase the original sentence:",'
  '\n      question: "The government introduced new regulations to reduce pollution.",'
  '\n      hint: \'New regulations ...\','
  '\n      correct: \'New regulations were introduced by the government to decrease pollution.\','
  '\n      explanation: "Active \u2192 Passive (introduced \u2192 were introduced). Synonym (reduce \u2192 decrease). Effective paraphrase = multiple changes." },'
))

LESSONS.append((B2_3, 'advancedVerbPatternsB2', 70090,
  '    { id: 70090, type: \'multiple-choice\', instruction: "Verb + object + infinitive vs Verb + -ing:",'
  '\n      question: "I advised him _____ early. I suggested _____ early.",'
  '\n      options: [\'to leave / leaving\', \'leaving / to leave\', \'leave / leave\', \'to leave / to leave\'],'
  '\n      correct: \'to leave / leaving\','
  '\n      explanation: "\'Advise + object + to\' (advised him to leave). \'Suggest + -ing\' (suggested leaving). Turli verb patterns." },'
  '\n    { id: 70091, type: \'fill-blank\', instruction: "Verb + that clause vs Verb + to-infinitive:",'
  '\n      question: "She agreed _____ (help). She agreed _____ she would help.",'
  '\n      blanks: [\'to help\', \'that\'],'
  '\n      explanation: "Agree + to (to help). Agree + that (that she would). One verb, two possible patterns." },'
  '\n    { id: 70092, type: \'error-correction\', instruction: "Verb pattern \u2014 missing preposition:",'
  '\n      question: "She prevented him to go. He insisted to come.",'
  '\n      errorPart: \'to go\','
  '\n      correct: "She prevented him from going. He insisted on coming.",'
  '\n      explanation: "\'Prevent + from + -ing\'. \'Insist + on + -ing\'. Some verbs require specific prepositions before -ing." },'
  '\n    { id: 70093, type: \'fill-blank\', instruction: "Causative verbs (have/get/make/let):",'
  '\n      question: "I had my assistant _____ (print) the report. I got my assistant _____ (print) the report. I made him _____ (do) it.",'
  '\n      blanks: [\'print\', \'to print\', \'do\'],'
  '\n      explanation: "\'Have + V1\', \'get + to + V1\', \'make + V1\'. Causative verb patterns vary." },'
  '\n    { id: 70094, type: \'transformation\', instruction: "Active verb \u2192 Passive infinitive:",'
  '\n      question: "People believe that he is rich. (use: He is believed)",'
  '\n      hint: \'He is believed ...\','
  '\n      correct: \'He is believed to be rich.\','
  '\n      explanation: "\'Believe that + clause\' \u2192 \'be believed to + V1\'. Personal passive construction." },'
))

LESSONS.append((B2_3, 'b2ComprehensiveReview', 70095,
  '    { id: 70095, type: \'multiple-choice\', instruction: "Review: All B2 grammar:",'
  '\n      question: "_____ the evidence, the theory is flawed. If the data _____ reliable, we would accept it. I suggest that he _____ retested.",'
  '\n      options: [\'Given / were / be\', \'Despite / was / is\', \'With / is / was\', \'Because of / are / being\'],'
  '\n      correct: \'Given / were / be\','
  '\n      explanation: "Complex prep (Given), second conditional (were), subjunctive (be). B2-level grammar in one sentence." },'
  '\n    { id: 70096, type: \'fill-blank\', instruction: "Review: Nominalization + stance + hedging:",'
  '\n      question: "The _____ (implement) of the policy was successful. _____ (clearly/perh.), this approach works.",'
  '\n      blanks: [\'implementation\', \'Clearly\'],'
  '\n      explanation: "Verb (implement) \u2192 Noun (implementation). Strong stance (Clearly) for confident claim." },'
  '\n    { id: 70097, type: \'error-correction\', instruction: "Review: Multiple advanced errors:",'
  '\n      question: "The data suggests that he is the best candidate. I recommend that he is hired immediately. If he would join, the team would be stronger.",'
  '\n      errorPart: \'data suggests\','
  '\n      correct: "The data suggest that he is the best candidate. I recommend that he be hired immediately. If he joined, the team would be stronger.",'
  '\n      explanation: "\'Data\' = plural \u2192 suggest. Subjunctive: \'that he be hired\'. Second cond.: \'If he joined\' (not would join)." },'
  '\n    { id: 70098, type: \'fill-blank\', instruction: "Review: Cohesion + argument structure:",'
  '\n      question: "_____ (Nevertheless/Moreover), the results are promising. _____, we must consider limitations.",'
  '\n      blanks: [\'Nevertheless\', \'However\'],'
  '\n      explanation: "Nevertheless = concession/contrast. However = introducing a contrasting point. Cohesion in argumentative writing." },'
  '\n    { id: 70099, type: \'transformation\', instruction: "Review: All skills combined:",'
  '\n      question: "They think social media causes anxiety. (paraphrase: passive + nominalization + claim)",'
  '\n      hint: \'It is believed ...\','
  '\n      correct: \'It is believed that social media usage causes increased anxiety.\','
  '\n      explanation: "Active (They think) \u2192 Passive (It is believed). Nominalization (causes \u2192 is the cause of). Formal academic paraphrase." },'
))

# ═══════════════════════════════════════════════════════════════════════════
# Main insertion logic
# ═══════════════════════════════════════════════════════════════════════════

files_processed = {}

for (file_path, lesson_id, start_id, exercise_text) in LESSONS:
    if file_path not in files_processed:
        with open(file_path, 'r', encoding='utf-8') as f:
            files_processed[file_path] = f.read()

    content = files_processed[file_path]

    # Find lesson
    marker = f"export const {lesson_id}: DailyLesson"
    idx = content.find(marker)
    if idx == -1:
        print(f"\u274c {file_path}: {lesson_id} not found")
        continue

    # Check if already has interleaved
    lesson_block = content[idx:idx+80000]
    if '\u2500\u2500 Interleaved Practice:' in lesson_block:
        print(f"\u23ed  {lesson_id}: Already has interleaved practice")
        continue

    # Find exerciseSections closing
    es_idx = lesson_block.find('exerciseSections:')
    if es_idx == -1:
        print(f"\u274c {lesson_id}: exerciseSections not found")
        continue

    search_from = idx + es_idx
    es_end = content.find('\n  ],', search_from)
    if es_end == -1:
        print(f"\u274c {lesson_id}: Could not find exerciseSections closing")
        continue

    # Add Aralash section
    ids_str = ', '.join(str(start_id + i) for i in range(5))
    section_insert = f'''    {{ title: "Aralash", desc: "Interleaved Practice \u2014 {lesson_id} ni boshqa grammar topics bilan aralashtirish", color: 'bg-fuchsia-500', icon: '\U0001f504', ids: [{ids_str}] }},
  ]'''

    content = content[:es_end] + ',\n    ' + section_insert + content[es_end+4:]

    # Find exercises closing and add exercises
    idx2 = content.find(marker)
    lesson_block2 = content[idx2:idx2+80000]
    ex_end = lesson_block2.find('\n  ],\n  exerciseSections:')
    if ex_end == -1:
        print(f"\u274c {lesson_id}: Could not find exercises array ending")
        continue

    insert_point = idx2 + ex_end
    content = content[:insert_point] + '\n\n' + exercise_text + content[insert_point:]

    files_processed[file_path] = content
    print(f"\u2705 {lesson_id}: Added 5 interleaved exercises ({start_id}-{start_id+4}) + Aralash section")

# Save all files
print(f"\n{'='*50}")
for file_path, content in files_processed.items():
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"\u2705 Saved: {file_path}")

print(f"\n\u2705 All done! Modified {len(LESSONS)} lessons across {len(files_processed)} files.")
