-- ═══════════════════════════════════════════════════════════════════════════
-- EnglishPath — Lesson Exercise Answers + Vocab Progress + Viewed Tabs
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 1. Per-exercise/test/drill answers ──────────────────────────────────
create table if not exists public.lesson_exercise_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  section_index int not null default 0,
  exercise_id int not null,
  exercise_type text not null,
  section_type text not null check (section_type in ('exercise','test','drill')),
  answer jsonb not null default '[]'::jsonb,
  is_correct boolean not null default false,
  submitted_at timestamptz not null default now(),
  unique (user_id, lesson_id, exercise_id, section_type)
);

alter table public.lesson_exercise_answers enable row level security;

drop policy if exists "Users manage own lesson_exercise_answers" on public.lesson_exercise_answers;
create policy "Users manage own lesson_exercise_answers"
  on public.lesson_exercise_answers for all
  using (auth.uid() = user_id);

create index if not exists idx_lesson_exercise_answers_user_lesson
  on public.lesson_exercise_answers (user_id, lesson_id);

-- ─── 2. Vocab progress per lesson (flashcard known + quiz stats) ─────────
create table if not exists public.lesson_vocab_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  word_index int not null,
  known boolean not null default false,
  quiz_correct int not null default 0,
  quiz_wrong int not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id, word_index)
);

alter table public.lesson_vocab_progress enable row level security;

drop policy if exists "Users manage own lesson_vocab_progress" on public.lesson_vocab_progress;
create policy "Users manage own lesson_vocab_progress"
  on public.lesson_vocab_progress for all
  using (auth.uid() = user_id);

create index if not exists idx_lesson_vocab_progress_user_lesson
  on public.lesson_vocab_progress (user_id, lesson_id);

-- ─── 3. Viewed tabs per lesson ──────────────────────────────────────────
create table if not exists public.lesson_viewed_tabs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  viewed_tabs jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

alter table public.lesson_viewed_tabs enable row level security;

drop policy if exists "Users manage own lesson_viewed_tabs" on public.lesson_viewed_tabs;
create policy "Users manage own lesson_viewed_tabs"
  on public.lesson_viewed_tabs for all
  using (auth.uid() = user_id);

create index if not exists idx_lesson_viewed_tabs_user_lesson
  on public.lesson_viewed_tabs (user_id, lesson_id);
