-- ═══════════════════════════════════════════════════════════════════════════
-- EnglishPath — Lesson Session Resume Migration
-- Run this in: Supabase Dashboard → SQL Editor → New query → Run
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Lesson sessions table (cross-device resume) ─────────────────────────
create table if not exists public.lesson_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  tab text not null default 'grammar',
  current_section int not null default 0,
  test_section int not null default 0,
  completed_sections jsonb not null default '{}'::jsonb,
  completed_test_sections jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

-- ─── RLS ─────────────────────────────────────────────────────────────────
alter table public.lesson_sessions enable row level security;

drop policy if exists "Users manage own lesson_sessions" on public.lesson_sessions;
create policy "Users manage own lesson_sessions"
  on public.lesson_sessions for all
  using (auth.uid() = user_id);

-- ─── Indexes ─────────────────────────────────────────────────────────────
create index if not exists idx_lesson_sessions_user_lesson
  on public.lesson_sessions (user_id, lesson_id);
